src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

use VVH-geometry for roadlink properties in

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

Add change api for:               
-total_weight_limits      
-trailer_truck_weight_limits
-axle_weight_limits       
-bogie_weight_limits   
-height_limits          
-length_limits      
-width_limits

Numerical limits change api

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

Speed limits are now removed when the road link they are on is no more valid in VVH. Return these removed speed limits from change api.

Return also removed speed limits from change api

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitServiceSpec.scala

Improve filler so that it automagically fixes the errors that may appear or have been entered in the database and that it is stable (not flip-flopping)

Speed limit filler improvement

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitServiceSpec.scala

Extend speed limits to fill the geometry even if splitted.

Better description for Epsilon

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TimeDomainParserSpec.scala

…them.
Remove useless debugging information from TimeDomainParserSpec.

SpeedLimitFiller and Service improvements

---

conf/ci-vahti/digiroad2.properties
conf/dev/digiroad2.properties
conf/production/digiroad2.properties
conf/production2/digiroad2.properties
conf/staging/digiroad2.properties
conf/test/digiroad2.properties
conf/testing/digiroad2.properties
conf/testing2/digiroad2.properties
conf/training/digiroad2.properties
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/DummySerializer.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/CsvGenerator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/VVHSerializer.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/RoadLinkServiceSpec.scala
src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
src/main/scala/fi/liikennevirasto/digiroad2/util/JsonSerializer.scala
src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
src/test/scala/fi/liikennevirasto/digiroad2/util/JsonSerializerTest.scala

Improvements in data generation (caching strategy) and geometry output format (easier to process on receiving systems)

DROTH-7: Kalpa transfer performance increase

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala

Pull to main branch, bug affecting and reproducible in all environments.

Fix DROTH-210

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Additionally a batch job to check all entries.

Purge projected speed limit targets from unknown speed limits. 

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/GeometryTransformSpec.scala

Address translation functions from coordinates to road network address.

Droth 240 address translation

---

UI/src/view/MassTransitStopForm.js
digiroad2-oracle/src/main/resources/db/migration/V86__new_fields_for_MassTransitStop.sql

Creation of the fields in the Data Base to show Finnish and Swedish address;
Write the correct order to show this two Fields.

Droth 220 adding address field stop form

---

UI/autherror.html
UI/login.html
UI/tmpl/index.html

All titles with Digiroad2 changed to Digiroad

DROTH-223 Browser title of the OTH-application is changed from Digiroad2 to Digiroad

---

UI/src/model/SelectedManoeuvreSource.js
UI/src/view/ManoeuvreLayer.js

- Corrections at reselectManoeuvre and in getAdjacents;

DROTH-247 New manoeuvres bug about moving the map during manoeuvre creation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

DROTH 220 & DROTH-221
Mass transit stops addresses field to Kalpa-Api 
&
batch process to collect missing addresses from VVH in two phase process
(
1. collect addresses to stops which are missing both  Finnish and Swedish address
2. collect addresses which are missing either Finnish or Swedish address and existing address corresponds to one found in VVH.
)

Droth 221 bus stop address information batch process

---

UI/src/application.js
UI/src/modalconfirm/GenericConfirmPopup.js
UI/src/model/MassTransitStopsCollection.js
UI/src/model/SelectedMassTransitStop.js
UI/src/view/MassTransitStopForm.js
UI/src/view/MassTransitStopLayer.js
UI/test/MassTransitStopMoveSpec.js
UI/test/TestHelpers.js
UI/test/integration-tests.html
UI/tmpl/index.html
digiroad2-oracle/src/main/resources/db/migration/V86_1__update_yllapitajan_koodi_property_type.sql
digiroad2-oracle/src/main/resources/db/migration/V86__add_roska-astia_and_koroke_properties.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/oracle/MassTransitStopDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala
src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala

Implementation of the following tasks:
- DROTH - 243 roska-astia and koroke are added to the equipment information of stops;
- DROTH - 244 Generating LiVi identifier to stops in OTH;
- DROTH - 253 Notification than equipment information can disappear when mass transit stop is transferred from municipality to ELY;
- DROTH-252 Show pop-up if mass transit stop is moved more than 50 meters

Droth 144 OTH integration to Tierekisteri - stops

---

UI/src/less/site/linear-asset-form.less
UI/src/view/ProhibitionFormElements.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
digiroad2-oracle/src/main/resources/db/migration/V87__add_collums_prohibition_value_table.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/LinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDaoSpec.scala

- Modifications in Prohibitions Form for have the new field;
- Add additionalInfo at the class ProhibitionValue;
- Add Collums at Prohibition Value Table;
- Modifications in querys for have new field, fetchProhibitions and insertProhibitionValue methods;
- Unit tests for all modifications.

DROTH-246 (16) Vehicle limitations to have free text field for additional information

---

gruntfile.js
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
viite-UI/src/application.js
viite-UI/src/main.js
viite-UI/src/view/TileMapCollection.js
viite-UI/src/view/TileMapSelector.js

Esri grey background maps to Viite

Drvvh 264 new background map

---

UI/src/model/SelectedMassTransitStop.js
UI/src/utils/date-utils.js
UI/src/view/MassTransitStopForm.js
digiroad2-oracle/src/main/resources/db/migration/V91__add_inventory_date_property.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala

DROTH-272 to main DROTH-144 branch

Droth 272 inventory date

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculatorSpec.scala

Import batch run improvements, a filler starting point and address (re-)calculator for road parts.

Drvvh 288 initial load m value adjustments

---

viite-UI/src/view/LinkPropertyForm.js

DRVVH-300 Text "Yleinen tie" on the form will be changed to word "Maantie" and "Omistaja selvittämättä" to "Ei tiedossa"

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ContinuityChecker.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

A batch job to recalculate mValues after import task.

Drvvh 294 recalculate after initial mValue import

---

viite-UI/src/view/LinkPropertyLayer.js

Changed the Layer in order to highlight all the features if single clicked, and if double clicked to highlight the single one.

DRVVH-301  Selecting "Muu tieverkko": there is no difference if clicking once or using double-click

---

viite-UI/src/view/LinkPropertyForm.js

Changed the form in order to concatenate all the unique roadClasses separated with ','

DRVVH-319 If the road section selected has several road types, they will be listed sequentially in field "Tietyyppi"

---

viite-UI/src/view/LinkPropertyForm.js

Removed the segmentin ID field from the form, except in the header.

DRVVH-302 - Filed Segmentin-ID needs to be removed from the lower section of the form

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala

isFloating(...) on MassTransitStopService.scala is slow on big numbers of stops as every check hits the database. For 2000 stops this is 2000 queries.
Change the PointAssetOperations method isFloating parameters to
def isFloating(persistedAsset: PersistedPointAsset, roadLink: Option[VVHRoadlink], currentAdministrativeClass: Option[AdministrativeClass])
and adjust MassTransitStopService method accordingly. Give the parameter a value from the PersistedMassTransitStop object we have already loaded from database.

DROTH-323 Floating check is slow on MassTransitStops

---

viite-UI/src/view/Layer.js
viite-UI/src/view/LinkPropertyLayer.js

Fixed a bug in the drawing calibration markers.
From the first screenshot it is shown that the sometimes the calibration markers are being made without coordinates.
I made a filter on Layer.js in order to only let the ones with coordinates pass to be drawn.
After making this fix the error i got disappeared and I am not able to reproduce the issue.

DRVVH-308 Form disappears unexpectedly

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitionerSpec.scala
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/GeometryUtils.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/TileMapCollection.js
viite-UI/src/view/TileMapSelector.js

Added a method that converts a collection of points into a OpenLayers geometry, in order to be able to see if there is a interception.
Changed the whole highlighting process in the LinkPropertyLayer.

DRVVH-331 If you select a gap location of a road address (black), theselected target does not get highlighted on the map

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala

Include TR equipment on integration api

DROTH-338: include TR equipment data in Integration API

---

conf/dev/keys.properties
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/TierekisteriClient.scala
src/main/scala/fi/liikennevirasto/digiroad2/TierekisteriTestApi.scala

*Changed authentication to different header attribute. 
*Adds keys.properties file where  TR username and password should be added
( googlemapapi fallsback to old key  if it cannot find crypto-key/client-id combo, so it can be left commented out).

Droth 331 Authentication

---

UI/src/view/navigationpanel/ActionPanelBoxes.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala

Give privileges to busStopMaintainer role like operator role.

Droth 351 bus stop maintainer role not working without operator role

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Change on the batch process to get a bus stop match from TR

Qa november 2016 hotfix

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VVHClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala

Performance fixes and stylistic changes

Drvvh 450 performance fix

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/JsonSerializer.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala

Kalpa-API fix for 416 that fixes:
Unknown link-sources for all links,
Missing complementary links

Droth 355 kalpa fix

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/GeometryUtilsSpec.scala

Bug fix: geometry truncation algorithm to calculate distances between points as 2D when measuring the cut point.

DROTH-414 Fix geometry truncation algorithm

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitServiceSpec.scala

- Correct the fetchSpeedLimitsByLinkId;
- Create new updateSpeedLimitValue for expire and create new Asset;
- Correct split, separate and updateValues methods for use the new updateSpeedLimitValue;
- Correct Unit tests because the new method updateSpeedLimitValue.

DROTH-493 (US 362) Light Saving history information, speed limits

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/view/navigationpanel/ProjectSelectBox.js
viite-UI/src/view/navigationpanel/RoadLinkBox.js
viite-UI/test_data/UserRolesTestData.js

VIITE-284 User management streamlining
VIITE-282 Hide buttons if user does not have editing permission

VIITE-284 User management streamlining

---

viite-UI/src/model/ApplicationModel.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js

Added phased selection to the 135 User story, this branch encompasses user story 275.

Viite 277 checking the selection of floating road addresses

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/GeometryUtils.js
viite-UI/src/view/LinkPropertyLayer.js

Another change in the selection logic, when selecting a floating all the floatings that share the:
. Road Part Number;
. Road Number;
. Track Code and
. Are adjacent.
Are to be selected automatically.

Viite 275/292

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyLayer.js

The name of the branch is incorrect, the task made it in this branch is the VIITE-301.

Viite 301  Error when selecting floating road address links

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/router.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/RoadAddressProjectForm.js

This branch addresses the cancel button issued at 297 and 303.

Fixed functionality of the Perutta button.

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/roadaddress/oracle/RoadAddressDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/GeometryTransformSpec.scala

Droth 527 busstop interface use viite instead of vkm to locate oth stops in road registry

Droth 527 busstop interface use viite instead of vkm to locate oth stops in road registry

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Droth 572 modification of batch process fill existing information amount of lanes

Droth 572 modification of batch process fill existing information amount of lanes

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala

Add current username in the database, when clicked on Tallena button.

VIITE-318_CREATED_BY_gets_the_username_of_the_user_who_moved_the_floating

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/oracle/MassTransitStopDao.scala

DROTH-490 Point-like asset bearing value needs to be adjusted in OTH

DROTH-490 Point-like asset bearing value needs to be adjusted in OTH

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyLayer.js

Limited the selection when dealing with the Unknowns.

VIITE-322 - Map selection is not restricted after Valinta

---

viite-UI/src/model/LocationSearch.js
viite-UI/src/utils/backend-utils.js

Fixed API and code clean up in LocationSearch.js

Viite- 327 API fixed.

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/LinkPropertyLayer.js

Fixed the selections regarding tasks Viite-324 and Viite-323.

Viite 324 map selection is active after siira

---

viite-UI/src/view/LinkPropertyForm.js

Viite 305 viite edit mode aet and let values to be shown on floating

Viite 305 viite edit mode aet and let values to be shown on floating

---

viite-UI/src/map/CalibrationPointMarker.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/RoadLayer3.js
viite-UI/src/view/Styler.js

Many fixes regarding styles and displays.

Viite 329 visualisation needs attention

---

viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/Styler.js

Viite-341: floating flag is shown for every floating road segments per roadlink
Viite-354: OL3 fix: Weird visualisation in one ramp, see the attachment

Viite 341 floating flag is shown for every floating road segments per roadlink

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/ObstacleService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RailwayCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/TrafficLightService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Droth-588 point like assets are not moved to new link geometry

Droth 588 point like assets are not moved to new link geometry

---

viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/view/LinkPropertyForm.js

Small correction to unknown selection method.
Corrected the VALITUT LINKI section of the form.

VIITE-347 - Kelluvien muokkaustilan formin linkkitiedot tarkistettava

---

viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js

Corrected the processGroupOutput function when dealing with single objects.
Made sure that the openUnknowns selects only unique roads to current.

VIITE-359 - Peruuta has been pressed unknows color is still green after Peruuta

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala

Show the latest of road link modification dates (property modification date or vvh modification date) in UI form

DROTH-608: Road link modified date comparison fix

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ContinuityChecker.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala
viite-UI/src/model/RoadCollection.js
viite-UI/src/view/LinkPropertyForm.js

Additionally fix recalculation to happen only after all floating links are placed back and don't have floating links in recalculation.

VIITE-368 choose only continuous floating links for defloating

---

viite-UI/src/view/LinkPropertyLayer.js

Added calibration points to sirraa temporary layer

VIITE-367 Calibration point after pressing siirrä

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/ObstacleService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RailwayCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/TrafficLightService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingServiceSpec.scala

Make point assets snap to road link if geometry is adjusted a bit but not enough to make it float

Droth 588 point assets snapping to link

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDaoSpec.scala
viite-UI/src/view/RoadAddressProjectForm.js

- Status in database gets saved as null instead of 0
- Save buttons should activate only if all mandatory fields are given

VIITE-84, Bug fixes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/FloatingChecker.scala

Fix geometry checks on floating updates to be side code independent (road address geometry is not guaranteed to have directionality)

Viite 304 floating update bug fix

---

UI/src/view/LinkPropertyLayer.js
UI/src/view/SpeedLimitLayer.js

-Corrections on LinkPropertyLayer and SpeedLimits

DROTH-665 Maastokartta not shown in any environment:

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Droth-663 when a linear asset is expired mvalues are updated

Droth 663 when a linear asset is expired mvalues are updated

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDaoSpec.scala

Eliminated a println.
Addd a method to check the "checkCounter" and a method to update it.

VIITE-464-increment_projects_check_counter

---

viite-UI/src/view/RoadLayer3.js
viite-UI/src/view/Styler.js

Fixing to road width for certain zoom levels and fixing when zoom is greater than 1km

VIITE-457: Roads drawn incorrectly on certain zoom levels

---

UI/src/view/LinearAssetLayer.js
UI/src/view/SelectToolControl.js

and correction of selection alter draw

DROTH-702 Relates to DROTH-57: Polygon selection

---

viite-UI/src/less/site/map-plugins.less
viite-UI/src/view/MapView.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/tmpl/index.html

Viite 492: hower info popup for roadaddress in project link action selection mode

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

I made some changes on queryList method, because the case clauses only takes a max of 22 fields, and we need to validate 23 fields. To solve that problem, I created a "implicit val getRoadAddressChangeRow" that handles those 23 values

VIITE-467 Error in end_date in ROAD_ADDRESS table.

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/view/ProjectLinkLayer.js

This pull request includes 2 tasks:
VIITE-491 Make Seuraava-button work even if there is no reserved links
Opening project that has all the links processed

Viite 495 , Viite 491 opening project that has all the links processed

---

viite-UI/src/less/core/buttons.less
viite-UI/src/view/RoadAddressProjectEditForm.js
viite-UI/src/view/RoadAddressProjectForm.js

New button to open project changes table. No functionality implemented yet.

VIITE-511 Add "Avaa ilmoituksen yhteenveto"-button

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Update address table after every save if the project has no unfinished links. Verify by test that the address table has every road part.

Viite 499 address change table update on every save

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ViiteTierekisteriClientSpec.scala

Some dead code elimination committed just after merge :(

VIITE-454 refactor and dead code elimination, logging on exceptions

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala

Simplify code and fix tests to reflect changes.

VIITE-527 fix fetching of correct road link for a road address object

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala

DROTH-749 Relates to DROTH-496 tasosijainti-field needs to accept negative values (-1 or -11)

DROTH-749 Relates to DROTH-496 tasosijainti-field needs to accept negative values (-1 or -11)

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopImportApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/oracle/ImportLogService.scala

DROTH-748 LAST_EDITED_DATE to VVH complementary api

DROTH-748 LAST_EDITED_DATE to VVH complementary api

---

viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js
viite-UI/src/view/RoadAddressProjectForm.js

Pull request for VIITE-530, VIITE-531 and VIITE-539

Quick fixes board

---

UI/src/model/SelectedMassTransitStop.js
UI/src/view/MassTransitStopForm.js

first checks if road is one directional, then if the stop direction is the same as the road direction

DROTH-746_Change_infotext_on_bus_stop_direction_creation

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/ServiceRoadApiSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporterSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/ObstacleService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RailwayCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/TrafficLightService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/pointasset/oracle/OracleDirectionalTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/pointasset/oracle/OracleObstacleDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/pointasset/oracle/OraclePedestrianCrossingDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/pointasset/oracle/OracleRailwayCrossingDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/pointasset/oracle/OracleTrafficLightDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/LinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PointAssetOperationsSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/TrafficLightServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporterSpec.scala

Reverts finnishtransportagency/digiroad2#784

Revert "Droth 747 link source field for assets to kalpa api"

---

digiroad2-oracle/src/main/resources/db/migration/V116__Geometryfield_for_missinglinks.sql
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressFiller.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala

added  geometry row to missing_road_address table, updated corresponding case class and adjusted sql query for creating missing road address

Viite 544 geometry column for missing links

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala

Droth-740 bus stops not attached to road links

Droth 740 bus stops not attached to road links

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala

DROTH-763_Last_modified_timestamp

DROTH-763_Last_modified_timestamp

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala

- Chnage the value of loppupvm and inventointipvm to moving date when moving bus stops more 50 mts.

DROTH-727 When moving bus stops more 50 mts (in state roads) inventointipäivä (inventory date) is not created for the newly created stop

---

viite-UI/src/view/RoadAddressProjectEditForm.js

This pull request includes 3 tasks:
VIITE-452 Other validation of the save
VIITE-442 Prefill road  numbers and road part numbers of selcted road links to the form
VIITE-584 Also the code numbers should be on the drop down menu

Viite 452 other validation of the save

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/RoadAddressProjectEditForm.js

Contains refactoring to VIITE-449 and VIITE-451

Viite 585 connect save button to backend

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/oracle/MassTransitStopDao.scala

DROTH-764 ELY stops not shown on staging

DROTH-764 ELY stops not shown on staging

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/images/link-properties/arrow-drop-pink-light.svg
viite-UI/src/map/LinkPropertyMarker.js
viite-UI/src/view/ProjectLinkLayer.js

Added new LinkStatus = 2 for New road addresses. Pink properties for this new addresses styling

VIITE-590 Visualization:  New road addresses are visualized as pink lines

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/GeometryTransformSpec.scala

- Modification at resolveAddressAndLocation method in GeometryTransform Class to fix the side_code value when geometry is digitazed to the opposite direction than the road address is growing.

DROTH-791 - Bus stops located in road registry while using VIITE

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDaoSpec.scala
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js

This pull request incluedes tasks: 
VIITE-614 Saving multiple times to the same road number and road part, updating the existant road address
VIITE-612 Extra calibration points appear in UI, when using the flip function

Viite 614 saving multiple times to the same road number and road part

---

viite-UI/src/map/LinkPropertyMarker.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js

This pull request includes 3 tasks:
-VIITE-603 The "Käännä kasvusuunta" button shouldn't be in the form when selecting the "Lakkautus"
- VIITE-617   Direction markers should be drawn on top of selected road links
- VIITE-522 Anomaly type 2 links have teardrops when shown as   targets for floating transfer. it should be a question mark.

Viite quick board

---

UI/src/utils/backend-utils.js
digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VVHClient.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/VVHClientSpec.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectLinkPartitioner.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/LinkPropertyLayerStyles.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js
viite-UI/src/view/Styler.js

Suravage links to map
Contains task VIITE-601 (frontend) and VIITE-602 (backend)   work done in 602 branch

VIITE-601&602 

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

Enable frozen link data fetch by server configuration, refactor configuration to separate case class object.

VIITE-634 enable frozen link service for road address import in QA

---

UI/src/application.js
UI/src/model/PointAssetsCollection.js
UI/src/model/TrafficSignsCollection.js

DROTH-833_Servicepoints_are_not_shown_on_map

DROTH-833_Servicepoints_are_not_shown_on_map

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

Includes project section calculator changes.

Viite 658 delta calculation for extending existing

---

viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js
viite-UI/src/view/RoadAddressProjectForm.js

*Some pop-Up navigation fixes regarding the 615 ui revamp

Viite-615_ui_navigation_fixes

---

viite-UI/src/less/core/buttons.less
viite-UI/src/less/core/forms.less
viite-UI/src/view/RoadAddressProjectForm.js

*Adjusted the Div with the reserved road parts so that the X button is centered
*Also it's closer to the text
*Also the labels and values should now be centered
*Also the X button should be smaller

VIITE-689 Visualisation / allignment of reserved road parts on project form

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

No need for new code, added test and did deprecation on method

Viite 682 calculator for new plus transfer

---

viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/view/RoadAddressProjectEditForm.js

*Changed how the dropdown modifiers like "hidden" or "selected" are handled.
*"New" will be the only option that is available to select when the roadlinks are unknown, grey or suravage.

VIITE-695_change_drop_down_on_grey_unknown_or_suravage_road_links

---

UI/src/asset-type-layer-specifications.js
UI/src/view/LinearAssetLayer.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/TierekisteriTestApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/TierekisteriClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/asset.oracle/OracleAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperations.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/TierekisteriClientSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala

Droth 808 tr to oth line assets with location

Droth 808 tr to oth line assets with location

---

UI/src/view/SpeedLimitLayer.js

- Add function for speedLimit:unselect event
- Correction for cut without changes and correction for cut with changes

DROTH-934 Cutting tool is not working properly with speed limit asset:

---

UI/src/view/MassTransitStopForm.js
digiroad2-oracle/src/main/resources/db/migration/V124__update_property_to_required.sql

The field Ei tiedossa will be removed from the form in DROTH-912

DROTH-913 Bus stops: Ylläpitäjä as mandatory field: 

---

UI/src/map/MassTransitMarker.js

-canvas fill color changed according to validity period

DROTH-59_Different_visualization_for_bus_stops

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
viite-UI/src/model/ProjectChangeInfoModel.js
viite-UI/src/view/ProjectChangeTable.js

Project change table update when returning empty list after reversion

VIITE-697 fix

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/less/site/asset-form.less
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/view/RoadAddressProjectEditForm.js

*Added a Red "!" sign on the form (invisible before editing)
*Said sign goes visible if the user changes the endDistance (LOPUSSA) value to a value different of the original
*Restoring the Original value will remove said sign
*Added a parameter on the data to send to backend called userDefinedEndAddressM (is initially sent as -1)
*If the endAddressM is changed at the end then the userDefinedEndAddressM is changed to that
*Backend is reading said value

VIITE-743 - UI: changes to form

---

UI/src/view/LinearAssetLayer.js

- Fix when linear asset is unselected.

DROTH-938 Cutting tool is not working properly with width asset

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Added unit test to validate the correct behavior

Bug already fixed in VIITE-753. 

---

viite-UI/src/model/RoadCollection.js
viite-UI/src/view/LinkPropertyLayer.js

*Added layer to draw the reserved (NotHandled) roads from a project
*Added the projectStyler in order to attribute the correct style to the reserved features

VIITE-750 - Visualisation of project screen needs addition

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/GraphPartitioner.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectAddressLink.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectLinkPartitioner.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/RoadAddressLinkPartitioner.scala

grouping of links by being in project or not and subgroup rules
applied the 0.1 meter connectedness rule

VIITE-767 changes to project link partitioning logic

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/model/RoadAddressProjectCollection.js

failed mValue calculation should not be an error on update
show API returned error message in UI

VIITE-770 Fix incorrect error message on link update

---

viite-UI/src/view/RoadAddressProjectForm.js

*Isolated the mechanism that displayed correct lower buttons on edit mode
*Replicated said mechanism when clicking the remove Reserved road part
*Corrected a small bug on the textFieldChangeHandler function

VIITE-757_wrong_form_after_removing_a_road_part

---

viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectForm.js

Also detect if was a single or double click and select links accordingly after the Haluatko poistaa tien valinnan ja hylätä muutokset popup.

VIITE-756 Enable tallenna button on edit project info

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteTierekisteriMockApi.scala

instead of checking key we check key value

VIITE-TRMock always reads values as non null

---

viite-UI/src/model/ApplicationModel.js
viite-UI/src/view/LinkPropertyForm.js
viite-UI/src/view/RoadAddressProjectForm.js

*Changed Cancel behaviour when editing an already opened project
*Added display of confirmation message
*Enforced an wait period on opening the project selection screen after a save is triggered

VIITE-748 - Poistu-painikkeessa häiriö / Poistu-button has a bug

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala

fix not checking the correct end of link vs. side code

VIITE-752 Fix link ordering algorithm 

---

viite-UI/src/view/ProjectLinkLayer.js

*Ended the oppression of the suravage links, they can now bear calibration points

VIITE-796 - "Etäisyyslukema"

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/GuestimateGeometryForMissingLinks.scala
viite-UI/src/view/RoadAddressProjectEditForm.js

*Added a selection of discontinuity to the form;
*Corrected a potential problem with the withGeometry method
*Created analogous methods of Guestimate but with ProjectLinks

VIITE-818 - Discontinuity value on form is wrong when reselecting homogenized links

---

viite-UI/src/less/site/map-plugins.less
viite-UI/src/view/TileMapSelector.js

*Added the checkbox that controls suravage visibility
*Connected checkbox value to the visibility of suravage links

VIITE-788 - Suravage linkit piirtoon ja pois piirrosta

---

viite-UI/src/application.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js

High priority PR in order pilot user to test application

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala

Didnt actually solve anything. Roadlink for given linkId is not coming from VVH and was giving no error.

Error message if for some reason the road link is not coming from VVH

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

* Recalculate after resplit is written, not after previous split is reverted.
* on road type and discontinuity update check that the list has at least one item

VIITE-844 split road address recalculation after save

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/src/application.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/ProjectLinkStyler.js
viite-UI/src/view/SplitForm.js
viite-UI/test/integration-tests.html
viite-UI/tmpl/index.html

Form common parts moved into one utility class; some room for improvement exists.
Small bugs fixed and dead code eliminated.
* Project DAO not checking the project id on delete by link id
* Backend created separately for forms and not used from the application (breaks testing stuff)

Viite 849 form refactor

---

viite-UI/src/application.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js
viite-UI/src/view/ProjectLinkLayer.js

Viite project mode ui bugs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadWidthService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/RoadWidthServiceSpec.scala

Droth 5 fix road width issue

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VVHClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala

Mapping the road address changes in change types
* 5+6 = Divided into two or more links
* 3+4 = Length increases on link
* 7+8 = Length decreases on link
* 11, 13, 14, 15 = Link gets removed and road address goes always floating.

Viite 507 + 533 change info mapping to road address

---

viite-UI/src/less/site/action-panel.less
viite-UI/src/less/site/asset-form.less
viite-UI/src/view/navigationpanel/ProjectListModel.js

*Reformulating the Project Selection window with new fields

VIITE-852 - Projektilistan jäsentely / Ordering of the projects list

---

viite-UI/src/less/core/variables.less
viite-UI/src/less/site/action-panel.less
viite-UI/src/view/navigationpanel/RoadLinkBox.js

*Modified the legend part when entering in or out of the project mode

VIITE-866 Oma legenda toimenpidenäytölle

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/model/ProjectAddressLink.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceTRSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDaoSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/TrackSectionOrderSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/package.scala

Includes generic fixes for project coordinates, default values, time stamp handling etc

Viite 873 geometry on reservation

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleMaintenanceDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MaintenanceServiceSpec.scala

Droth 969 modification of huoltotiet api to geo json

Droth 969 modification of huoltotiet api to geo json

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/src/view/navigationpanel/ProjectListModel.js

VIITE-914 Projects in project list are not sorted by ELY-code
VIITE-915 ELY-code and username are missing from projects rejected by Tierekisteri in project list

Fixes to project list (VIITE-914 & VIITE-915)

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala

My reasoning is that convertToRoadAddress is gonna be called by updateRoadAddressWithProjectLinks.
The method updateRoadAddressWithProjectLinks is the one that will be called via batch that will create the road addresses based on the project links after TR says ok.
In the convertToRoadAddress we have both the convertProjectLinkToRoadAddress and createSplitRoadAddress which both will create roadAddresses so, it was as question on changing the geometry and geometry timestamp where needed.

*Adding projectLink geometry on the conversion from ProjectLink to RoadAddress object

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala

Using default road type (saved in VIITE database) instead of guessing. Just guess road type when is Unknown in database

VIITE-919 Tietyyppi changes when performing numbering operation

---

UI/src/application.js
UI/src/less/site/map-plugins.less
UI/src/view/TrafficSignToggle.js
UI/src/view/VioniceLayer.js
UI/test/integration-tests.html
UI/tmpl/index.html
conf/dev/keys.properties
gruntfile.js
package.json
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

Droth 829 vionice data visualized in oth

Droth 829 vionice data visualized in oth

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/RoadCollection.js
viite-UI/src/router.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/navigationpanel/EditModeToggleButton.js
viite-UI/src/view/navigationpanel/SearchBox.js

Viite 935 ui road address history view

---

viite-UI/src/view/NavigationPanel.js
viite-UI/src/view/navigationpanel/SearchBox.js

*Added an ID to the affected ui elements
*Filtered out the newly given ID's

VIITE-949 - UI search buttons in project mode are disabled

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperations.scala

DROTH-1072-Gaps in the tr speed limit asset:

---

UI/src/view/SpeedLimitLayer.js

-TrafficSigns showing after map is moved

DROTH-1082:

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala

Remove numbering action filtering from reserved road parts.

VIITE-964 remove filtering of numbering action from reserved road parts

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessage.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/BusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/TerminalBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/TierekisteriBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/oracle/MassTransitStopDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala

Correct connectedToTerminal info on Vallu-Xml and Kalpa-Api

DROTH-1077 Correct Missed connectedToTerminal info on Vallu-Xml and Kalpa-Api

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/model/ProjectChangeInfoModel.js
viite-UI/src/view/ProjectChangeTable.js

Missing the Finnish text messages.

Viite 942 discontinuity checks

---

viite-UI/src/model/ProjectCollection.js
viite-UI/src/view/FormCommon.js
viite-UI/src/view/ProjectChangeTable.js
viite-UI/src/view/ProjectEditForm.js
viite-UI/src/view/ProjectForm.js
viite-UI/src/view/ProjectLinkLayer.js

This pull request includes several tasks that are related with PROJECT mode, from quick board and sprint 14 - task VIITE 956:
- VIITE-956 Exiting a project with a new road address stops creation of a new project
- VIITE-902 User can't leave a project in the middle of creating an action or edits
- VIITE-903 user can't edit a project's information in the middle of creating a Toimenpide or edits
- VIITE-906  a confirmation is requested from the user before sending Tieosoitemuutosilmoitus to Tierekisteri
- VIITE-907 exiting the Projektitila

Viite quick fixes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

Small adaptation to the apply_change_information_to_road_address_links in order to validate road addresses

VIITE-967 - check change information works also with roadaddress history

---

viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/SplitForm.js

Fixed the issues with deselecting split links.
Issue was in the triggering of a change event related to the dropDown_0 selected values.

VIITE-965 - When unselecting splitted links, several issues appear

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
viite-UI/src/model/ProjectCollection.js
viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/utils/GeometryUtils.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/ProjectLinkStyler.js

Splitted blue cross line now appears when selecting splitted links.
Terminated line appears with different style

Viite 988 add blue cross line also when selecting split links

---

viite-UI/src/less/site/project-change-table.less
viite-UI/src/view/ProjectChangeTable.js

Contains VIITE-924 and VIITE-927

Viite 924 error in the change table when it is reopened

---

viite-UI/src/less/core/forms.less
viite-UI/src/view/FormCommon.js
viite-UI/src/view/LinkPropertyForm.js

Link selection now shows attributes description along with codes

VIITE-908 Project link selection now shows description along with codes

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
viite-UI/src/model/RoadCollection.js
viite-UI/src/model/SelectedLinkProperty.js
viite-UI/src/utils/backend-utils.js
viite-UI/src/view/LinkPropertyLayer.js

This contains fix for second part of VIITE-1020 (Anomalous geometry of map and info on the form)

Viite 1020 incorrect ely border validation and anomalous geometry in minor zoom cases

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VVHClient.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala

Change the import road address batch to get also the suravage VVH-links.
Change the update road address geometry batch to handle the suravage links as well.

Viite 1023 Suravage links included in the initial road address download

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala

Transformed a filterNot to a filter and changed first condition.

VIITE-1055 - Tarpeeton tarkastusilmoitus / unnecessary validation notification

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala

Included in fetchByLinkIdToApi and the mass query a filter to not fetch historic links.

VIITE-1110 VIITE API contains road address history

---

UI/src/model/LinearAssetsCollection.js
UI/src/utils/backend-utils.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala

-Digiroad2Api: fetching complementary road links on point and linear assets now has the option to return road address info.

DROTH-1161_road_address_hover_fix_on_bus_stop_layer

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

-added numeral and textual value services to IntegrationApi

DROTH-1164 Missing value fields in Kalpa API

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

change to reoadaddresslinkbuilder methods to take road address ely instead of making a guess

VIITE-1115_ely-code from db when possible

---

digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

added requirment for conversiontable name as input to importroadaddress batch.
will be read as second argument

VIITE-1119_conversion-table has to be defined in roadaddressimport

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala

Added check for ending ramps that are connecting roundabouts which should have Minor Discontinuity for those cases. 
Added info mapping for error objects to fornt-end

Viite 1118 wrong jatkuvuus code when ramp road part ends in roundabout

---

UI/src/application.js
UI/src/less/site/map-plugins.less
UI/src/model/AssetsVerificationCollection.js
UI/src/model/LinearAssetsCollection.js
UI/src/model/PointAssetsCollection.js
UI/src/model/SpeedLimitsCollection.js
UI/src/utils/backend-utils.js
UI/src/view/LinearAssetLayer.js
UI/src/view/MapView.js
UI/src/view/MunicipalityDisplay.js
UI/src/view/PointAssetLayer.js
UI/src/view/SpeedLimitLayer.js
UI/test/SelectedSpeedLimitSpec.js
UI/test/integration-tests.html
UI/tmpl/index.html
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/VerificationService.scala

DROTH-1160_Showing_municipality_name_on_the_OTH_UI

Droth 1160 showing municipality name on the oth ui

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala

-added missing ProhibitionSaveProjected in Digiroad2Context

DROTH-1193 Prohibition actor fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala

Droth 1155 strange timestamp referring to dr1 conversion on asset added in 2017

Droth 1155 strange timestamp referring to dr1 conversion on asset added in 2017

---

UI/src/model/LinearAssetsCollection.js
UI/src/utils/backend-utils.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearMassLimitationService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/StateSpeedLimitTierekisteriImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/LinearMassLimitationServiceSpec.scala

DROTH-1215 Hoover_for_road_info_does_not_work_on_mass_restrictions

DROTH-1215 Hoover_for_road_info_does_not_work_on_mass_restrictions

---

UI/src/view/linear_asset/manoeuvreLayer.js

DROTH-1117 Issues with manoeuvre visualization

DROTH-1117 Issues with manoeuvre visualization

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala

- Added if clause when updating the changeSet method projectSpeedLimit of SpeedLimitFiller.

DROTH-1289 Speed limit asset disappearing on the link when zooming or panning

---

UI/src/router.js
UI/src/view/linear_asset/speedLimitLayer.js
UI/src/view/navigationpanel/speedLimitBox.js
UI/src/view/providers/selectToolControl.js

DROTH-1301 Traffic signs not shown

DROTH-1301 Traffic signs not shown

---

UI/src/application.js
UI/src/assetTypeConfiguration.js
UI/src/utils/property-utils.js
UI/src/view/point_asset/pointAssetForm.js
UI/test/integration-tests.html
UI/tmpl/index.html

DROTH-1288 Traffic signs should have value validation on form

DROTH-1288 Traffic signs should have value validation on form

---

project/build.scala
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
start.sh

Monitoring for OTH

---

UI/csv_import.html
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleMaintenanceDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala

- New Option on CVS import HTML page to import railroad service roads data;
- Added new class for Import Maintenance Roads using CSV files;
- Added new input on ImportDataApi.

DROTH-1306 Batch process to implement new code values to railroad service roads

---

UI/src/application.js
UI/src/model/selectedLinearAsset.js
UI/src/view/linear_asset/linearAssetForm.js
UI/src/view/linear_asset/linearAssetLayer.js
UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
UI/src/view/providers/selectToolControl.js

DROTH-1357 && DROTH-1356 Multiple selection toll, split and separete do not work properly

DROTH-1357 && DROTH-1356 Multiple selection toll, split and separete do not work properly

---

UI/src/view/linear_asset/linearAssetLayer.js
UI/src/view/linear_asset/linearAssetMassUpdateDialog.js

DROTH-1379 Slowness detected on multi Select

DROTH-1379 Slowness detected on multi Select

---

UI/src/less/site/global.less
UI/src/view/dynamicAssetForm.js
UI/src/view/linear_asset/careClassLayer.js

DROTH-1443 Care Class UI issues in Firefox

Fix css scroll problems in firefox

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriTrafficSignAssetClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/StateSpeedLimitTierekisteriImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/TierekisteriClientSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala

Droth 1476 traffic signs with liikvast information

Droth 1476 traffic signs with liikvast information

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavingService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Droth 1466 apply changes not set last adjustment timestamp and modified vvh generator

Droth 1466 apply changes not set last adjustment timestamp and modified vvh generator

---

UI/src/view/municipalityWorkList.js
UI/src/view/speedLimitWorkList.js
UI/src/view/workListView.js

DROTH-1500 add tbody to worklists

---

UI/src/less/site/asset-form.less
UI/src/model/selectedPointAsset.js
UI/src/view/point_asset/pointAssetForm.js

Droth 1533 service point unformatted form

Droth 1533 service point unformatted form

---

UI/src/less/site/modals.less
UI/src/view/feedbackDataTool.js
UI/tmpl/index.html

Droth 1529 text is missing from the feedback tool email

Droth 1529 text is missing from the feedback tool email

---

UI/src/less/site/asset-form.less
UI/src/less/site/modals.less
UI/src/view/feedbackApplicationTool.js

DROTH-1570_Feedback_UI_improvements

---

UI/src/less/site/global.less

DROTH-1573_dblclick_map_fix

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

- Fix validateUserMunicipalityAccessByLinkId method in case of link id for asset not found.

DROTH-1505 A floating obstacle cannot be deleted

---

UI/src/view/navigationpanel/actionPanelBox.js
UI/src/view/navigationpanel/careClassBox.js
UI/src/view/navigationpanel/carryingCapacityBox.js
UI/src/view/navigationpanel/heightLimitationBox.js
UI/src/view/navigationpanel/linearAssetBox.js
UI/src/view/navigationpanel/manoeuvreBox.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/navigationpanel/navigationPanel.js
UI/src/view/navigationpanel/pavedRoadBox.js
UI/src/view/navigationpanel/pointAssetBox.js
UI/src/view/navigationpanel/roadLinkBox.js
UI/src/view/navigationpanel/serviceRoadBox.js
UI/src/view/navigationpanel/speedLimitBox.js
UI/src/view/navigationpanel/trSpeedLimitBox.js
UI/src/view/navigationpanel/trafficSignBox.js
UI/src/view/navigationpanel/weightLimitationBox.js
UI/src/view/navigationpanel/widthLimitationBox.js
UI/src/view/navigationpanel/winterSpeedLimitBox.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala

Droth 1609 municipality check mark

Droth 1609 municipality check mark

---

UI/src/utils/validity-directions.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala

- unknown type added to validity directions file;
- Side code value set to Unknown when create floating traffic signs.

DROTH-1616 (US 1471) Traffic signs with no direction and not floating

---

UI/src/utils/backend-utils.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala

Droth 1679 municipality list missing from csv import

Droth 1679 municipality list missing from csv import

---

UI/src/application.js
UI/src/assetTypeConfiguration.js
UI/src/view/navigationpanel/pedestrianCrossingBox.js
UI/src/view/point_asset/pointAssetForm.js
UI/src/view/point_asset/pointAssetLayer.js

DROTH-1692 Quality list error with pedestrian crossing

DROTH-1692 Quality list error with pedestrian crossing

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDaoSpec.scala

DROTH-1689 Undefined links on error list

DROTH-1689 Undefined links on error list

---

UI/src/controller/roadCollection.js
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Droth 1704 administrative class doesnt refresh on cancel

Droth 1704 administrative class doesnt refresh on cancel

---

UI/src/router.js
UI/src/view/inaccurateWorkList.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AxleWeightLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/BogieWeightLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/HeightLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/LengthLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SevenRestrictionsLimitationValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/TotalWeightLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/TrailerTruckWeightLimitValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/WidthLimitValidator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SevenRestrictionsLimitationValidatorSpec.scala

DROTH-1708_Mass_restriction_quality_list

DROTH-1708_Mass_restriction_quality_list

---

conf/production/digiroad2.properties
conf/production2/digiroad2.properties
conf/staging/digiroad2.properties
conf/testing/digiroad2.properties
conf/testing2/digiroad2.properties

on;
staging
qa 1 and 2
prod 1 and 2
conf files

DROTH-1756: domain name change

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriTrafficSignAssetClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/StateSpeedLimitTierekisteriImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/TierekisteriClientSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
tr-import-data.sh

DROTH-1768 Split Tierikisteri TrafficSign importer by trafficSign groups

DROTH-1768 Split Tierikisteri TrafficSign importer by trafficSign groups

---

UI/src/controller/careClassCollection.js
UI/src/less/site/linear-asset-form.less

related with some forms: MassTransitLa…ne, CareClass, CarryingCapacity and Prohibitions

DROTH-1647 CSS fixes on styles 

---

UI/src/application.js

DROTH-1864 Asset menu order

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AssetValidator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Fix performance issue on marge additional panels

fix DROTH-1996 Tierekisteri traffic signs: changes in value extraction

---

UI/src/assetTypeConfiguration.js

- Added validation to avoid starting date later than the end date on roadDamagedByThaw and roadWorks assets.

DROTH-2027 (US 1863) It's possible set starting date later than end date when edit

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

DROTH-2102 Wrong links on the private road list

---

UI/src/application.js
UI/src/view/linear_asset/speedLimitForm.js

-Fixed form loading first than verification

DROTH-2099 Unknown speed limit list disappears some times

---

UI/src/view/dynamicAssetForm.js
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

DROTH-217 No new parking prohibitions are created from some traffic signs

DROTH-217 No new parking prohibitions are created from some traffic signs

---

UI/src/application.js
UI/src/authorizationpolicies/authorizationPolicy.js
UI/src/view/linear_asset/speedLimitForm.js
UI/src/view/municipalityWorkList.js
UI/src/view/navigationpanel/actionPanelBox.js

-check for checkmark div, then append icon.
-changed the conditional for fetching roles on speed limit form. previous condition is always true if user is municipality user

DROTH-2171 Double checkmark on checked asset:

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

added more cases to functional class mapping
see JIRA ticket DROTH-1467 for more info

DROTH-1467_Wrong_functional_class_on_road_link

---

UI/src/view/point_asset/trafficSignForm.js

- Added new event to force the field to be filled. (Copy from DROTH-2224_Date_fields_for_traffic_signs)

DROTH-2232 Traffic Sign doesnt allow update

---

ci/pipeline/dev_task_runner
ci/pipeline/prod_task_runner
ci/pipeline/qa_task_runner
ci/pipeline/staging_task_runner
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

-Created new batch to add obstacles from the shapefile
-Created query to fetch the shapefile info and transform it to Obstacle
-Added the batch to the task runners
-Modify the getClosestRoadlinkFromVVH method to receive a radius

DROTH-2216 Obstacle batch

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala

- Fix the slowness at Staging environment by fixing the order of the queries for speedLimits asset.

DROTH-2271 Check slowness at staging environment after deploys

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala

- Fix the update information for speed Limits

DROTH-2271_Check_slowness_staging_environment_after_deploys

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala

- Fix the suggested assets-button missing in municipality management page for some assets

DROTH-2273-Suggested_assets_button_missing_in_municipality_management_page

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala

-Updated the fill topology for the private road information no based more on the change type
-Created new tests

DROTH-2305 Private road information disappears from some links

---

UI/src/model/selectedLinkProperty.js
UI/src/view/link_property/linkPropertyForm.js

-Removed undefineds from roadPartNumbers so it will appear the right information and not "Infinity"
-Switch if order to appear correct information

DROTH-2309 (US 2059) Address numbers don't show as they should

---

conf/dev/keys.properties
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

-Renamed proxy to the right name
-Cleaned unused vionice code

DROTH-2311 (US 2143) Calls about the new VKM are returning a 404 error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

- Added code to contemplate road without exit but with previus speedlimit

DROTH-2307 OTH crashes on both production servers

---

UI/src/authorizationpolicies/authorizationPolicy.js
UI/src/authorizationpolicies/linearAssetAuthorizationPolicy.js
UI/src/authorizationpolicies/linearStateRoadAuthorizationPolicy.js

- Added a modification rights to state roads in Ahvenanmaa

DROTH-2321Modifing rights to state roads in Ahvenanmaa

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala

- Fix Kalpa export due 500-error

DROTH-2334 KalpaApi_returning_500_error_for_certain_asset_types

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala

- Fix create_prohibition_using_traffic_signs batch

DROTH-2329 create_prohibition_using_traffic_signs batch not working

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

- Add new validation/update in case of Admin class of Unknown SpeedLimits doesn't match;
- Modify the "link_id in" condition to use a MassQuery.

DROTH-2331 Speed limit search not working

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleDirectionalTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OraclePedestrianCrossingDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleRailwayCrossingDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleServicePointDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficLightDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrailerTruckWeightLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleWidthLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PropertyValidator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/UserNotificationServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WeightLimitServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WidthLimitServiceSpec.scala

Droth 2335 extraction railway and pedestrian crossing fails

---

UI/src/assetTypeConfiguration.js
UI/src/model/selectedLinearAsset.js
UI/src/view/dynamicAssetForm.js

-Fixed problems on dynamic linear asset selection that would lock the user on a linear asset when selected
-Fixed visual bug on checkbox view mode

DROTH-2332 Service road problems

---

UI/src/view/point_asset/servicePointForm.js

-Fixed name/weight fields not being saved as they should

DROTH-2344 (US 2142) Value field disappears

---

UI/src/assetTypeConfiguration.js

-Fixed a bug where OTH didn't allow saving road damaged by thaw without date

DROTH-2348 General RoadDamagedByThaw info cannot be saved in OTH

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

- New changes to try to optimize the process

Droth 2326 batch resolve frozen links doesnt run with this vkm version v2

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala

-Resolved a bug where linear assets would disappear from map because the properties of the assets where not in the same order

DROTH-2352 - Road links don't show up when updating RoadDamagedByThaw

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

-fixed a bug on obstacles and railway crossing extractions

DROTH-2369 Extraction problems

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala

-Fixed a bug where part of the query was being malformed

DROTH-2371 Digiroad2-api-error

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

- Fix the Value field in Kalpa for SevenRestrictions

DROTH-2375 Value field errors in Kalpa

---

UI/src/less/site/content-box.less

- Fix a visual bug in the municipality work-list for municipality users when window size is very small

DROTH-2377 visual bug in municipality work-list

---

UI/src/model/locationSearch.js
UI/src/utils/backend-utils.js
UI/src/utils/locationInputParser.js
UI/src/view/navigationpanel/searchBox.js
UI/test/unit-tests/locationInputParserSpec.js

- Fix the search box not finding bus stops

DROTH-2378_search_box_not_finding_bus_stops && DROTH-2381_search field doesn't find streets in some municipalities

---

UI/src/view/linear_asset/piecewiseLinearAssetFormElements.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

-Fixed a bug where possibleValues were not appearing because there was one less argument in the function
-Fixed a bug where WinterSpeedLimit value was being treated as a DynamicValue and not as a NumericValue

DROTH-2383 Winter speed limit not working

---

UI/src/view/navigationpanel/massTransitStopBox.js

-Added bus stop symbols on legend
-Refactor some code

DROTH-2387 (US 2119) Bus stop symbols are not shown in legend

---

UI/src/view/inaccurateWorkList.js
UI/src/view/verificationWorkList.js

DROTH-2393 Quality error list empty

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

- Fix the adjustLanesSideCodes function to remove sub-lanes when sideCode is not ok

DROTH-2382 V2

---

UI/src/assetTypeConfiguration.js

- Fix the edit, save, delete in new created signs

DROTH-2411 (U.S:2262)

---

UI/src/authorizationpolicies/authorizationPolicy.js

- Fix the validation to allow users with municipalities in Ahvenanmaa

DROTH-2402- Modifying assets in Ahvenanmaa

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala

- Fix the validation to allow users with municipalities in Ahvenanmaa

DROTH-2402 v2

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala

-Removed lane configuration if a lane inside is cut so it would not group in a chain

DROTH-2440 Additional lane is shown as whole even though it is cut

---

UI/src/authorizationpolicies/authorizationPolicy.js
UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js
UI/src/authorizationpolicies/pointAssetAuthorizationPolicy.js
UI/src/authorizationpolicies/pointStateRoadAuthorizationPolicy.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala

- Allow users in Ahvenanmaa to place point assets in state roads.

DROTH-2435 Operator_and_municipality_users_cannot_edit_points_on_Ahvenanmaa_state_roads

---

UI/src/authorizationpolicies/authorizationPolicy.js

- Fix authorizationPolicy to fix the tests

DROTH-2435 Operator and municipality users cannot edit points on Ahvenanmaa state roads

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

- Fix the lane creation when traffic direction change

Droth 2439 problems with additional lanes when changing the direction main lane

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala

-Fixed a bug where the filler was trying to update a id = 0
-Fixed a bug where the filler was changing the lane code and attributes incorrectly

DROTH-2426 Lanes: API error in QA

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriPointConversionImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriPointConversionImporterSpec.scala

- Apply the fix at new publicId for the mass restrictions like weight and height types.

DROTH-2445 Errors in mass restrictions from Tierekisteri

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

-Created new batch to export private road data in csv

DROTH-2469 Private road data

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

-Rollback changes to "combine" operation in laneFiller
-Deleted deprecated test
-Refactor checkSideCodes and adjustLanesSideCodes functions

DROTH-2488 Lane cut won't save properly

---

UI/src/view/municipalityWorkList.js

-Fix bug where municipality page was not loading

DROTH-2505 Municipality page for Akaa does not load

---

UI/src/assetTypeConfiguration.js
UI/src/view/dynamicAssetForm.js
UI/src/view/workListView.js

-Fixed some bugs related with worklists of 3 asset types

DROTH-2473 Work list problems

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/OracleAssetDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

-Add Ahvenanmaa municipalities as exceptions to TR-import batches

DROTH-2508 Restore expired assets in Ahvenanmaa

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala

-Replaced some withDynSession blocks with withDynTransaction ones

DROTH-2507 Problem when extracting obstacles

---

UI/src/assetTypeConfiguration.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

-Added arvo field mandatory for some signs

DROTH-2513 Minimum speed limit value must be mandatory

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

-Fix a bug when extracting start/end dates for geojson

DROTH-2526 Change api for lanes returning error

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/AssetReportCsvExporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataExporter/AssetReportCsvExporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/csvexporter/AssetReporterDAO.scala

-Add filter from assets on municipality road links
-Fixed missing lanes and manoeuvres on report
-Refactor code

DROTH-2521 Report lists changes in roads which it should not

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala

Fix the generator of Linear prohibitions through by traffic sign

Droth 2527 prohibitions generated by traffic signs created without time validations

---

UI/src/utils/backend-utils.js
UI/src/view/csvReportsWorkList.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataexport/ExportDataApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/AssetReportCsvExporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataExporter.scala

- Fix the button to show the log info doesn't work in case of error

DROTH-2529 (U.S:2454) Extraction board the button to show log info doesnt work in case of error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

- Value field modified at CSV TrafficSIgn Import to applies validations according to of the traffic sign type.

DROTH-2534 Traffic sign csv-import

---

UI/src/view/point_asset/trafficSignForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala

- Added green color option in the Additional Panels

DROTH-2563 Green color option for additional plates

---

UI/src/view/point_asset/pointAssetForm.js

- Upgrade property default value calculation on singleChoiceHandler field.

DROTH-2422 Wrong values on traffic signs

---

ci/pipeline/run_tests
config/deploy/training.rb

- Delete training.rb file.
- Disable robot framework tests.

DROTH-2567 Delete old code/folders mentioned at Transfer meetings

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

- Fix the enconding for traffic sign csv import.

DROTH-2566 Possible bug in the traffic sign csv-import

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

 DROTH-2469 add ACCESSS_RIGHT_ID to private road

---

UI/src/view/dynamicAssetForm.js

Changed label tag text from Kelirikkokausi to field.label

---

UI/src/view/point_asset/pointAssetForm.js

if undefine return empty string

 DROTH-2579 if undefine return empty string

---

UI/src/view/point_asset/trafficSignForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala

Reverts finnishtransportagency/digiroad2#1585
if we need this change in future, we need to run revert of revert pull request.

Revert "DROTH-2563 Green color option for additional plates"

---

UI/src/view/point_asset/trafficSignForm.js

https://extranet.vayla.fi/jira/browse/DROTH-2599

DROTH-2599 Changed panelinfo and main sign text placements.

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala

https://extranet.vayla.fi/jira/browse/DROTH-2629

Droth 2629 check duplicates with maintext

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/feedback/FeedbackOperations.scala

https://extranet.vayla.fi/jira/browse/DROTH-2581

DROTH-2581 trim s away from end of layer name

---

UI/src/view/point_asset/trafficSignLabel.js

Deleted visualization of info value of traffic signs.

Deleted visualization of info value of traffic sign

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

Reverts finnishtransportagency/digiroad2#1611

Revert "DROTH-2598 Changed value on mainSignText field to same as additionalI…"

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

DROTH-2651 Changed municipaltyToDelete to Honkajoki and municipalityToMerge to Kankaanpää

DROTH-2651 Changed municipaltyToDelete to 99 and municipalityToMerge to 214

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TierekisteriBusStopStrategy.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

https://extranet.vayla.fi/jira/browse/DROTH-2642

Droth 2642 add vallu message for expired

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
project/build.scala
src/main/resources/application.conf

Exceptions in async processing code were lost. Added configuration to redirect the error messages to application log file for further analysis.
Also Improved the logging of missing roadlink while hanlding side code change.

Fix Akka Logging

---

UI/src/assetTypeConfiguration.js

DROTH-2686 change default value

---

UI/src/view/point_asset/trafficSignLabel.js

DROTH-2684 change visualization

---

UI/src/view/initialPopupView.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/resources/db/migration/V236__enumerated_value_namefi_column.sql

https://extranet.vayla.fi/jira/browse/DROTH-2627
Testit ok http://livibuild04.vally.local/jenkins/job/oth/job/Run-Tests/652/

DROTH 2627 Interface typos

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala

https://extranet.vayla.fi/jira/browse/DROTH-2598

Droth 2598 change import on traffic signs 2

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala

https://extranet.vayla.fi/jira/browse/DROTH-2694

DROTH-2694 added headOption and IllegalStateException adjustedSideCode

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala

https://extranet.vayla.fi/jira/browse/DROTH-2704

DROTH-2704 headOption for oldAsset and throw illegal exception

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala

https://extranet.vayla.fi/jira/browse/DROTH-2708

Droth 2708 prohibition service empty list error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala

https://extranet.vayla.fi/jira/browse/DROTH-2691

Droth 2691 linear asset operations error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OraclePedestrianCrossingDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinkIdImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDaoSpec.scala

lisätään alias loppuun from(select * from) syntaksiin ja korjataan limit käyttöä

Droth 2706 check limit in where and from select syntax

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinkIdImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadLinkDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleMassTransitStopDaoSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala

ja poistetaan käyttämättömiä viite koodin jäänteitä

DROTH-2706 fix error in sql code and remove todo comment

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala

https://extranet.vayla.fi/jira/browse/DROTH-2706
Korvattu kaikki MONTHS_BETWEEN-funktiot extract(month from age()):llä.

DROTH-2706 months_between to postgresql equivalent

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala

when deleting masstransitstop it ID cannot be saved to vallulog table

 DROTH-2725 fix invalid insert

---

.gitignore
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISMassTransitStopDaoSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala

Droth 2706 renaming some missing oracle

---

aws/cloud-formation/cicd/cicd-github.yaml
aws/cloud-formation/support-repository.yml

nää unohtui nyt asettaa, mut laitetaan nyt

 DROTH-2768 add scan on push

---

aws/cloud-formation/fargateService/alb_ecs.yaml
aws/task-definition/dev/task-definition.json

katotaan jos tää korjais loadbalancer ongelman

DROTH-2782 port configuration mistakes

---

src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

Add support for digiroad-dev context path used in aws dev env.

DROTH-2785 Fix proxy regexp

---

gruntfile.js

https://extranet.vayla.fi/jira/browse/DROTH-2757

DROTH-2757 change .properties references to Digiroad2Properties.

---

aws/buildspec.yaml

Reverts finnishtransportagency/digiroad2#1697

Revert " DROTH-2749 deactivate test"

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/ConversionDatabase.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/CsvGenerator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadLinkDataImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitValidatorSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/UserNotificationServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearSevenRestrictionsServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/NumericValueLinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/HeightLimitServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WeightLimitServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WidthLimitServiceSpec.scala

https://extranet.vayla.fi/jira/browse/DROTH-2756

DROTH-2756 Set data source to PostGISDatabase.ds and deleted unused imports

---

aws/cloud-formation/batchSystem/batchJobDefinition.json
aws/cloud-formation/batchSystem/batchSystem.yaml
aws/cloud-formation/batchSystem/parameter.json
aws/fargate/startup.sh
aws_register_jobDefinition.ps1
aws_update_batchSystem.ps1
submit_job.ps1

Tää menee nyt aika geneeris periaatteella. Käytetään yhtä job definition ja määritetään vaan tarvittavat env kun ajetaan submit-job. console noiden laittelu on hieman kömpelöä.

Droth 2795 cloudformation

---

aws_submit_job.ps1

kommentti jos komento ei toimi, päivitä aws versio

 DROTH-2795 rename and add comment

---

aws/cloud-formation/fargateService/alb_ecs.yaml

https://extranet.vayla.fi/jira/browse/DROTH-2810
Lisätty container insights cloudFormationiin.

DROTH-2810_add_cluster_settings_to_cloudFormation

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala

revert tääkin, vähän huolimaton ollut

 DROTH-2796 change spect

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala

Reverts finnishtransportagency/digiroad2#1735  auki ettei uohdu

Revert " DROTH-2796 change spect"

---

ci/docker/Dockerfile.sbt

katotaan hajoaako jotakin muutakin kun on vähän aikaa kun jenkins hommia ajeltu viimeksi

update sbt to 0.13.15

---

README.md
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala

https://extranet.vayla.fi/jira/browse/DROTH-2813
Testataan webhookkia tällä muutoksella.

Droth 2813 double build in aws

---

README.md

DROTH-2813 empty row for webhook test

---

README.md

https://extranet.vayla.fi/jira/browse/DROTH-2813
Poistetaan webhookkien testausta varten lisätyt tyhjät rivit.

DROTH-2813 delete empty rows created for testing

---

aws/cloud-formation/cicd/cicd-github.yaml

joo, nyt kyl unohtui että nää pitää olla määritetty fake arvoilla jotta homma menisi läpi

 DROTH-2740 add new env

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/CacheClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala

 DROTH-2740 add timer to measure caching

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala

noissa batch nyt käytetään tota println, ei taida näkyä muuten siellä

Droth 2903 add try catch hotfix

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

cherry pick uudelleen nimeämis commit DROTH-2660_new_lane_creation branch, nyt kun on vähän enemmän kehittäjiä voi tullla ongelmia kun uudelleen nimeäminen on osa isompaa ominaisuutta

Refactor naming2

---

UI/src/assetTypeConfiguration.js
UI/src/model/selectedLaneModelling.js
UI/src/view/dynamicAssetForm.js
UI/src/view/linear_asset/laneModellingForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Kaistatyökalun alkupvm (start_date) kenttä pakolliseksi

Droth 2889 start date changes

---

UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingLabel.js
UI/src/view/linear_asset/laneModellingLayer.js
UI/src/view/linear_asset/laneModellingStyle.js

Droth 2941 fix lane styling

---

project/build.properties

 DROTH-2760 fix build and change sbt to same as in viite

---

aws/cloud-formation/batchSystem/batchJobDefinition.json
aws/cloud-formation/batchSystem/batchSystem.yaml

Lisätty log-groupille nimi ja oikeus luoda log-grouppeja
Log streamia nimeä ei kannata muutta

Droth 2654 aws batch logging

---

aws/cloud-formation/batchSystem/batchSystem.yaml
aws/cloud-formation/batchSystem/parameter.json

Lisätty batchin cloudformatioon kohta joka luo sähköposti muistutuksen.

Droth 2911 notification for failed batch jobs

---

UI/src/utils/laneUtils.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Kaistan piirtyy nyt keskelle kun sideCode on 2 tai 3 yksisuuntaisella tiellä. viewOnlyLanelta löytyy nyt trafficDirection attribuutti, joka tarvitaan tähän toteutukseen.

DROTH-2992 Lane offset fixed, viewOnlyLane has trafficDirection attribute now.

---

aws/cloud-formation/digiroad2-db-cloudformation.yaml

postgre versio 13.2 -> 13.3, CloudFormation designerin metadata poistettu.

DROTH-3033 Postgre verison 13.3 removed CloudFormation metadata

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Linkillä olevien kaistojen lkm selvitykseen haettu kannasta jokaisella linkillä olevat kaistat, sama toiminnallisuus voidaan saavuttaa käyttämällä jo kerran haettuja kaistoja.

Droth 3034 viewing lanes slow

---

conf/staging/digiroad2.properties

Reverts finnishtransportagency/digiroad2#1830
ei kyl ollut mitään apua

Revert " DROTH-3036 test adding vvh as non proxy host"

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

LaneService testit oli jäänyt muuttamatta, testit korjattu nyt toimimaan.

DROTH-3050 Fixed tests

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Siirretty kaksinumeroisen kaistakoodin laskenta laneService, luotu sille unit test

Droth 3050 change api changes for velho integration

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala

Koodi lisäkaistan lisäämiseen tieosoitteen avulla erotettu csv importin koodista. Lisättävän kaistan sidecoden päättely tehdään jatkossa lanePartitionerin avulla hyödyntäen pääkaistojen tietoja.

Droth 3007 modify adding lanes by road address

---

UI/src/model/selectedLaneModelling.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Lisäkaistojen lisääminen usealle valitulle kaistalle korjattu toimimaan yksinumeroisella kaistakoodilla. Luotaville kaistoille otetaan sideCodet valitun pääkaistajoukon mukaan. Korjattu lisäkaistoihin liittyvä bugi lanePartitionerissa samalla.

Droth 3054 multiple lane add fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Jäi testit ajamatta nopean korjauksen jälkeen tänä aamuna ja testi failasi buildatessa. Korjattu ongelma.

DROTH-3051 quick fix

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/LaneApiSpec.scala
src/main/scala/ScalatraBootstrap.scala

Mockaukset luotu testejä varten, lisätty parempaa virhetilanteista suoriutumista LaneApiin.

DROTH-3076 Fixed API error handling and tests

---

conf/env.properties
gruntfile.js

päivitetään VKM oikeaan ja pientä organisointia

Update env properties organizing

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkTempDAO.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ResolveFrozenRoadLinksSpec.scala

Postgrest pudottaa milli sekunti nollat. Tuodaan ne takaisin.

 DROTH-3055 fix resolveFrozen roadlink

---

UI/src/utils/laneUtils.js

Yksisuuntaisten teiden kaistojen offset korjattu. Lisäkaistat piirtyvät nyt halutuille puolille.

DROTH-3090 fixed lane draw offset on one way tracks

---

UI/swagger/index.html
gruntfile.js

pieni jääne kun viellä oli digiroad alussa

 DROTH-3019 swagger pointing to old context digiroad url

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala

Testit oli mennyt rikki, en huomannut heti lokaalisti testatessa, buildi onnistuu nyt

DROTH-3098 better error handling, fixed tests

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala

Lisätty getOrElse, hoitaa saman filtteröinnin, ilman, että heittää NoSuchElementException

Droth 3106 change lanes batch fix

---

UI/src/view/linear_asset/laneModellingLayer.js

Korvattu nuolifunktiot "tavallisilla" ja korjattu puolipisteitä. Katsottu, ettei ajonaikana tai grunt testistä tule virheilmoituksia gruntin konsoliin.

DROTH-3086 replace arrow functions to fix build error

---

aws/cloud-formation/batchSystem/aws_update_batchSystem.ps1
aws/cloud-formation/batchSystem/batchSystem.yaml

batch fail viestissä on nyt jotakin informaatio arvoa myös ei kehittäjille.

improve batch failure message

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Lisätty Loggereita kertomaan paljon menee kaistojen ja tielinkkien esittämiseen tarvittaviin operaatioihin aikaa

Droth 3092 roadlink slowness fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AssetValidator.scala

Lisätty poikkeuksen käsittely ja logitus kohtaan, joka kaatoi batchit. Lisäksi vaihdettu printit loggereihin ja selkeytetty viestejä.

DROTH-3130 add exception handling and logging to assetvalidator

---

UI/test/run-integration-tests.js

Fiksaus rikkoontuneisiin Mocha integraatiotesteihin

DROTH-3154 Fixed mocha integration test dependency

---

aws/cloud-formation/cicd/cicd-github.yaml

Lisätty ECR:n lifecyclepolicyt cloudformation templateen.

DROTH-3079 Added ECR lifecycle policies

---

aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/batchSystem.yaml

Batch System CloudFormation-templateen lisätty tuotanto-batch ympäristö. Ei voitu testata päivittää vielä Väylän pääsynhallinnasta johtuen.

Droth 3110 prod batch system

---

aws/cloud-formation/batchSystem/batch-parameter.json
aws/cloud-formation/batchSystem/batchSystem.yaml

Lisätty Prod, QA ja DEV batch ajastus eventit batchSystem cloudFormationiin

DROTH-3161 Added Prod, QA and DEV batch events to CloudFormation

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala

cherry pick vähän logging koodia ja yhtenäistetty loggaus aikaa vvh puolella

Droth 3092 add logging

---

UI/swagger/index.html
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala
gruntfile.js
src/main/scala/ScalatraBootstrap.scala

lisätty digiroad sana ja cors headers, korjataan lisää jos ei toimi

Droth 3019 swagger to apivayla

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/Sequences.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/MassQuery.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLanePopulationProcess.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Optimoitu pääkaistojen populointia vaihtamalla yksittäisiä insert kyselyjä batchiin.

Droth 3169 main lane population optimization

---

aws/cloud-formation/taskdefinition/prod-create-taskdefinition.yaml

fix wrong url mistakes

---

UI/src/view/link_property/linkPropertyForm.js

DROTH-2805 fix typo

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala

pari sql virhettä jäänyt oracle -> postgrest migration jälkeen

Droth 3177 fix sql error

---

aws/buildspec.yaml
aws/cloud-formation/fargateService/prod/README.md
aws/cloud-formation/s3/DEV-api-s3-parameter.json
aws/cloud-formation/s3/PROD-api-s3-parameter.json
aws/cloud-formation/s3/QA-api-s3-parameter.json
aws/cloud-formation/s3/digiroad2-api-s3.yaml
aws/cloud-formation/taskdefinition/dev-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/prod-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/qa-create-taskdefinition.yaml
conf/env.properties
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/LaneApiSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/ServiceRoadApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/Digiroad2Properties.scala
project/build.scala

Vältetään API Gatewayn aikaraja sekä maksimi koko rajoitukset tallentamalla rajoituksia ylittävät vastaukset s3:seen, joihin kyselijä ohjataan presigned urlilla.

DROTH-3167 avoid API GW limitations

---

aws/cloud-formation/cicd/prod/PROD-cicd.yaml

Muutettu login siten, että loggaa myös tuotantoon ja tagays siten, että tägää myös deviin puskettavan imagen

DROTH-3182 Update docker login and tag params

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala

Käytetään samaan resurssiin uudelleen ohjaamisessa koko relatiivista polkua.

DROTH 3167 API GW fixes

---

src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

laitetaan selain cache pois päältä index html

 DROTH-3199 disable browser cache

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala

Poistetaan virheen heitto jos tietolajille merkittyä linkkiä ei löydy linkeistä tai historioiduista linkeistä (esim. täydentävällä geometrialla sijaitsevat). Täydentävällä geometrialla sijaitsevia tietolajeja ei haluta palauttaa rajapinnoille (pl. joukkoliikenteen pysäkit). Skipataan ja lokitetaan kyseiset muutokset.

DROTH-3190 Fix change api asset on complementary link

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json

Unohtui nostaa ympäristömuuttujassakin CPU määrää, korjattu nyt.

Increase CPU count to 4

---

aws/cloud-formation/batchSystem/batchSystem.yaml

Päivittäisten eräajojen ajastukset korjattu vain arkipäiville.

DROTH-3207 Daily Batch timings now only on work days

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChangesSpec.scala

Kaistojen samuutus korjattu toimivaksi eri muutostyypeille.  Unit testit jokaiselle eri muutostapaukselle.

Droth 3170 change lanes fixed

---

aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Caching disabloitu QA ja prod job definitoneissa

DROTH-3209 Disabled caching QA and Prod Job definition

---

aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Käytettävä image päivitetty QA job definition

DROTH-3211 update QA job definition to use correct image

---

UI/src/controller/laneModellingCollection.js
UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingForm.js
UI/src/view/linear_asset/laneModellingLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Uusi branch masterista, johon cherry-pickattu oleelliset commitit pull requestista #1955.

Droth 3109 lane split problems branched from master

---

aws/cloud-formation/cicd/qa/cicd-qa.yaml

 DROTH-3228 add missing webhook

---

aws/cloud-formation/batchSystem/batchLambda/cicd/prod-deployment-bucket-parameter.json
aws/cloud-formation/batchSystem/batchLambda/cicd/prodBatchLambdaDeploymentBucket.yaml
aws/cloud-formation/fargateService/prod/README.md

Korjattu ohjeen --parameter, vaihdettu parametrin nimi DevAccountID -> AccountID

Droth 3214 run prod batches on prod account

---

aws/cloud-formation/batchSystem/batchSystem.yaml
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChangesSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChangesSpec.scala

Tehty uusi branch NextRelease, mergetty kaistasamuutuksen kolme branchia:
DROTH-3170_change_lanes_fixed
DROTH-3170_build_fix
DROTH-3175_fix_saving_changes

Droth 3170 change lanes to next release

---

aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json

Vaihdettu prod job definitioniin tuotantotilin arn:t

DROTH-3214 Fixed JobDefinition

---

aws/cloud-formation/batchSystem/batchSystem.yaml

Jos korjataan merge conflict nyt tässä ja sitten mergetään development <- master

Resolved merge conflict batchSystem.yaml

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Korjattu yksi unit-test, jotta build ei kaadu.

DROTH-3109 fix one unit-test by adding sidecode

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala

Lisätty puuttunut talviteiden pois suodatus linkeistä sekä päivitetty testit takaisin aiempaan muotoon.

Droth 3276 filter out winter roads

---

aws/cloud-formation/batchSystem/batchLambda/cicd/prod-batchLambdaPipeline.yaml
aws/cloud-formation/batchSystem/batchLambda/cicd/prodBatchLambdaDeploymentBucket.yaml

Lisätty tuotanto eräajo lambdan pipelineen tarvittavia oikeuksia.

Droth 3268 add missing permissions to prod batch pipeline

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala

Lisätty rajapintojen lokitusta.

DROTH-3270 Add logging to APIs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala

Lisäkaistojen CSV-tuonnissa tullut eri tikettien muutosten myötä nested transactioneita, korjattu pois

DROTH-3104 Fix additional lane csv import nested transactions

---

digiroad2-oracle/src/main/resources/db/migration/V1_4__change_to_generic_geometry.sql

column ilman geometry tyyppiä, mahdollistaa pisteiden ja viivojen tallentamisen

 DROTH-3292 change to generic geometry

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala

näitä override oli vähän enemmän kuin muistin tai tajusin tarkistaa

 DROTH-3277 add missing false

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala

Lisätty täydentäville linkeille oma dao, josta jatkossa kysellään täydentävät linkit VVH:n sijaan.

Droth 3296 get complementary links from own db

---

UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Lisätty uusi toiminnallisuus lisäkaitoille muuttaa ne pääkaistaksi. Muutokset hyödyntävät muutossanomissa newLaneCode / newLaneType kenttiä.

Droth 3096 promote to mainlane

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Tyyppimuunnos virhe esti tielinkin ominaisuustietojen muokkauksen.

DROTH-3308 Fixed cast error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

DROTH-3313 Fixed construction type filtering in roadLinks

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/VVHClientSpec.scala

Toimii devissä. Sovittu Antin kanssa, että voidaan mergetä suoraan ilman approvea, koska muita ei paikalla ja katselmoitu jo devin pr:ssä.

Droth 3311 remove fetch changes from vvh

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Poistettu yksi kantahaku. Huomattu bugi, jossa kaikille linkeille frontilta ei saada SideCode kun tallenetaan muutosta kaistoille. Tätä bugia en pystynyt enää toistamaan mitenkään. Pitää katsoa jos toistuu tulevaisuudessa vielä

DROTH-3096 refactored code, got rid of redundant db query

---

UI/src/view/linear_asset/careClassStyle.js
UI/src/view/linear_asset/carryingCapacityStyle.js
UI/src/view/linear_asset/cyclingAndWalkingStyle.js
UI/src/view/linear_asset/laneModellingStyle.js
UI/src/view/linear_asset/parkingProhibitionStyle.js
UI/src/view/linear_asset/pavedRoadStyle.js
UI/src/view/linear_asset/piecewiseLinearAssetStyle.js
UI/src/view/linear_asset/roadDamagedByThawStyle.js
UI/src/view/linear_asset/roadWorkStyle.js
UI/src/view/linear_asset/winterSpeedLimitStyle.js
UI/src/view/point_asset/pointAssetLayerStyles.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Vaikuttaa toimivan devissä ok.

Droth 3197 narrower lines for cycling and walking routes

---

.gitignore
README.md
aws/local-dev/postgis/docker-compose.yaml
aws/local-dev/postgis/start-postgis.sh
importRoadlink.ps1

Skripti hakea tielinkit kannasta. SSH yhteys bastion koneeseen ja portien ohjaus pitää tehdä ennen skriptin ajamista. 
En nyt alkanut tekemään muutoksia noihin meidän batch koodeihin. Tarpeen tullessa voi joko ladata koko tieverkko ja ladata se kantaan tai muokata municipalitie haku kohtaa batch koodissa käyttämään vaan pientä määrää kuntia.

Droth 3294 seperate volume for development

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Lisätty tyyppimuunnos niihin arvoihin, jotka on raportoitu vääräntyyppiseksi ja joiden on havaittu tulevan apista vääräntyyppisenä. Lisäksi testit näille tietolajeille.

DROTH-3337 int conversions for Kalpa api values + tests

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Määritellään TestTransactions luokan sisällä, jotta build ei kaadu.

DROTH-3337 explicit definition of test transactions to fix build

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Dev-testauksen ja keskustelun perusteella muutokset:
* vaihdettu default-arvot Nonesta tyhjään merkkijonoon
* lisätty pari tyyppimuunnosta
* paranneltu testejä

Droth 3337 fixes after dev testing

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Testattu dev-apista, että toimii ok.

Droth 3337 fix incorrect return value formats in kalpa api

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLaneStartDateImporter.scala

Käytätetään Default credential provider chain

DROTH-3104 Use default credential provider chain

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

lisätty unohtunut withDbConnection

 DROTH-3295 add withDbConnection

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLaneStartDateImporter.scala

Käsitellään rivit rinnakkain 10 000 joukoissa, lisätty lokitusta ja virheistä selviämistä.

DROTH-3104 Added parallel processing of rows, improved logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLanePopulationProcess.scala

Ei luoda pääkaistoja ajopoluille.

Droth 3312 exclude tractor road from mainlane creation

---

aws/cloud-formation/digiroad2-db-cloudformation.yaml

EngineVersion piti myös päivittää

 DROTH-3344 update engine version

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLaneStartDateImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/Parallel.scala

Käytetään Util.Parallel, kaksinumeroinen kaistakoodi selvitetään käyttämällä tieosoitteen sideCodea. Muutettu lokitusta

Droth 3104 mainlane startdates merge fix

---

UI/src/view/linear_asset/prohibitionFormElements.js

Toiminta testattu testien osalta.

Droth 3340 vehicle prohibition UI naming improvements

---

UI/src/assetTypeConfiguration.js
UI/src/view/dynamicAssetForm.js
UI/src/view/linear_asset/laneModellingForm.js

Lisätty kaistanmallinnustyökalun UI elementteihin uusia luokkia ja select valintoihin data-value tieto elementtien identifiointia helpottamaan testeissä.

DROTH-3348 Add identifiers to UI code to help testing

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala

Siirretty taulujen truncate yhteen sql lauseeseen.

DROTH-3345 truncate in single statement

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLaneStartDateImporter.scala

Siirretty getObjectFromS3 AwsServiceen.

DROTH-3104 Moved getObjectFromS3 to AwsService

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAOSpec.scala

poistettu tarkk'ampuja ohitus koodi, korjattu by linkid kysely

Droth 3243 add support for hyphen in roadname

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

DROTH-3307

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

DROTH-3332

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

DROTH-3351 fix roadlinks without lanes api mapping

---

UI/src/view/linear_asset/laneModellingForm.js

 DROTH-3248 fix naming error

---

UI/src/view/linear_asset/laneModellingLayer.js

Droth 3289 disable cut tool for lane group

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala

Droth 3351 links missing lanes fix

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Testit oli jäänyt korjaamatta. Lisätty match, niin voidaan välttää .get käyttöä.

DROTH-3307 fixed unit tests and added handling to avoid None.get

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinkIdImporter.scala

Muutettu linkki id:t päivittävää batchia sallimaan null arvot dest_link_id:llä kääntymisrajoitus elementit sisältävässä taulussa. Linkki id:n mappaus uuteen id:seen onnistuu nyt vaikka dest_link_id olisi null.

DROTH-3371 Allow manoeuvre dest_link_id to be null

---

UI/src/view/point_asset/servicePointForm.js

Lisätty palvelupiste lomakkeen option kohtiin data-value attribuutti testaamista varten.

DROTH-3373 Improve service point form naming for testing

---

UI/src/model/selectedLaneModelling.js

Korjaus bugiin, jossa valittua lisäkaistaa ei voinut katkaista uudelleen, kun katkaistu useaan kertaan.

DROTH-3346 fix bug with cutting lanes

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala

Droth 3307 traffic sign alphanumeric old codes missing

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala

Korjattu csv import. Testattu dev ympäristössä.

DROTH-3385 CSV import fix

---

UI/src/application.js

Poistetaan kaistanmallinnustyökalun piilotus prod

DROTH-3395 Removed hiding lane modelling tool in prod-environment

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

DROTH-3403 LinkSource mapping fix

---

UI/src/utils/text-utils.js
UI/src/view/dynamicAssetForm.js
UI/src/view/linear_asset/prohibitionFormElements.js
UI/src/view/point_asset/servicePointForm.js
UI/test/integration-tests.html
UI/tmpl/index.html

Varmistettu devissä, että data-value attribuutit näkyvät oikein uuden tyyppisenä.

DROTH-3373 New method for resolving data-value attribute value

---

digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_6__municipality_asset_id_mapping_table.sql
digiroad2-oracle/src/main/resources/db/migration/V1_7__municipality_asset_id_mapping_table.sql

Luotu taulu ja testailtu lokaaliin kantaan, että constraintien pitäisi toimia tiketin kuvausten mukaan.

DROTH-3409 create mapping table for municipality asset id

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala

Lisätty jannen toimittamat kolme päivitettävää arvoa

DROTH-3307 Updated old law code values

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala

Lisätty rivin poisto mappaystaulusta bussipysäkkien poiston yhteyteen.

Droth 3409 mapping table for municipality asset

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLanePopulationProcess.scala

Ajettu populointi DEV ja tarkastettu levähdysalueet. Ajo loi oikealla sideCodella kaistat linkin tyypin ja liikennöinti suunnan mukaan. OK

DROTH-3389 Special handling for RestAreas

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminalBusStopStrategy.scala

Validoidaan että tarvittavat parametri on olemassa lähettää akka viesti. Ei nyt ollut sittenkään niin vakava mut onpa nyt korjattu.

Droth 2695 fix trying to fetch with empty array

---

UI/src/view/laneWorkList.js

sortBy kentät oli jäänyt väärin päin

DROTH-3097 fixed sorting

---

UI/src/view/initialPopupView.js

Kaistanmallinnustyökalu valittavissa oletus tietolajiksi käyttäjälle

DROTH-3413 Add lanemodelling tool to default options

---

UI/src/utils/backend-utils.js
UI/src/view/laneWorkList.js
UI/src/view/link_property/linkPropertyForm.js
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneWorkListService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneWorkListServiceSpec.scala

Droth 3097 lane work list

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/taskdefinition/dev-create-taskdefinition.yaml

change viite endpoint to dev

---

aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/cicd/qa/cicd-qa.yaml

Tehoja nostettu dev ja test codebuild

DROTH-3418 bigger compute type for dev and test codeBuild

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/viite/SearchViiteClient.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Lisätään linkkien id:llä tehtävään Viitteen tieosoitehakuun lainausmerkit linkki id:lle.
Viedään deviin viedyt muutokset myös feature branchiin.

DROTH-3280 Use quotation marks with road address fetch by link ids

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Droth 3419 fix speedlimit unknown limit generation

---

aws/fargate/startup.sh
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/viite/SearchViiteClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Korjaus batchin ajavan luokan polkuun. "Ylimääräisten committien" pitäisi olla jo devillä.

Droth 3251 fix path

---

UI/src/view/link_property/linkPropertyLayer.js

Muutokset ilman deviä feature branchiin. Vaikuttaa olevan devillä ok.

DROTH-3421 fix roadlink visualization bug to feature branch

---

aws/fargate/startup.sh
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala

Batchit saatu ajattua devillä, joten viedään korjaukset faeture-branchiin.

Droth 3251 fix bugs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala

Lisätty lainausmerkit linkId:hen. Korjasi ongelman ainakin lokaalisti.

Droth 3426 fix failing speed limit validator process

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

Korjattu vääriä tyyppejä ja vastauksen kenttien käsittelyä haettaessa KGV road_link_versions.

DROTH-3420 Fix errors in kgv road link history

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala

Devissa batch ajettu onnistuneesti.

DROTH-3426 fix failing speed limit validator process

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

Cherry pickattu commitit uuteen branchiin oikeasta feature branchista.

Droth 3420 history link fix from droth 3121

---

digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_15__add_qgis_roadlinkex_table.sql

Lisätty uusi taulu täydentäville tielinkeille.

DROTH-3438 New table for complementary road links

---

digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_15__add_qgis_roadlinkex_table.sql

Uusi taulu täydentäville linkeille. Tuodaan myös feature branchiin.

Droth 3438 add kgv roadlinkex table

---

UI/src/view/link_property/linkPropertyLayer.js

Korjataan merge conflictin ratkomisessa tullut väärä numeroarvo.

DROTH-3445 fix link type visualization on qa

---

digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_16__create_municipality_email_table.sql

Viedään qa:lle, jotta saadaan tehtyä versionumeroilta uudempia migraatioita.

Droth 3439 create municipality email table

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala

Devillä ok, joten viedään korjaus feature-branchiin.

DROTH-3455 add BidirectionalLaneCarriageWay back to link type values

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinkIdImporter.scala

Muutettu LinkIdImporteria päivittämään myös täydentävien linkkien id:t. Lrm sekä muiden "normaalien" taulujen päivitys yrittää ensin katsoa löytyykö vvh id _frozenlinks_vastintaulu_csv_ taulusta, jos ei niin katsotaan löytyykö se _qgis_roadlinkex_ taulusta, mikäli vvh id ei löydy kummastakaan, asetetaan linkki id:ksi null.
**Huom**. Kun viedään kgv muutokset tuotantoon, pitää ensin ajaa flyway migrate ja sen jälkeen tuoda täydentävät linkit gqis_roadlinkex tauluun. Vasta näiden vaiheiden jälkeen voidaan ajaa LinkIdImporter. Toinen vaihtoehto on käydä luomassa taulu käsin tuotantoon ja viemässä täydentävät linkit sinne jo etukäteen.

DROTH-3457 LinkIdImporter to update complementary link ids too

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala

Qgis_roadlinkex tauluun siirtymä muutokset feature branchiin.

DROTH-3459 Get complementary links from qgis_roadlinkex table

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFillerSpec.scala

DROTH-3451 fixed unit tests

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/DamagedByThawFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala

Droth 3451 separate fix operations

---

UI/csv_import.html
UI/newuser.html
importRoadlink.ps1

Testattu toimivaksi devissä. Viedään muutokset QA:lle.

DROTH-2833 Fix scandic letters in UI

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Refaktoroitu LaneNumber enumeraatio yhteen object

DROTH-2954 Refactored LaneNumber

---

UI/src/less/core/variables.less
UI/src/less/site/action-panel.less
UI/src/view/link_property/linkPropertyForm.js
UI/src/view/link_property/linkPropertyLayerStyles.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/navigationpanel/pointAssetBox.js
UI/src/view/navigationpanel/roadLinkBox.js
UI/src/view/point_asset/pointAssetLayerStyles.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Droth 3196 draw links temporarily out of use

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala

Parannettu virhe viestiä kuvaavammaksi.

DROTH-3466 improve InvalidRoadNumberException message

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala

Droth 3466 lanes filter only car road

---

UI/src/view/navigationpanel/manoeuvreBox.js
UI/src/view/navigationpanel/speedLimitBox.js

DROTH-3481 Remove extra closings of divs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala

Otetaan Viite peräiset virhetilanteet kiinni ja lokitetaan ne, kun haetaan pysäkille tieosoitteita. Jos Viite yhteys epäonnistuu tai kysely palauttaa muun virheviestin, yritetään tieosoite hakea VKM:sta. 
Ennen pysäkin tietojen avaaminen kaatui mahdollisiin Viite virheisiin, jolloin muun muassa muokkaaminen oli mahdotonta.

DROTH-3460 Catch Viite errors when opening bus stop

---

UI/src/view/navigationpanel/massTransitStopBox.js

DROTH-3488 override inherited function to fix double rendering

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/resources/db/migration/V1_18__update_traffic_sign_F53_enumerated_value.sql

DROTH-2830 Update F53 traffic sign enumerated value

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala

Droth 3484 fix update speed limits

---

UI/src/view/point_asset/trafficSignForm.js
digiroad2-oracle/src/main/resources/db/migration/V1_19__increase_maximum_number_of_additional_panels.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISTrafficSignDao.scala

Dev ok. Testattu UI, csv import, Kalpa API ja Change API.

DROTH-2640 Allow five additional panels for traffic sign

---

UI/src/model/selectedLaneModelling.js
UI/src/utils/date-utils.js
UI/src/view/linear_asset/laneModellingForm.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneEndDateExpirer.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Kaista päätetään nyt eräajossa kun end_date pvm koittaa. Jos end_date asetetaan UI:lla menneisyyteen päätetään kaista heti tallennuksen yhteydessä.

Droth 3468 lane end date expire

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala

Poistettu turha 1000 ositus, parannettu logitusta, pitää viel katsoa vaatiiko DIGIAN api gateway homma jotakin omaa koodia.

Droth 3546 improve logging viite error

---

digiroad2-oracle/src/main/resources/db/migration/V1_22__add_expired_date_constraint.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAOSpec.scala

Lisätty expirointipäivän käyttö kyselyihin ja eriytetty käytössä olevien ja poistuneiden linkkien haku. Lisäksi yksinkertaiset testit.

DROTH-3541 separate queries for valid and expired links

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

DROTH-3553 fix ChangeApi type cast

---

aws/cloud-formation/fargateService/prod/README.md

Lisätty ohjeet lambdan koodin päivittämiseen, testattu toimivaksi tänään julkaisussa.

Update README.md with instructions on how to update lambda code

---

lambda/asset-history-processor/.dockerignore
lambda/asset-history-processor/.gitignore
lambda/asset-history-processor/Dockerfile
lambda/asset-history-processor/README.md
lambda/asset-history-processor/aws/cloudformation/ecr/dev.yaml
lambda/asset-history-processor/aws/cloudformation/lambda-resources.yaml
lambda/asset-history-processor/aws/dev/README.md
lambda/asset-history-processor/aws/dev/lambda-resources.json
lambda/asset-history-processor/aws/dev/tags.json
lambda/asset-history-processor/aws/sam/template.yaml
lambda/asset-history-processor/events/test.json
lambda/asset-history-processor/package.json
lambda/asset-history-processor/src/index.ts
lambda/asset-history-processor/test/index_test.js
lambda/asset-history-processor/tsconfig.json

Alustettu kohteiden muutosten käsittelijä/tallentaja-lambda ja sen CloudFormation templatet.
Viedään muutokset omaan development branchiin, joka tulee CI/CD putken toteuttamisen jälkeen käynnistämään lambdan dev-pipelinen.

DROTH-3528 Cloudformation templates and initialization of lambda function

---

lambda/road-link-change-handler/.gitignore
lambda/road-link-change-handler/README.md
lambda/road-link-change-handler/aws/cloudformation/lambda-resources.yaml
lambda/road-link-change-handler/aws/sam/template.yaml
lambda/road-link-change-handler/env.json
lambda/road-link-change-handler/src/index.ts

Mahdollistettu muutosten käsittelijä -lambdan lokaalitestaus sam avulla ja kirjattu ohjeet. Mahdollistettu lisäksi muutosten hakuaikavälin määrittäminen env muuttujilla (testaamista varten).

DROTH-3498 Enable local testing

---

UI/src/view/linear_asset/laneModellingForm.js

Korjattu lane_code weight formilla, kentät menivät väärään järjestykseen kun paineettiin "lisää tieosoitteella" napista, kun lisätty uusi kaista

DROTH-3461 fix new lane lane_code weight on form

---

lambda/asset-history-processor/README.md
lambda/asset-history-processor/aws/cloudformation/cicd/cicd-stack.yaml
lambda/asset-history-processor/aws/codebuild/dev.yml
lambda/asset-history-processor/aws/dev/README.md
lambda/asset-history-processor/aws/dev/cicd-parameter.json

Lambdan dev julkaisuputki. Samaa templatea pitäisi pystyä käyttämään QA pipelinen määrittämiseen, pitää vain tehdä oma buildspec kys. ympäristöön ja oma parametritiedosto (myös oma ecr repo täytynee lisätä).

DROTH-3536 asset history lambda dev cicd

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala

Lisätty virheen käsittely viitteestä ja logitusta  roadaddress haulle.

Droth 3564 log address fetching

---

lambda/road-link-change-handler/aws/cloudformation/cicd/cicd-stack.yaml
lambda/road-link-change-handler/aws/cloudformation/ecr/ecr.yaml
lambda/road-link-change-handler/aws/codebuild/buildspec.yml
lambda/road-link-change-handler/aws/dev/README.md
lambda/road-link-change-handler/aws/dev/cicd-parameter.json
lambda/road-link-change-handler/aws/dev/lambda-resources.json
lambda/road-link-change-handler/aws/qa/README.md
lambda/road-link-change-handler/aws/qa/cicd-parameter.json
lambda/road-link-change-handler/aws/qa/lambda-resources.json
lambda/road-link-change-handler/aws/qa/tags.json

Lisätty tielinkkien muutosten hakija -lambdalle dev ja qa julkaisuputket ja konfiguroitu qa ympäristö.

DROTH-3537 dev and qa cicd setup

---

UI/src/assetTypeConfiguration.js
UI/src/controller/laneModellingCollection.js
UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_22__add_expired_date_constraint.sql
digiroad2-oracle/src/main/resources/db/migration/V1_23__new_change_table.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAOSpec.scala

Julkaisun jälkeinen NextRelease -> master merge

Next release

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/LaneApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
src/main/scala/ScalatraBootstrap.scala

Droth 3547 lane api fixes to qa

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ClientUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala

Korjattu selainkäytön Viite yhteyden "WARNING: Invalid cookie header: ... Invalid 'expires' ..." virheet.
Lisätty lokitusta kertomaan jäljellä olevien yritysten määrä sekä epäonnistumiseen kulunut aika.

DROTH-3562 viite connection and logging improvements

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ClientUtils.scala

Droth 3564 exponental backoff

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala

Korjattu operaattori testauksessa löytynyt virhe parametrien validoinnissa.

DROTH-3547 Fix range parameter validation

---

digiroad2-oracle/src/main/resources/db/migration/V1_26__add_sidecode_to_change_table.sql

Lisätty change_table:en vielä mukaan puuttunut side_code kenttä.

DROTH-3532 Add side_code to change_table

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ClientUtils.scala

add more logging to find better way to reproduce error

Droth 3564 add more logging to find way to repeat

---

lambda/asset-history-processor/README.md
lambda/asset-history-processor/aws/cloudformation/lambda-resources.yaml
lambda/asset-history-processor/aws/dev/lambda-resources.json
lambda/asset-history-processor/aws/qa/lambda-resources.json
lambda/asset-history-processor/aws/sam/template.yaml
lambda/asset-history-processor/events/test.json
lambda/asset-history-processor/package.json
lambda/asset-history-processor/src/aws/ssm-service.ts
lambda/asset-history-processor/src/index.ts
lambda/asset-history-processor/src/processor/change-processor.ts

- Siirretty kohteiden historiakäsittelijä lambda vpc:n sisälle ja sallittu kantayhteys.
- Lisätty dead letter sqs queue.

DROTH-3532 Move lambda inside vpc

---

digiroad2-oracle/src/main/resources/db/migration/V1_24__edit_change_table.sql
digiroad2-oracle/src/main/resources/db/migration/V1_25__drop_columns_from_change_table.sql
digiroad2-oracle/src/main/resources/db/migration/V1_26__add_sidecode_to_change_table.sql

DROTH-3532 edit change table

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

- Lisätty kunta hakuun takaisin .toList, jonka puuttuminen aiheutti ongelman pysäkin rikastamisessa
- Siistitty koodia

DROTH-3521 remove point asset fixing operations from browsing

---

aws/buildspecs/development.yaml
aws/buildspecs/test.yaml

Korjaus hajonneisiin buildeihin

DROTH-3657 Fix dev and QA builds

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala

Korjattu ApiUtils toimimaan LinkedHashMap kanssa

DROTH-3578 add ApiUtils case for LinkedHashMap response type

---

UI/src/model/selectedLaneModelling.js

DROTH-3559 Remove redundant reorganizeLanes method call

---

UI/src/view/linear_asset/laneModellingLayer.js

DROTH-3549 Prevent lane cut if additional lane is promoted to main lane

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala

DROTH-3671 Fix VKM response value type cast

---

UI/src/controller/trafficSignsCollection.js
UI/src/view/point_asset/trafficSignForm.js

Lisätty toimitetut liikennemerkit käpy-linkeille sallittuihin liikennemerkkeihin.

DROTH-2683 Add more allowed traffic signs for walking-cycling-links

---

UI/src/controller/trafficSignsCollection.js
UI/src/view/point_asset/trafficSignForm.js

Droth 2683 walking cycling allowed traffic signs

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Muutostietobucketin nimi batch definitioneihin. En päivittänyt task definitionia, jos ei välttämättä tarvita siellä koskaan.

road link change bucket to batch definition

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Droth 3674 use history events with no event number

---

digiroad2-oracle/src/main/resources/db/migration/V1_28__edit_kgv_roadlink_constraints.sql

DROTH-3500 Modify kgv_roadlink constraints

---

digiroad2-oracle/src/main/resources/db/migration/V1_28__samuutus_record_table.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala

Taulu ja kyselyt hakea tietoa siitä.
Laitttu sql alustavasti Query kansioon. Jos tulee monimutkaisempia tai enemmän, heitetään omaan dao luokkaan ja service taakse.

Droth 3676 samuutus table

---

UI/src/controller/roadCollection.js
UI/src/enumerations.js

Droth 3680 pedestrian zone traffic sign fix

---

UI/src/controller/roadCollection.js

DROTH-3680 Fix mistake in link type boolean check

---

UI/src/assetTypeConfiguration.js
UI/src/view/point_asset/trafficSignForm.js

DROTH-3681 Fix Traffic sign form pedestrian cycling link default sign

---

UI/src/assetTypeConfiguration.js

DROTH-3686 Fix traffic sign save condition regex for number field

---

UI/src/assetTypeConfiguration.js

Lisätty haluttu validointi C47-merkin arvo-kentälle.

DROTH-3686 Add validation for C47 value field

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeCollector.scala

Malli miten alettaisiin pitämään kirjaa muutoksista. Ajattelin alussa alkamaan koodaamaan api kohteiden lisäämiselle mut jätän sen katsomisen sitten kun aletaan tekemään itse samuutus koodia. Tää kannattaa varmaan napata sitten kun aletaan tekemään samuutusta pohjana.

Droth 3527 samuutus change collector

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Testattu devissä kuntakäyttäjän tunnuksilla, että toimii. Build ongelma taisi myös olla satunnainen, koska toisella yrityksellä meni normaalisti läpi.

DROTH-3691 speedlimit bug fix

---

UI/manual/index.md

Manuaalista cherry pickattu haluttu muutos next releaseen.

DROTH-3719 update manual

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporterSpec.scala

DROTH-3697 fix failing test

---

lambda/road-link-change-handler/test/service/s3-service_test.js
lambda/road-link-change-handler/test/utils/s3-object-utils_test.js

Korjattu kirjaston versiopäivityksen jälkeen hajonneet testit

DROTH-3700 fix broken tests

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdaterSpec.scala

Muokattu käyttämättömästä funktiosta koodi, joka muodostaa samuutuksessa objectin raporttia varten + testejä.

DROTH-3698 reporting for bus stops

---

lambda/road-link-change-handler/src/client/vkm-client.ts
lambda/road-link-change-handler/src/index.ts
lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

Muutokset muuttuneen Tiekamun perusteella. Mm. muokattu tiekamu tulosten mappausta sekä poistettu vkm muunna kyselyt, joille ei ole enää tarvetta. Lisäksi yksinkertaistettu koodia muutamasta kohtaa.
Huom. Tiekamu muutokset eivät vielä ole dev, qa tai prod ympäristöissä, joten uudet muutokset (Tiekamu kysely) eivät vielä toimi.

DROTH-3499 Updates due to Tiekamu changes

---

lambda/road-link-change-handler/aws/cloudformation/cicd/prod-cicd-stack.yaml
lambda/road-link-change-handler/aws/cloudformation/ecr/prod-ecr.yaml
lambda/road-link-change-handler/aws/prod/README.md
lambda/road-link-change-handler/aws/prod/cicd-parameter.json
lambda/road-link-change-handler/aws/prod/ecr-parameter.json
lambda/road-link-change-handler/aws/prod/lambda-resources.json
lambda/road-link-change-handler/aws/prod/tags.json
lambda/road-link-change-handler/aws/qa/README.md

Lisätty tuotanto pipeline lambdalle

DROTH-3737 Add production pipeline and instructions

---

lambda/road-link-change-handler/aws/cloudformation/cicd/prod-cicd-stack.yaml

Korjattu tuotanto pipelineä käyttämään build stagessa oikeaa imagea.

DROTH-3737 Fix CodeBuild to use right image

---

aws/cloud-formation/batchSystem/batchSystem.yaml
aws/cloud-formation/batchSystem/dev-batch-system-parameter.json
aws/cloud-formation/batchSystem/prod-batch-system-parameter.json
aws/cloud-formation/batchSystem/qa-batch-system-parameter.json

Lisätty luvitus, jotta muutossetin lataaminen s3:een voi käynnistää batch lambdan. Vaatii vielä muutoksia itse lambdan koodiin.

DROTH-3743 Add samuutus event handling to batch lambda

---

aws/cloud-formation/fargateService/alb_ecs.yaml
aws/cloud-formation/fargateService/dev/DEV-alb-ecs-parameter2.json
aws/cloud-formation/fargateService/update-fargate.ps1

joo nyt äärimmäisen tylsästi nimetty.

Droth 3685 add support for paraller env

---

lambda/road-link-change-handler/src/client/kgv-client.ts
lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

Lisätty päällystetieto mukaan muutossetin linkin tietoihin.
Päivitetään erillisessä PR testimuutossetti.

DROTH-3750 Add surfaceType to change set

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala
digiroad2-oracle/src/test/resources/smallChangeSet.json
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

Lisätty testi muutossetin linkeille päällystetieto.

DROTH-3750 Add surfaceType info to test change set links

---

UI/manual/index.md

Tuotantojulkaisun jälkeinen NextRelease -> master

NextRelease

---

lambda/road-link-change-handler/aws/cloudformation/lambda-resources.yaml
lambda/road-link-change-handler/src/index.ts
lambda/road-link-change-handler/src/service/change-set.ts

Lisätty yhdistely tieosoitteiden mukaan pilkotuille täysin uusille linkeille sekä korjattu lambdan käynnistävän eventin ajastus.

DROTH-3777 tiekamu changes

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/OnOffLinearAssetService.scala

korjattu yksi testi, kaistoissa joku ongelma mut Antti hoitaa sen

 DROTH-3696 fix test

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

käsitellään osittainen poisto jakaantumisena.

Droth 3783 handle remove with replace

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala

Droth 3703 lanes in range api fix

---

UI/manual/index.md

Sovittiin, että operaattorin manuaalimuutokset tehdään kehitystiimin julkaisuprosessin mukaisesti, eli pull requestilla muutokset development haaraan. Tässä ensimmäinen, jos jotain tehtävä erilailla otamme palautteen vastaan.

manual modification

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

suodatatetaan osittaiset add pois

 DROTH-3786 filter partial add away

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

unohtui käsitellä tämä skenaario, paremmin sanottuna ei tullu mieleen.

 DROTH-3786 fix continuity errors

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/DynamicLinearAssetUpdaterSpec.scala

Testattu eri samuutustapauksia käpy-tietolajilla. Testien perusteella näyttäisi siltä, että käpy-väylille ei tarvittaisi erillistä samuutuslogiikkaa.

DROTH-3523 test samuutus for cycling and walking

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

development samuutus koodiin, viimeisimmät development muutokset jo tuotannossa.

Droth 3493 merge development

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

 DROTH-3747 remove unneeded endpoits

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluSender.scala

tän kyl pitäisi taata että yhteyksiä pitäisi olla riittävästi ja samalla siirrety vallut viesteissä client luonti per kutsu.

Droth 3562 viite problem

---

aws/cloud-formation/batchSystem/batchSystem.yaml

lisätään oikeus laittaa raportti s3 bucket

 DROTH-3784 add right to upload samuutus report

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

vähän parannettu testien nimiä

 DROTH-3787 remove println and improve test naming

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

Droth 3745 remove traffic direction condition from trams

---

UI/manual/index.md

Korjattu virheellinen tieto manuaalissa.

useampi liittymänumero korjaus manuaaliin

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

Korjattu virheenkäsittelyä.
Ei tehdä omaa formatisointia vaan annetaan logger tehdä se. Mahdollistaa tulevaisuudessa sen räätälöinin keskitestysti.
Ei nyt pakollinen muutos mutta korjasin vähän pagination systeemiä ja lisäsin logitusta.

Droth 3799 fixt future v2

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/viite/ViiteClient.scala

kokeillaan dev millaisia nopeuksia tulee.
Tästä tulee jotakin 100 - 300ms lisää aikaa mutta pitäisi taata vakaamman yhteyden.
revert tää jos tulee liian hitaasti.

 DROTH-3562 create client per request

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/viite/ViiteClient.scala

Reverts finnishtransportagency/digiroad2#2577
ei tehdä tätä muutosta.

Revert " DROTH-3562 create client per request"

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Reverts finnishtransportagency/digiroad2#2578
ei tehdä tätä muutosta.

Revert " DROTH-3562 fix unit test"

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala

 DROTH-3562 let us not wait 15min but only one minute before failling

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

Tuodaan korotettu -tieto pysäkeille integrationApiin.

DROTH-3785 add raised attribute for mass transit stops in IntegrationApi

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
UI/src/view/point_asset/pointsCursorTool.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

Vaikuttaisi toimivan OK devillä

Droth 3744 enable tram stops on pedestrian links

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessage.scala
digiroad2-api-common/src/test/resources/StopChange.xsd
digiroad2-api-common/src/test/resources/exampleValluMessage.xml
digiroad2-api-common/src/test/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessageSpec.scala

jotta pysyy tasoissa, testaus QA

Droth 3557 add new vallu endpoint

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
UI/src/view/point_asset/pointsCursorTool.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

Reverts finnishtransportagency/digiroad2#2592
Pitää sitten tehdä revert revert päälle sitten myöhemmin.

Revert "Droth 3744 enable tram stops on pedestrian links"

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
UI/src/view/point_asset/pointsCursorTool.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

revert Reverts finnishtransportagency/digiroad2#2596

Revert "Revert "Droth 3744 enable tram stops on pedestrian links""

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala

Droth 3802 allow tramp stops on pedestrian ways during csv import

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala

- Korjattu puuttuva ')'-merkki joka hajotti buildin

 DROTH-3802 fixed missing parenthesis

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala

Ei tehdä lennosta oikaisuja vaan tehdään ne tallennuksen yhteydessä. Tämä on väliratkaisu kunnes UI työkalut on korjattu toimimaan paremmalla tavalla.

Droth 3816 adjust when saving

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala

sama filter kun haetaan kaistoja id avulla

 DROTH-3816 add same 1000 filter when fetching lanes

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala

Vaikuttaisi toimivan ok. Ei tullut erroria logiin, eikä kantaan nolla/miinuspituisia. Pistotarkastelulla katsotut pysäköintikiellot näytti oikeanlaisilta.

Droth 3766 fix parking prohibition generator

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdaterSpec.scala

En onnistunut toistamaan bugia lokaalisti, mutta arvelisin, että assetit voi tulla myös "väärässä järjestyksessä", jolloin sorttaaminen auttaisi.

DROTH-3493_fix_sorting_bug

---

src/main/resources/logback.xml

Testaan nyt tätä, tuskin ainakaan rikkoo mitään. Jos menee läpi, vien tämän myös siihen samuutuscoden perushaaraan.

DROTH-3493 logback to same as before

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Lisään vähän logitusta, että näen millainen asset kaatuu none.getiin.

DROTH-3493 improve logging for possible none.get

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

Hyväksytty aiemmin pr https://github.com/finnishtransportagency/digiroad2/pull/2662

Droth 3493 samuutus code to dev

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Logitetaan vielä toi muutostieto, mitä aiemmin ehdotettiin.

DROTH-3493 add change info to exception logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

 DROTH-3727 Fixed comparison

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/MValueCalculator.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala

Logitetaan väliaikaisesti adjustmentteja, jotta saadaan stackOverFlow kiinni. Samalla tarkennettu varoitusta nollamittaisesta assetista.

Droth 3493 fix bugs

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneWorkListService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

Korjataan nested transaction kaistojen samuutuksessa.

DROTH-3493 fix nested transaction on lanes

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdaterSpec.scala

Huomasin vasta deville vietävän haaran testilogista, että compile failaa, joten viedään vielä pari sulkumerkkiä.

DROTH-3493 fix compilation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

Korjataan vielä toinen nested transaction. Toivotaan, että ei tule enää lisää. Yritin katsoa koodia eteenpäin, jos olisi helposti havainnut.

DROTH-3493 fix nested transaction

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

DROTH-3493 Fix unit test

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala

Korjattu eurooppateiden ja  liittymänumero visualisointi.

 DROTH-3834 fix europianroadnumber and exit number visualization

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

katottu jo : https://github.com/finnishtransportagency/digiroad2/pull/2712

Droth 3493 samuutus code

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdateProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdater.scala

Lisätty hieman logitusta. Noita Option.get oli jonkinverran, joten en nyt lähtenyt niitä setvimään. Vaatii hieman uudelleen miettimistä ja turhien Option poistoa.

 DROTH-3493 add some logging and commentation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala

DROTH-3844 fix nested transaction

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala

-Korjattu tilanne, jossa floating-arvon päivityksen jälkeen frontille palautetaan vanha, ei päivitetty asset.

Droth 3727 update floating bugfix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala

 DROTH-3727 no need for asset+link coupling when fetching

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala

- Korjattu tilanne jossa kopiointi ei tarjoa ajankohtaisia tietoja

 DROTH-3727 Asset fetched instead of copied

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Batch ajettu devillä. Vaikutti toimivan ok.

Droth 3844 fix unknown speed limit

---

UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

DROTH-3725 storyn alaiset muutokset yhtenä squashattuna commitina

DROTH-3725 (including DROTH-3726 DROTH-3727 DROTH-3728) as single commit

---

UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Pysäkkijutut ja tuntemattomien eräajo nextReleaseen.

Droth 3726 3727 3728 3844 to next release

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

Tuotantojulkaisun jälkeinen master -> development
Haaraan mergetty master ja korjattu tulleet merge konfliktit. Konfliktit suurilta osin whitespace, masterissa oli poistettu testi "Update existing masstransitstop if the new distance is greater than 50 meters". Säilytin nyt sen tähän.

Development fix master merge conflict

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/PavedRoadUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala

DROTH-3862_and_DROTH-3861
poistetaan suodatus joka tullut epähuomioksa

 DROTH-3862 remove filtering

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Droth 3493 add documentation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

poistetaan compile virhe perinnän poistolla

 DROTH-3493 fix compile error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcess.scala

DROTH-3502 Add logging to batch

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcess.scala

Oli kaatunut None.get. Korjattu käsittely ja lisätty lokitusta

DROTH-3502 fix none get

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ManoeuvreUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ManoeuvreUpdaterSpec.scala

Korjattu partition method. Lisätty unit test.

 DROTH-3522 fix partition and add test

---

digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LanePartitionerSpec.scala

Äskeiset muutokset kaista attribuutteihin muutti tän testin vastausten järjestystä, korjattu testi vakaammaksi

DROTH-3853 Fix unstable test.

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ValidateSamuutus.scala

lisätään unohtunut newTransaction = false

 DROTH-3692 add missing newTranaction = false in samuutus validation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/PavedRoadUpdater.scala

Lisätään lokitusta, niin saa virhetilanteen kartoitettua paremmin ja voi luoda yksikkötestin kuvaamaan tilannetta.

DROTH-3886 Improve logging

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/LogUtilsGeo.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala

 DROTH-3855 fix compile error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala

Lisätarkennus:
- tarkenne (typeExtention) ei ole pakollinen tieto ja voidaan jättää antamatta. Annettuna se tulee kuitenkin aina validoida.

 DROTH-3822 typeExtension is not mandatory info and may be absent, but if given must be validated

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala

Lisätarkennuksia ääkkösten käyttöön ja puuttellisista tiedoista varoitukseen.
Testattu developmentissa, toimii ok.

Droth 3822 csv import for service points

---

.gitignore
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ValidatorDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

käytetään values ja join,
Katotaan tuleekos nopeammaksi.
Lisätty myös parallel ajo jos isoja listoja. 
Siistitty koodia duplikaatti koodista ja tarpeettomista tarkistuksista.

Droth 3855 speed up samuutus

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadWidthUpdaterSpec.scala

Lisätty yksikkötesti tiketissä kuvatulle tilanteelle. Virhettä ei voitu toistaa, mahdollisesti korjaantunut muiden muutosten myötä.

DROTH-3866 Add unit test for case described in ticket

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/PavedRoadUpdaterSpec.scala

Venytetään päällyste linkin pituiseksi. Pitäisi mennä ihan lisäämällä assetin tyyppi listaan. Muokattu testit uuden logiikan mukaiseksi.

DROTH-3901 fit paving to road link length

---

UI/src/view/assetsOnExpiredLinksWorkList.js

Operaattorin pyynnöstä pieniä parannuksia työlistan UI;lle.
- Kolumnin teksti kuvaavampi
- Poistettu turha pilkun lisääminen ensimmäisen pisteen jälkeen, jos kyseessä pistemäinen asset, jolla vain yksi piste

DROTH-3503 Improve assetsOnExpiredLinks worklist according to request

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdaterSpec.scala

Korjattu virheet kuvauksissa, joissa toiminnallisesta luokasta puhutaan hallinnollisena luokkana.

 DROTH-3882 Fixed wrong attribute description (admin -> functional)

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Korjattu tilanne jossa kohteelle tulee kaksi m-arvo korjausta. Lisätty logitus löytämään nämä tilanteen, jos tulee viellä lisää.

 DROTH-3913 fix duplication bug

---

UI/src/view/link_property/linkPropertyForm.js

Kuvaavammat popup viestit tielinkin muokkauksessa. operaattorit hyväksyneet.

DROTH-3666 Fix pop up messages

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala

Muutetaan kääntymisrajoitusten hakua UI-puolella niin, että se ei kaadu, jos jostain syystä rajoituksen elementeistä puuttuu alku tai loppu.

DROTH-3870 fix manoeuvre fetching bug

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISMaintenanceDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISDirectionalTrafficSignDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISTrafficSignDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala

Lisätään side code 0.
Liikennemerkeissä se muunnetaan liikennesuunta 0.
Muissa tilanteissa heitetään virhe.

DROTH-3938 add side code 0 and handling for traffic sign

---

aws/buildspecs/development.yaml
aws/buildspecs/test.yaml
aws/cloud-formation/support-repository.yml
aws/fargate/Dockerfile

Dev buildasi ja toimi ihan normaalisti, joten varmaan voi viedä qa:lle?

Droth 3941 update docker base image

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

Oli jäänyt filtteröimättä kaistat käsiteltävälle vanhalle linkille.

DROTH-3666 Fix bug with filtering lanes on link

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

Ei korjata ton Enum nimeä nyt, build failas kun vanha enum käytössä muualla.

DROTH-3885 Revert renaming enum

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

Viedään DROTH-3885 ja DROTH-2935 QA:lle testattavaksi

Droth 3885 csv import side code 0 fix from master

---

UI/src/utils/validity-directions.js
UI/src/view/point_asset/pointAssetForm.js
UI/src/view/point_asset/trafficSignForm.js

Varmaan voi viedä tänne kans, niin säästytään konflikteilta jatkossa.

DROTH-3884 ui handling for traffic signs outside roads

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Cherry-pickattu commitit ja selvitetty konfliktit.

DROTH-3902 db reset safeguard to samuutus code

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Devin build meni läpi, joten viedään tämä myös samuutus_codeen.

DROTH-3902 allow aws test connection to reset unit test db

---

aws/cloud-formation/cache/cache.yaml

 DROTH-3827 downgrade cache to smaller version

---

UI/src/view/point_asset/pointAssetForm.js
UI/src/view/point_asset/trafficSignForm.js

Korjausten jälkeen toimii devillä ok.

Droth 3884 UI handling for traffic signs outside roads from master

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala
digiroad2-oracle/src/test/resources/smallChangeSet.json

jos kuntakoodi on null, ohitetaan se

 DROTH-3954 filter changes where municipality code is null

---

UI/src/view/point_asset/trafficSignForm.js

Näytetään suuntima myös read only lomakkeella, jos liikennemerkki on tieverkon ulkopuolella.

DROTH-3884 render bearing value in read only form

---

digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala

Muokattu testi muotoon, että ei ole väliä, mikä asseteista jää jäljelle yhdistymisen jälkeen.

DROTH-3493 fix unstable test

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficLightsCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala

SideCoden muodostuminen liikennemerkkien ja -valojen CSV-importissa korjattu, parannettu koodia hieman, yhtenäistetty liikennevalot toimimaan sideCoden ja Bearing osalta samoin kuten liikennemerkit.

DROTH-3885 Fix determining sideCode, improve code

---

UI/src/view/point_asset/trafficSignForm.js

DROTH-3884 don't filter by car roads only when recalculating bearing

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala

Droth 3952 return info about error

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AssetPropertyConfiguration.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdaterSpec.scala

Lisätty puuttuva arvo, lisätty olemassa olevaan terminaalipysäkin samuutus testiin testaus arvon käytölle.

Droth 3958 mass transit stop samuutus number format exception fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Ohitetaan virheelinen change info. Muissa tilanteissa kaadetaan samuutus.

 DROTH-3963

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

- Poistettu turhia lokeja täyttäviä lokituksia kaistojen samuutuksesta
- Lisätty logArrayProgress metodi LogUtils seuraamaan looppien edistymistä
- lisätty timer fuse operaatioon

Droth 3968 lanes samuutus slowness fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Lisätty progress lokitusta viivamaisten samuutukseen

DROTH-3971 Add array progress logging to LinearAssetUpdater

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

 DROTH-3961 add lifecycle info

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

Korjattu oikea muutosmäärä testiin, jostain syystä ei näkynyt failanneena lokaalisti kaikkia testejä ajaessa

DROTH-3937 Fix smallChangeSet.json test

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

samuutus_code haarassa on väärä alias tässä käytössä. Tod. näk. tuli mulla virhe master -> samuutus_code merge konfliktin ratkomisessa

DROTH-3493 Fix wrong table alias mistake from resolving merge conflict

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json

Nostettu dev job definiton käytetyt vCpu 4 -> 8

DROTH-3987 Increase used cpu count to 8

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

Partition kävi hakemassa, joka kerta uudestaan työlistan kaikki kohteet.
Korjataan hakemalla lista vain kerran.

 DROTH-3978 fix slow partition

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

DROTH-3977 refactor mergerOperations

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/HazMatTransportProhibitionUpdaterSpec.scala

Venytetään VAK-rajoitus linkin mittaiseksi.

DROTH-3985 fit hazmat to road link length

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala

logitusta lisää, poista parallel progress logitus, ohitetaan epäonnistuneen raportti rivin luonti

Droth 3978 speed up lanes

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Käytetään jo haettuja alkuperäisiä assetteja operationSteps mergessä

DROTH-3977 Use already fetched assets when merging OperationSteps

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

Lambdan korjaus tännekin. Tajusin, että siitä normilambdasta buildattu image ei toimi, kun entrypoint on väärä.

Dev lambda road link change handler

---

lambda/road-link-change-handler/aws/dev/lambda-resources.json
lambda/road-link-change-handler/env.json

Vaihdettu url, kuten tiketissä pyydetään.

DROTH-3992 change kgv url

---

aws/cloud-formation/task-definition/dev-create-taskdefinition.yaml

 DROTH-3998 change api to prod

---

UI/src/view/link_property/linkPropertyForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Annetaan operaattorille oikeus muokata kaikkia hallinnollisia luokkia, myös valtio-luokkaa.

DROTH-4003 allow operator to edit state roads

---

aws/fargate/Dockerfile

En havainnut devin buildissa tai käytössä ongelmia, joten poisto lienee ok.

Droth 4016 remove xz and openssl

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

DROTH-4015 Fix changes size in unit test

---

UI/src/view/point_asset/trafficSignForm.js

Sallitaan lisäkilpi H9.1 (eli OTHValue 140) kävelyn ja pyöräilyn väylille.

Droth 4001 allow additional panel h9.1 for pedestrians

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Droth 3951 fix lanes on point missing link handling

---

UI/src/controller/trafficSignsCollection.js
UI/src/controller/trafficSignsReadOnlyCollection.js
UI/src/utils/backend-utils.js

DROTH-4010 fix pedestrian crossings mixing with traffic signs

---

UI/src/assetTypeConfiguration.js

DROTH-2988 read only specification to walkways

---

UI/src/view/providers/selectToolControl.js

Droth 2772 remove zooming when double clicking

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

sourceid on isompi kuin int max value, käytetään long tyyppiä

DROTH-4007 int is too small for sourceid, use long

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

dev kaikki vaikuttaa toimivan.

Droth 4007 fix long

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json

Laskettu dev eräajo resurssit takaisin matalemmiksi

DROTH-3999 Change dev batch to use 4 vCPU, 30720mb

---

lambda/road-link-change-handler/aws/dev/lambda-resources.json
lambda/road-link-change-handler/aws/prod/lambda-resources.json
lambda/road-link-change-handler/aws/qa/lambda-resources.json
lambda/road-link-change-handler/env.json

 DROTH-4007 update kgv and vkm url

---

UI/src/view/linear_asset/linearAssetLabel.js

Tossa menee parametrit vähän väärin: parametrina tulee oikeasti asset eikä suoraan value, jolloin value pitää vielä katsoa assetista.

DROTH-3740 fix winter speed limit visualization

---

UI/src/view/point_asset/pointAssetLayer.js
UI/src/view/point_asset/pointAssetStyle.js

Selvittelyjen perusteella assetilla voi olla useampi openlayers feature-objecti. Kun haetaan findilla, löydetään vain yksi, joka sekoittaa systeemin.
Samansuuntaisuuden tarkistamisessa liikennevaloilla ei ole mielestäni tekemistä assetin id:n kanssa, joten poistin sen.

Droth 3955 disappearing arrow bug

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Lisätty exit, koska batch ei pysähtynyt käsittelyn jälkeen. Erikoiskuljetusyhteydet filtteröidään pois, ja yksityistiet generoinnin osalta (en lähtenyt poistamaan yksityisteitä, että menisi mahdollisimman nopeasti).

Droth 4041 errors in unknown speedlimits

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Tajusin, että haen tässä poisto-osassa tarpeettomasti kaikki linkit. Lopputulos varmaan sama, mutta nopeuttanee, jos haen vain noi, missä on tuntemattomia.

DROTH-4041 get only links with unknown

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

DROTH-4040 Implement DateTime deserialization

---

UI/src/model/selectedPointAsset.js

DROTH-4043 Filter out unneeded 'counter' property before saving

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Eräajo toimimaan uuden määrittelyn mukaan.

DROTH-4041 filter according to new definition

---

digiroad2-oracle/src/main/resources/db/migration/V1_39__drop_old_municipality_api_tables.sql

 DROTH-3411 deleted wrong table

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Lisätään vielä poistuvat linkit käsittelyyn.

DROTH-4041 add links expiring soon to unsupported links

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Ajopolku haluttiin vielä mukaan.

DROTH-4041 add tractor road to unsupported links

---

UI/src/view/linear_asset/linearAssetLabel.js

Dev ok. Mulla näköjään branchissa ja commitissa mennyt nelonen ja seiska väärin päin. Korjasin otsikkoon.

DROTH-3470 fix winter speed limit visualization

---

UI/src/assetTypeConfiguration.js
UI/src/controller/obstaclesRoadCollection.js
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala

Droth 3774 allow railway crossings to new types

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Pudotettu jobien max ajoaika viikosta 3vrk, jotta jumittuneet jobit eivät jää päälle turhaan.

 DROTH-3576 shorter timeout for jobs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala

DROTH-4019 bypass missing value, log error

---

UI/src/view/linear_asset/linearAssetLayer.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala

Rajataan groupedLinearAssetLayer vain massarajoituksille, jolloin se ei sotke muita tietolajeja. Korjataan json sellaiseen muotoon, jota UI pystyy hyödyntämään massarajoitusten piirtämisessä.

Droth 3669 3767 3983

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala

Siiretty validointi ennen tallennusta. Refactor koodi käyttämään uutta metodia.

Droth 4019 add logging dev

---

digiroad2-oracle/src/main/resources/db/migration/V1_40__fix_traffic_sign_enumerated_values.sql

Droth 2877 missing single choice value

---

UI/src/utils/roadAddressInfoPopup.js

 DROTH-3462 changed roadData check to allow 0s

---

UI/src/application.js
UI/src/model/applicationModel.js
UI/src/view/zoomBox.js

Droth 2844 block zooming out during modifications

---

digiroad2-oracle/src/main/resources/db/migration/V1_41__delete_unnecessary_asset_types_from_samuutus.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala

Droth 3838 remove unnecessary asset types from samuutus success

---

UI/src/view/workListView.js

 DROTH-4045 deletable speedLimit value should not be parsed to int

---

UI/src/view/providers/layer.js

 DROTH-2844 Removed selectionTool deactivation from layer stoppage

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/task-definition/dev-create-taskdefinition.yaml
aws/cloud-formation/task-definition/prod-create-taskdefinition.yaml
aws/cloud-formation/task-definition/qa-create-taskdefinition.yaml

poistetaan cloudformation myös vvh

 DROTH-3667 remove vvh parameters

---

UI/src/view/providers/layer.js

 DROTH-2844 readded deactivation during stoppage

---

project/build.scala

Logback-classic 1.2.3 -> 1.3.11

DROTH-4022 Upgrade logback-classic to 1.3.11

---

project/build.scala

Katsottu https://github.com/finnishtransportagency/digiroad2/pull/3195

Droth 4021 dependency changes

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala

Toinen testauskierros roadLinkPropertyUpdaterin pullonkaulojen selvittämiseksi ja ratkaisemiseksi.

 DROTH-3956 Some structure optimization

---

UI/src/assetTypeConfiguration.js

assetTypeConfiguration muodosti formille required-fieldin väärässä muodossa, joka aiheutti backendissä parse-errorin

DROTH-4100 fix parking prohibition changes are not saving

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporterSpec.scala

Suorituskykytestit lineaarisille, pistemäisille ja tielinkin ominaisuustiedoille lokaalia testaamista varten.
Testien perusteella en havainnut optimointitarvetta csv:n generoinnille, joten itse generointia ei ole muokattu.

DROTH-4096 performance tests for csv generation

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala

Sallitaan csv import valtion teille esteiden ja tasoristeysten osalta. Virheitä aiheuttaneet viennit menevät tällöin läpi.

DROTH-4083 allow csv import to state roads

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala

Uudet esterakennelmatyypit lisätty CSV-importtiin.

DROTH-4107 Added new obstacle types to be accepted in csv imports.

---

project/build.scala

DROTH-4109 Update scalatra swagger 2.6.3 -> 2.6.5

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/task-definition/dev-create-taskdefinition.yaml
aws/cloud-formation/task-definition/prod-create-taskdefinition.yaml
aws/cloud-formation/task-definition/qa-create-taskdefinition.yaml

DROTH-4055 AWS muutokset otettu omaan haaraan josta viedään masteriin. Päivitetään resurssit sitä mukaan kun viedään uuteen ympäristöön koodimuutokset.

DROTH-4055 Remove Viite values from AWS files

---

lambda/road-link-change-handler/src/service/s3-service.ts

Muutossetin luomiseen käytettävä 'until' päivänmääräksi asetetaan seuraava päivä 'since' päivänmäärästä.

Fix until date before daily samuutus

---

lambda/road-link-change-handler/aws/cloudformation/lambda-resources.yaml

Korjattu cron käynnistämään samuutusprosessi ma - to 21:30 suomen aikaan

Change start-road-link-change-handler-event cron expression

---

lambda/road-link-change-handler/src/service/s3-service.ts

korjattu päivänmäärät muutossetin muodostukseen

Use last 'until' date as current 'since'

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala

Korjattu bugi, jossa tuntemattomia ja identiteetittömiä nopeusrajoituksia käsiteltiin ryhmänä.

 DROTH-4114 Fixed a bug where unknown speedLimits with no roadIdentifier were grouped together

---

UI/src/controller/trafficSignsCollection.js
UI/src/controller/trafficSignsReadOnlyCollection.js
UI/src/enumerations.js

DROTH-4075 fix traffic sign visibility on kapy links

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala

Viedään (samuutustestauksen vuoksi suoraan) qa:lla hyväksytyt muutokset myös deville, jotta aiemmat bugit eivät häiritse samuutustestausta.

Droth 4114 faster speed limit query as default

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadLinkReplacementFinder.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcessSpec.scala

Korjattu jo työlistalla olevien päättyneillä linkeillä sijaitsevien assettien inserttaaminen työlistaan uudestaan.
Huom. RoadLinkReplacementFinder commit löytyy jo deviltä, GitHub sekoilee.

Droth 4111 daily samuutus fixes

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ValidateSamuutus.scala

Jos samuutuksessa ei uusia linkkejä, joilla validoida assetteja niin skipataan validointi ja merkataan samuutus onnistuneeksi. Jätetty DAO metodeihin mahdollisuus käyttää tyhjää linkID listaa, jolloin käydään kaikki linkit läpi jos validointi-metodeja kutsutaan topology_validation eräajon kautta.

DROTH-4158 skip validation if now new links to filter

---

UI/src/view/suggestedAssetsWorkList.js

DROTH-4175 use Finnish term for suggested assets

---

UI/src/enumerations.js
UI/src/less/core/tables.less
UI/src/utils/backend-utils.js
UI/src/view/manoeuvreSamuutusWorkList.js
UI/src/view/workListView.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/resources/db/migration/V1_47__change_manoeuvre_work_list_table.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/manoeuvre/ManoeuvreDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ManoeuvreUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ManoeuvreUpdaterSpec.scala

Lisätty halutut kentät tietokanta-tauluun ja työlista-näkymään. Lisätty mahdollisuus poistaa kohteita työlistalta.

Droth 4167 manoeuvre work list improvements

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

 DROTH-4184 Added missing information to generated unknownSpeedLimits

---

UI/src/enumerations.js
UI/src/less/site/action-panel.less
UI/src/view/link_property/linkPropertyForm.js
UI/src/view/link_property/linkPropertyLayerStyles.js
UI/src/view/navigationpanel/roadLinkBox.js

DROTH-4149 use functional class 9 in ui

---

UI/src/model/selectedSpeedLimit.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Nopeusrajoituksilla piirretään nyt osittaiset tuntemattomat segmentit linkillä ja niitä pystyy muokkaamaan.

Droth 4185 partial unknown speed limit

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

Fix change set size in RoadLinkChangeClientSpec

DROTH-4123 samuutus asset expire bug

---

UI/src/view/municipalitySituationPopup.js
UI/src/view/municipalityWorkList.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala

Pävivitetty kunnan tilannekuvassa esitettävää informaatiota:
- "K-TUNNUS" -> "TUNNUS"
- Tarkistetut tietolajit päivitetty uuteen listaan
- Lisätty tooltip, joka selventää pallukan muodossa tarjottua vinkkiä kuntaylläpitäjälle annetuista vihjeistä
Lisäksi muokattu operaattorin toiveesta kuntasivulle "Vihjetieto" -> "Vihjeet"

Droth 4174 municipality situation update

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDaoSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcessSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdaterSpec.scala

Lisätty enrichRoadLink mockauset

DROTH-4185 Add needed mocks for enrichRoadLink

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala

Lisätty uusi toiminnallinen luokka 9 (Huoltoaukot ja erikoiskuljetusyhteydet ilman puomia tai puomilla) mukaan isCarTrafficRoad-määrittelyyn.

 DROTH-4203 added 9 to allowed functional classes

---

UI/src/controller/speedLimitsCollection.js
UI/src/utils/backend-utils.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Droth 4189 fix complementarylinks in speedlimits

---

digiroad2-oracle/src/main/resources/clear-db.sql

"drop table if exists manouvre_samuutus_work_list" täytyy säilyttää kunnes taulu on poistunut kaikista tietokannoista.

 DROTH-4177 readded old drop table clause to fix DataFixture reset problem

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PointAssetOperationsSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/DirectionalPointAssetUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/TrafficSignUpdaterSpec.scala

and externalId is included in the change report

DROTH-4201 Preserve externalId during samuutus 

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDaoSpec.scala

dev ok, operaattoreille testiin

Droth 4205 functional class 9 verification to next release

---

UI/src/controller/manoeuvresCollection.js
UI/src/controller/roadCollection.js
UI/src/less/main.less
UI/src/less/site/pop-up-map-plugins.less
UI/src/utils/backend-utils.js
UI/src/view/linear_asset/baseManoeuvreLayer.js
UI/src/view/linear_asset/manoeuvreForm.js
UI/src/view/linear_asset/manoeuvreLayer.js
UI/src/view/manoeuvreSamuutusWorkList.js
UI/src/view/pop_up_map/popUpManoeuvreBox.js
UI/src/view/pop_up_map/popUpManoeuvreLayer.js
UI/src/view/pop_up_map/popUpMapView.js
UI/src/view/pop_up_map/workListPopUpMap.js
UI/src/view/workListView.js
UI/test/integration-tests.html
UI/tmpl/index.html
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/resources/clear-db.sql
digiroad2-oracle/src/main/resources/db/migration/V1_49__rename_manoeuvre_samuutus_worklist.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/manoeuvre/ManoeuvreDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcess.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcessSpec.scala

Droth 4177 manoeuvre worklist map to next release

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ValidatorDao.scala

Lisätty voimassaolotarkistus valindointiskriptiin

 DROTH-4223 added valid_to check to assetTooShort

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Lisätty täsmälokitusta jumittuneeseen kohtaan

 DROTH-4209 added logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala

Lisätty yksittäisten säikeiden tilaa (Runnable/Waiting/Terminated) lokittava työkalu LinearAssetUpdaterProcess mainiin

 DROTH-4209 added thread state logger

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Lisätty jumikohtaan linkkitietojen lokitusta

 DROTH-4209 added link logging to goThroughChanges

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

 DROTH-4209 More logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LogUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAOSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ExpiredRoadLinkHandlingProcessSpec.scala

Korjattu äärimmäisen hidas "find_assets_on_expired_road_links" -eräajo

Droth 4209 more logging to stuck processes

---

UI/csv_import.html
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

... adminstrative class limits

DROTH-3172 fix public transport csv import tool

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala

 DROTH-4255 Display historylink municipalityCode as 0 when null to retain uniform practice across process

---

UI/csv_import.html
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

Droth 3172 fix public transport csv import tool

---

UI/src/utils/date-utils.js
UI/src/view/point_asset/massTransitStopForm.js
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

DROTH-4166 mass transit stop csv import improvements

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala

Vaihdettu testit käyttämään oikeaa fetchiä.

DROTH-3172 update tests to mock complementary links too

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

DROTH-3172 change roadlink fetching function to one that includes 

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

Aikaisemmassa resolvessa oli jäänyt yksi boolean lisäämättä.

Droth 4166 mass transit stop csv import improvements to qa

---

digiroad2-oracle/src/main/resources/db/migration/V1_51__columns_to_additional_panel.sql

Migraatiotiedosto lisätty liikennemerkkien tievelho-integraation takia. additional_panel-tauluun lisätään modified_date ja created_date kentät calculateDiff varten, external_ids lisätty koska lisäkilvet ovat omia itsenäisiä merkkejään Velhossa omalla OID:llään. Unique constraint voidaan lisätä, koska additional_panel taulussa on vain voimassa olevia lisäkilpiä.

DROTH-4186 Add migration file for traffic sign Tievelho-integration

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Väliaikaista lokitusta debuggaukseen

DROTH-4201 add logging

---

UI/src/less/site/pop-up-map-plugins.less

DROTH-4251 remove duplicate ol-popup styling

---

digiroad2-oracle/src/main/resources/db/migration/V1_52__increase_externalId_lenght.sql

 DROTH-4265 increase varchart length so that velho assets can be saved

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

 DROTH-4218 add prohibition additionalInfo to intergrationAPI output

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/MaintenanceRoadUpdater.scala

Lisätty täsmälokitusta rautateiden huolteiden samuutusbugin sijainnin selvittämiseksi. Lokitukset poistetaan kun sijaintia selviää.

 DROTH-4240 Added temporary logging to find bug case

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Tuntemattomia nopeusrajoituksia valittaessa käyttöliittymässä klikkaamalla valikoitui vain yksi linkki, vaikka olisi pitänyt valikoitua koko ketju.

DROTH-4197 fix unknown speedlimit grouping

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Droth 4197 fix unknown speedlimit grouping

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ValidatorDao.scala

Lisäsin jakojäännös filterin, jotta kaistoja vertaillaan vain samalla puolella pääkaistaa

DROTH-4233 add modulo filter

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Käyty läpi tiketin ongelmalinkkejä, vaikuttaisi toimivan nyt ok.

DROTH-4213 ignore commas within quotes to fix split bug

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala

Droth 4342 speedlimits bug fix

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala

CSV-importilla voi jatkossa lisätä dataa vain operaattorikäyttäjänä

DROTH-4338 remove csv import rights from municipality users

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

Korjataan hajonneet testit + yksi rivi, jossa voi periaatteessa tulla head of empty list. Kyseisessä koodissa tsekataan vain, onko kyseessä ratikka, joten Unknown of mielestäni tähän turvallinen default-arvo.

DROTH-4337 fix tests

---

UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js
UI/src/view/linear_asset/linearAssetLayer.js
UI/src/view/linear_asset/speedLimitLayer.js
UI/src/view/point_asset/massTransitStopForm.js

Muutama korjaus vielä, mitä huomasin dev-testailussa. Bussipysäkkien virheilmoitus oli epätarkka ja laatikkovalintojen virheilmoitus puuttui.

Droth 4336

---

digiroad2-oracle/src/main/resources/db/migration/V1_54__update_enumerated_value_for_obstacles.sql

Muutettu esterakennelmien koodiarvojen nimiä.

DROTH-4278 updated enumerated_value name_fi for obstacles

---

UI/src/view/point_asset/obstacleForm.js

DROTH-4276 Add info text for obstacle types on obstacleForm.js

---

digiroad2-oracle/src/main/resources/db/migration/V1_V55__update_enumerated_value_for_E30_traffic_sign.sql

Korjattu typo E30 liikennemerkin rivillä enumerated_value-taulussa

 DROTH-4202 Fix typo in enumerated value

---

UI/src/controller/trafficSignsCollection.js
UI/src/enumerations.js
UI/src/view/point_asset/trafficSignForm.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala

Droth 4296

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

Droth 4291 traffic sign csv import bug

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitionerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

DROTH-4399 refactor linearAssetPartitioner

---

UI/src/view/link_property/linkPropertyForm.js

Kuuntelija muutettu tunnistamaan kaikki syöttötavat, pelkän näppäimistön sijaan.

DROTH-4395 use 'input' event to support right-click paste in form fields

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Korjataan nested transaction leikkauksessa ja kaksisuuntaiseksi jakamisessa.

DROTH-4337 fix nested transaction

---

project/build.scala

Päivitetään logback tiketissä mainittuun versioon. En havainnut buildissa, testissä enkä sovelluksen käytössä ongelmaa.

DROTH-4306 update logback

---

UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js

Virtuaalipysäkkiä luotaessa ei ole vielä pysäkkiä, joka tarkistettaisiin, niin tulee undefined. Pitäisi hoitua tällä. Taisi hajota siinä vaiheessa, kun lopuksi katsoin noita pysäkkien siirtelyitä.

DROTH-4391 fix virtual stop creation

---

project/build.scala

Testattu sbt compile ja test sekä sovelluksen käyttö. Vaikuttaisi ok ilman tätä kirjastoa.

DROTH-4328 remove commons-io

---

aws/cloud-formation/task-definition/dev-create-taskdefinition.yaml
aws/cloud-formation/task-definition/prod-create-taskdefinition.yaml
aws/cloud-formation/task-definition/qa-create-taskdefinition.yaml

Ulkoiseen välimuistiin ei mahdu enään kaikki tielinkit, Otetaan palvelu pois käytöstä.

 DROTH-4453 turn off cache

---

aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

false meni väärään riviin vahingossa nyt korjattu.

 DROTH-4453 accidentally turned wrong true to false

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala

DROTH-4464 remove filter from complementary link fetch
