UI/src/view/SpeedLimitLayer.js

Fix the TODO comment to stop listening the map:moved event when layer not selected.
While at it, refactor the speed limit layer to let the base class Layer to control starting, stoping, refreshing etc. by implementing the base class template functions instead of having own overlapping implementation.

Refactor speedlimit layer

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

We will need the whole link geometry for changed assets (speed limits at this moment) when we convert to the eventual Rosatte format. Included:
- For each changed asset, include the link geometry where the asset resides to the API response.
- Remove alternative API endpoint.
- Add type annotations where useful.

Add link geometry to change API

---

src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

Open LR encoding requires the roadlinks:
-geometry
-link type
-functional class
Open LR encoding will be performed outside OTH. The simplest approach is to embed the relevant information into each change info instead of having to request road link information separately.

Include the link type and functional class for changed speed limit in change api

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/oracle/OracleLinearAssetDao.scala
src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala

The TN-ITS API is the only client for the change api and it does not care about the changes propagating from the changes to the VVH roadlinks. Including changes to geometry and link id's.
Hence simply filter out all these adjustements.

Filter geometry adjustements from change api

---

UI/src/model/ApplicationModel.js
UI/src/view/navigationpanel/ActionPanelBoxes.js
UI/src/view/navigationpanel/EditModeToggleButton.js
UI/src/view/navigationpanel/LinearAssetBox.js
UI/src/view/navigationpanel/ManoeuvreBox.js
UI/src/view/navigationpanel/PointAssetBox.js
UI/src/view/navigationpanel/RoadLinkBox.js

The application no longer resets the "Edit Mode" when transitioning between data views.
Changed each entry in the navigation panel to keep the "Edition Tools" visible if the "Edit Mode" is toggled On.

Droth 14 keeping edit mode when jumping objects

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/SpeedLimitService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitServiceSpec.scala

Fixed speed limit projection bugs (vvhtimestamp was occasionally taken from wrong speed limit), now combining of speed limits that are really close (<10 cm) instead of connected (<1 µm).

Droth-271 & 265: speedlimit projection fix

---

UI/src/view/MassTransitStopLayer.js

- Add missing the message "Pysäkkiä siirretty yli 50 metriä. Siirron yhteydessä vanha pysäkki lakkautetaan ja luodaan uusi pysäkki." for cases when the mass transit stop moved more than 50 meters and is managed by ELY-keskus.

DROTH-310 (144) Bug: "Bus stop moved" popup missing for bus stops with ELY-keskus as administrative class

---

UI/src/application.js
UI/src/model/SelectedMassTransitStop.js
UI/src/view/MassTransitStopForm.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/MassTransitStopServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TestTransactions.scala

These features are missing from bus stop removal implementation (DROTH-273):
- There should be a confirmation popup for user when Poista checkbox is checked and user clicks Tallenna. See DROTH-273 for message text.
- The bus stop should be first removed from Tierekisteri and if that is successful, it can be removed from OTH
- If removal from Tierekisteri fails, user should be shown a popup message. See DROTH-273 for message text.

DROTH-312 (144) Bug: Bus stop removal is not implemented according to specification

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/AssetDataImporter.scala

A log needs to be created of all the rows that cannot be saved to Viite during the initial data load. All attribute data needs to be picked up. Reason codes used:
1 = Link-ID is not found in the VVH interface
2 = Values of the start and end fields are totally outside of the link geometry 
3 = Another reason
These are for example cases where the link-ID is not found in the VVH interface and values of the start and end fields of a road address segment are totally outside of the link geometry (for example the length of the link is 10, road address start is 12 and end 18).

Drvvh 312 creating log of the initial data load

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/masstransitstop/MassTransitStopOperations.scala

- Create method to verified if BusStop was modified to Virtual;
- Join the previous validation created to remove the LiVi_ID in OTH in case bus stop (maintainer ELY) status was moved from anything to virtual;
- Add the Remove Operation type in the Operation match.

DROTH-568 If a bus stop (maintainer ELY) status is moved from anything to virtual (type = 5) stop needs to be removed from Tierekisteri

---

viite-UI/src/model/RoadCollection.js

Created a method that will return all the groups that have the same roadNumber ,anomaly ,roadLinkType ,roadPartNumber and trackCode values if the selected group is not a group of Unknown roads or Other (Muu tieverkko) roads.

VIITE-344 - Selection of homogeneous road section doesn't work

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

When old project was opened, it showed wrong discontinuity type to some segments

Fixes discontinuity type of segment when opening old project

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

-Filter condition when returning road_link_properties

DROTH-639 Kalpa-API: filter out MTK_CLASS if linkSource = 2

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala

Fixed matching rules to allow non-intersecting but non-connected geometries as valid targets.

Viite 413 t intersection doesn't give an error

---

viite-UI/src/view/LinkPropertyLayer.js

Force refreshing to get new road link address values for the whole road.

VIITE-405 reset roadcollection before fetching new road links 

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ViiteTierekisteriClient.scala

When tierekisteri did not accept project, user  always got "Bad request" message to UI after pressing publish. Now we parse error message when we are expecting one (with html error codes 400-499)

Fix for not parsing actual error message

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/RoadLinkServiceSpec.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculatorSpec.scala

Changed the RoadAddress in order to include the adjusted_timestamp~from LRM_POSITION; ground work for Viite-82.
Added a test for the getChangeInfoFromVVH method on the RoadLinkService.
Added a small helper method that when supplied with both with a sequence of RoadAddresses and ChangeInfos it will return what un-applied changeInfos match said roadAddress.
Added a TODO as a reminder of future changes to the vvhChangeInfo queries.

Viite 493 vvh changetable

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/DefloatMapper.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala

Fix crash on two links and three segments to single link mapping. Adjust road address geometries after transfer to match properly the target geometry and not just approximate geometry.

Viite 515 crash on floating transfer

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressLinkBuilderSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/DefloatMapperSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/FloatingCheckerSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/LinkRoadAddressCalculatorSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/RoadAddressChangeInfoMapperSpec.scala

Road address objects (and project links) are saved and fetched with the geometry source information.

Viite 549 save geometry source to road address

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/DataFixture.scala

Batch job updates road address LRM link source to current, complementary or historic source depending on which one matches. Historic only for completely removed links.

VIITE-546 batch job to update current LRM link source values

---

UI/src/model/SelectedMassTransitStop.js
UI/src/view/MassTransitStopForm.js

Bus stops are now modifiable(form is read only) if: They have an end date in the future, have no end date
Not modifiable if the end day is older than today.

DROTH-728 TR changes: Bus stops with end date should be modifiable in OTH

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectLinkDaoSpec.scala

error message now shows roadnumber, roadpartnumber and project date (as in task description)
Also fixes bug where fetching roadaddressproject startdate was switched with createdate

Viite 571 define error message when reserved

---

UI/src/view/LinearAssetLayer.js
UI/src/view/LinkPropertyLayer.js
UI/src/view/PointAssetLayer.js
UI/src/view/SpeedLimitLayer.js

Created separate event listeners(set when the layer is created) to layers the check if complementaries are shown/not shown. The existing event listeners were not active when zoomed >200 meters.

DROTH-793_complementary_links_not_drawn_after_zoom

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/oracle/OracleDatabase.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/AddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculatorSpec.scala

Fix track 1+2 direction logic in cases where they divert but have a common point of origin.

Viite 649 track incompatible bug

---

UI/src/view/AssetLabel.js

-Removed feature.setProperties(asset) meant for traffic sign labeling. RenderFeatures is already overridden in TrafficSignLabel.js

DROTH-883: Double clicking to select linear assets produces OL error

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Change table calculation fix: reconciliation of track 1+2 differences failed on combined tracks and with multiple operations. Added tests for different cases.

VIITE-753 fix change table

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Unchanged road sections were calling a different, outdated method.
Generalized the unchanged / numbering etc. partitioning, eliminated dead code.

VIITE-753 fix unchanged track change calculation

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAOSpec.scala

Tests for termination + new + transfer for two tracked road part.
Fixes bugs on losing project link data if multiple segments were on a link and new links were added to the part. Fixes delta calculator to utilize the road address id column on project links and mapping between old and new change info row.

Viite 674 terminate new transfer two track

---

digiroad2-oracle/src/main/resources/db/migration/V132__index_for_project_link_ra_id.sql
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala
viite-UI/src/model/SelectedProjectLink.js

Change the UI to always use digitization ordering.
Change delta calculator so that it understands split links in calculation.

VIITE-798 fix for split project link addressing

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectAddressLinkBuilder.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
viite-UI/src/model/RoadAddressProjectCollection.js
viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/view/ProjectLinkLayer.js
viite-UI/src/view/RoadAddressProjectEditForm.js

Fixes for incorrect split point being passed to the backend, negative values for resplitting (currently refuses resubmitting) and incorrect geometry for split links in address link builder.

Viite 798 fix split addressing

---

UI/src/view/PointAssetForm.js

-checks current layer and amount of services for asset. Hide if only one service to prevent saving "empty" asset.

DROTH-997: hide x-delete button when form is only showing once service.

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/TrackSectionOrder.scala

Keep starting link even if roundabout is created piece by piece
Fix incorrect starting calibration point geometry, use original address length on transfer / unchanged etc.

VIITE-848 addressing roundabouts piece by piece

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectSectionCalculator.scala

Fix road addressing on roads where the part has a U shape and starting point calculation fails to pick the road link at the end because of that.
* Replaced with the newer functionality to find a loose end for the track and choose from those.
* Left track starting point will be the right track starting point if the link in question is a combined track link. Otherwise old logic remains.

VIITE-860 U shaped road addressing fix

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAOSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/ProjectDaoSpec.scala

fixes bug: Where the user make new roundabout or anything else NEW action, it has right ELY code in Change table. But if user opens project data form, there is ELY is 0 for new roundabout. => The user can not continue to action mode.
adds ely code to reserve table (so we avoid ely!=projectEly in UI checks). Later we might want to remove  ely ui check if project can have multiple ely's.

Viite 858 ely==0

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/RoadAddressChangesDAO.scala

Sort change table by road, part, startAddrM, track and change type.
Pick old data first (used for all change types except new) but use new side for additions.

VIITE-923 change sort for change table

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/package.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculator.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/process/ProjectDeltaCalculatorSpec.scala

Fix for incorrectly sorting the section mapping for discontinuous reversed transfers.
Fixed mixed default coordinates (lat <-> lon) for users without default

VIITE-947 removed (incorrect) sorting for track change positions

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitter.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala

Added Discontinuity adjustment method to the pre-split links.

VIITE-983 - Jakamalla JATKUU-koodin muutos on tallennettava vain A-tai B-osalle

---

viite-UI/src/model/SelectedProjectLink.js
viite-UI/src/view/LinkPropertyLayer.js
viite-UI/src/view/ProjectLinkLayer.js

Changed the linkIds that are loaded on the SelectedProjectLink.
Decreased the zIndex of the transferred Link (dark yellow).

VIITE-991 - Selection on the map is too large when splitting

---

digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectService.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
viite-UI/src/view/ProjectChangeTable.js

Send button is enabled only if validations pass and project change table is open. Changed publishable method to check validations and renamed old method to it's current use of checking if all links have been processed. This way we are not doing same thing twice

Viite 1035 send button enabler validation

---

UI/src/model/MassTransitStopsCollection.js
UI/src/utils/backend-utils.js
UI/src/view/navigationpanel/ActionPanelBoxes.js

-check complementary box on default for MTS
-backend.utils: getRoadLinksWithComplementary added and returning roadlinkdata for integration tests

DROTH-1144_complementary_links_default_on_MTS

---

viite-UI/src/view/MapView.js
viite-UI/src/view/ProjectEditForm.js

VIITE-1063 : When there is no selection in project mode, sometimes pencil and 'Poistu projektista' link disappear
VIITE-1067 : Spinner stays spinning if the user double clicks in road part selection mode

VIITE-1063 & VIITE-1067

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/ProjectValidator.scala
digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/dao/ProjectDAO.scala
viite-UI/src/view/ProjectForm.js

On the validation made it so that will obey the rule of "Validation should be taken into consideration only the current road addresses (END_DATE is null and VALID_TO null)."
Corrected an issue on ProjectValidator checking for minor discontinuity. 
If we find possible targets of discontinuity we will now check actual road addresses for same road number and same road part and we check if the project link discontinuity actually matches those, not only that but we also make sure that at least one of the project links overlaps with the actual road addresses.
If both of those conditions are verified then we assume that there is no minor discontinuity (for said project links will be either replacing or being merged with the actual road addresses).

VIITE-1055 - Tarpeeton tarkastusilmoitus / unnecessary validation notification

---

digiroad2-viite/src/main/scala/fi/liikennevirasto/viite/RoadAddressService.scala

OTH cache only get complementary link for walways so, for now since this is urgent we are getting the complementary links by normal interface of VVH

VIITE-1109 Get complementary links from VVH instead of cache (for now)

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala

- resolveAddressAndLocation method modified to only used VKM if roadAddress is empty and if we have a defined road on the link;
- Fetch ROADNUMBER field from the attributes list to send to resolveAddressAndLocation method.

DROTH-1409 Bus stops save road address on links that haven't got road address

---

UI/src/view/linear_asset/manoeuvreLayer.js
UI/src/view/link_property/linkPropertyLayer.js
UI/src/view/providers/selectToolControl.js

-Added condition to selectToolControl: compare current layer with select tool control to activate. select tool can be activated by fetches from previous layers, causing irregularities when selecting assets/links

DROTH-1502 Link selection not working

---

UI/src/view/providers/selectToolControl.js

- drawInteraction on "drawend" redefined to do the intersect by Extent instead of by Coordinates.

DROTH-1554 Polygon tool not working at linear assets

---

UI/src/less/site/linear-asset-form.less
UI/src/model/selectedLinearAsset.js
UI/src/model/selectedLinearAssetFactory.js
UI/src/view/linear_asset/linearAssetLayer.js

-linearAssetLayer: more responsibility shifted to decorateSelection() to decide if offset is needed or not.
-pass a parameter to know if multiple assets are selected. if they are, do not use cloneDeep to avoid slowness. if not, enable cloneDeep so that separation works visually.
-selection is now removed before applying a new one to avoid duplicated layers.

DROTH-1745 UI: separation causes duplicate features

---

digiroad2-api-oth/src/main/resources/logback.xml

fix to avoid default logging level=debug when running api tests: added logback.xml file to digiroad2-api-oth path. configuration copied from the one in digiroad2-oracle

addition of logback.xml file

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessage.scala
digiroad2-api-common/src/test/resources/StopChange.xsd
digiroad2-api-common/src/test/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessageSpec.scala

- New field "vyöhyketieto" (ZoneId) added to vallu-xml message and to unit tests too.

DROTH-1758 ZoneID field needs to be added to Vallu-xml

---

conf/dev/digiroad2.properties
gruntfile.js
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

- In variable http.nonProxyHosts of digiroad2.properties file the value with reference to "oag.liikennevirasto.fi", switched to "oag.vayla.fi";
- Modified other cases who still using 'oag.liikennevirasto.fi'.

DROTH-1755 Change http.nonProxyHosts to work with vayla.fi-domain

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

In the case of bus stop 307276:
It was located on link 4385749. There is changes made to this link, so it becomes one-directional and another road is added next to it. In Tierekisteri it is terminated. But in this case, it is keeping the old link Id, but the the road now has only one direction. In the code we assume that if the old link Id still exists, the road is not terminated. This will be changed to always check for both the current link and the historic one, because the Terminated strategy uses the historic one.

DROTH-2127 updated logic to get road links on update

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala

-Override def isFloating in TerminatedBusStopStrategy so it will not go to the parent to give the wrong boolean and reason

DROTH-2268 Bus stops that need to be deleted

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

-Fixed a bug where IntegrationApi was returning a list of values instead of the value for the paved road and width asset Types

DROTH-2333 Kalpa api returning paved_roads type code in a list

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala

-Fixed a bug where the process was not creating a roadworks asset in a link with no road name
-Fixed a bug when deleting a traffic sign

DROTH-2437 (US 2218) Roadworks are not created from traffic signs

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

- With the new actions to generate history the sideCOde adjustments need to be performed first than the others actions on the links due to possibility of move the data to history tables.

DROTH-2510 Geometry not shown on lane tool

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala

https://extranet.vayla.fi/jira/browse/DROTH-2706
Oraclen to_timestamp_tz-funktio korvattu postgresql:n vastineella, eli to_timestamp-funktiolla (sisältää aikavyöhykkeen).

DROTH-2706 fix to_timestamp_tz function to work with  postgresql

---

conf/env.properties
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/Digiroad2Properties.scala
src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

https://extranet.vayla.fi/jira/browse/DROTH-2755
Testauksessa käytetty Marjukan tekemää ohjetta https://extranet.vayla.fi/jira/browse/VIITE-2579 ja seuraavia linkkejä: 
http://localhost:8080/digiroad/maasto/1.0.0/taustakartta/default/ETRS-TM35FIN/12/2762/1645.png ja 
http://localhost:8080/digiroad/maasto/rasteripalvelu/wmts/?request=GetCapabilities
--> molemmat palauttivat 401-statuskoodin.

Droth 2755 oag urls

---

src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala

ei täytetä logia turhalla tiedolla, jos tarvitaan tieto ajetaan debug tilassa tai muokataan takaisin info

 DROTH-2749 info into debug

---

aws/task-definition/dev/task-definition.json

https://extranet.vayla.fi/jira/browse/DROTH-2762
Koska aws:n tekemä rakenne ei suoraan toimi, vaihdetaan toistaiseksi takaisin meidän originaaliin kantayhteyteen, niin pääsee testaamaan muuta.

DROTH-2762 setting schema back to digiroad2

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala

Disabloidaan funktiot, jotka käyttää kuntien geometriaa/koordinaatteja.

DROTH-2762 disable calls to functions with municipality coordinates as parameters

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala

https://extranet.vayla.fi/jira/browse/DROTH-2824
Palautettu kuntien geometriaa käyttävät funktiot takaisin ja korjattu oracle-jäänteet sekä yksi testi Digiroad2ApiSpec.scalasta.

Droth 2824 add geometry functions back

---

UI/src/view/linear_asset/manoeuvreForm.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala

Lisätessä kääntymisrajoituksen tielinkki "ketjuun" tielinkkejä, oli mahdollista klikkailla useita radio-näppäimiä ennen kuin seuraavan linkin vaihtoehdot latautuivat. Tekemäni muutos disabloi jatkolinkkien valintaan käytettävät radiopainikkeet niitä klikatessa

DROTH-2806 Disabled manoeuvre extension radio buttons after click

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Luotu uusi LaneNumberOneDigit, jossa ei käytetä ensimmäistä tieosoitteen suuntaan sidonnaista numeroa. Siirytty käyttämään uutta LaneNumberOneDigittiä kaikkialla paitsi CSV-import, jossa käytetään vanhaa kaksinumeroista.

Droth 2950 lane number changes

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala

Korjaa csv import testin "Create new lane", kun expireAllAdditionalLanes funktio on vaihdettu palauttamaan Unit, Any sijaan.

Remove when().thenReturn() to fix lane creation test

---

UI/src/controller/laneModellingCollection.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LanePartitionerSpec.scala

Kaistajoukon muodostus korjattu toimimaan yksinumeroisella kaistakoodilla. Kaistajoukkoa muodostaessa tien kaistat käydään läpi ja tilanteen vaatiessa vaihtaa kaistan vastaavaan toisen sideCoden kaistaan. Teillä, joilla ei ole tienumeroa tai tiennimeä ei muodosteta joukkoa.

Droth 3000 lane highlight fix

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LanePartitionerSpec.scala

LanePartitioner tehty uusiksi, ilman geoToolsin käyttöä niin nyt ei tarvitse kikkailla ja varoa gt GraphPartitionerin bugeja. Kaistajoukkojen muodostaminen toimii nyt paremmin, eikä lisäkaistat aiheuta enää ongelmia.

DROTH-3040 fixed LanePartitioner

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LanePartitionerSpec.scala

Kaistajoukot muodostuvat nyt myös linkillä olevien lisäkaistojen mukaan, jotta lisäkaistojen muokkaus käyttöliittymässä olisi yksinkertaisempaa ja helpompaa. Valitussa joukossa on siis samat lisäkaistat. Parannettu kommentointia myös.
LanePartitioner toiminta:
1. Jaetaan kaistat kahteen joukkoon sen mukaan onko ne kaksi- vai yksisuuntaisella linkillä
2. Jaetaan kaistat joukkoihin tienumeron(tai nimen), sideCoden ja laneCoden mukaan
3. Päätellään joukon kaistoille oikeat sideCodet ja vaihdetaan tarvittaessa kaista oikean sideCoden kaistaan
4. Jaetaan kaistat lisäkaistojen mukaan joukkoihin (Luo mahdollisia "aukkoja" kaistajoukkoon)
5. Jaetaan kaistajoukko geometrialtaan vierekkäin oleviin, jotta aukkoja ei ole

Droth 3039 additional lanes draw fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RedundantTrafficDirectionRemoval.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/RedundantTrafficDirectionRemovalSpec.scala

Ensiksi haetaan kaikkien traffic_direction-taulussa olevien linkkien id:t ja linkkejä vastaavat vvh-linkit. Sitten verrataan, onko linkin liikennesuunta sama sekä traffic_direction-taulussa että vvh-linkissä. Jos liikennesuunta on sama, tieto poistetaan traffic_direction taulusta.
Testi lisää tietokantaan sekä poistettavan että validin liikennesuunnan, kutsuu poiston suorittavaa funktiota, varmistaa, että vain poistettava liikennesuunta on poistettu ja lopuksi siivoaa myös toisen lisätyn suunnan kannasta.

Droth 3061 delete updated traffic direction from db

---

aws/task-definition/dev/task-definition.json

Korjattu vahingossa asetettu väärä endpoint. Vaihdettu on-prem QA viite aws QA viitteeseen.

DROTH-3028 corrected viite endpoint to use aws QA viite not on-prem QA

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

IntegraatioAPI:in toteutettu kaikki kunnan kaistat palauttava rajapinta Velholle. Kaksinumeroista kaistakoodimuunnosta varten luotu vkmClientille json-parametria käyttävä haku. Kaistatiedoista muodostetaan jatkuvat pätkät kaistakoodin mukaan tieosanumeron alueella, ja kaistatieto viedään Velholle vaihtoehto C:n mukaisessa muodossa https://extranet.vayla.fi/wiki/display/DROTH/Kalpa+API+-+kaistatietojen+lataus
VKM hitausongelmista päästy eroon json-parametri haun avulla.

Droth 3051 velho lane api

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/LaneApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/PolygonTools.scala
src/main/scala/ScalatraBootstrap.scala

Luotu LaneApi, josta voi kysyä Digiroadin kaistatietoja kunnan alueella tai tieosoitevälillä. Siirretty aikaisempi kunnan alueelta kaistatiedot kertova rajapinta Integraatio apista osaksi LaneApia, ja luotu uusi tieosoiteväliltä kaistatiedot kertova rajapinta.  Rajapintojen toiminnan ja parametrien kuvaus confluencessa ja Swaggerissa.

Droth 3076 address space lane api

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala

Ohjelmisto jää pyörimään kun se aloitetaan palvelin tyyppisesti. Sammutetaan se manualisesti kun prosessi on loppunut.

 DROTH-3023 add exit command after akka system is turned off

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala

CSV-importilla tuodut tierekkarin kaistat ajetaan nyt fillTopologyn lävitse luonnin jälkeen, jotta voidaan korjata luonnissa syntyviä ongelmia, kuten päällekkäisyyksiä ja linkin pituuden ylittäviä kaistoja. Aikaisemmin kun on samuutettu lennossa käyttäjän siirtäessä karttaa niin tämä on tehty siinä vaiheessa.

Droth 3098 lane csv import fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RedundantTrafficDirectionRemoval.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/RedundantTrafficDirectionRemovalSpec.scala

Vaihdettu testi ajamaan rollbackilla ja suorat "traffic_direction" -merkkijonot enumiksi.

DROTH-3061 change test to run with rollback and convert string to enum

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala

FillTopology haluaa historioida kaistoja joiden id = 0 (uusi kaista, ei vielä luotu). Aikaisemmasta toteutuksesta oli jäänyt pari filtteröintiä pois. FillTopology toimii muuten ok, mutta tässä yhteydessä tulee ongelma kun yrittää historioida kaistoja joiden ID = 0, joten sen takia muutos tässä CSV-importin yhteydessä, eikä suoraan fillTopology

DROTH-3098 Added filter for problems in fillTopology

---

UI/images/link-properties/arrow-drop-red2.svg
UI/src/view/linear_asset/laneModellingLayer.js
UI/src/view/linear_asset/laneModellingStyle.js
UI/src/view/providers/layer.js

Toiminto piirtää nuolet yksisuuntaisten tielinkkien kaistoille samalla tavoin kuin tielinkeillä. Erona tielinkkitoteutukseen on, että nuoli renderöidään erillisenä komponenttina, jolloin nuoli ja kaistaviiva piirtyvät ensimmäisellä kerralla hieman eri aikaan.
Lisätty isompi punainen nuoli, koska alkuperäinen nuoli oli pienempi kuin muun väriset.
HUOM! Jos lisäkaistoja lisää ensin kaksisuuntaiselle ja sen jälkeen vaihtaa tielinkin yksisuuntaiseksi, kaistan ja nuolen väri ei täsmää (vasen alakulma). Tämä johtuu kuitenkin kaistaviivan ominaisuuksista, ei nuolen (kyseisellä linkillä on kaksi kaistaa, joten myös kaistaviivan tulisi olla syaani, eikä punainen). Asiaan kannattanee palata muiden kaistamuutostaskien yhteydessä.

Droth 3086 add direction marker to lanes

---

UI/src/view/linear_asset/laneModellingStyle.js

Renderöinnin sivuvaikutuksena muokkaantuvat kaistan koordinaattipisteet. Käytetään renderöinnissä kaistamuuttujan kopiota, jolloin renderöinti ei sotke alkuperäistä muuttujaa.

DROTH-3109 fix bug in A and B lane marker rendering

---

UI/images/center-marker-red.svg
UI/src/view/linear_asset/laneModellingLayer.js

Katkaisukohdan päälle piirretään rasti punaisella taustalla, jotta erottuu paremmin A ja B merkeistä. Tätä varten luotu punainen piste. Toteutuksen on tarkoitus mahdollistaa usean katkaisukohdan visualisointi sitten, kun kaista voidaan katkaista useasta kohdasta.

Droth 3099 create lane split point marker

---

UI/src/application.js
UI/test/run-integration-tests.js

Frontin Integraatio-testit menivät rikki edellisestä muutoksesta (ja sen korjausyrityksestä). Selvityksestä huolimatta en saanut testejä korjattua, joten alkuperäinen muutos nyt tehty käyttämättä this.Environment.name() arvoa. Toiminnallisuus pysyi nyt samana ja testit on OK, ympäristön tarkistus tehdään nyt vain application.js

DROTH-3154 Integration test build error fix

---

aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Lisätty qa job definitionin muistia maximiin 30gb

DROTH-3157 Increased qa job definition memory to max 30gb

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala

Lisätty X-Api-Key header parametri kaikkien DR rajapintojen Swaggeriin mukaan. Testatessa rajapintaa Swaggerilla voi siis syöttää Api avaimen, jolloin Swaggerin pitäisi toimia AWS-ympäristössä. Timeout tulee olemaan vielä ongelma joillain rajapinnoilla toistaiseksi.

DROTH-3162 Added X-Api-Key parameter to Swagger definition for all APIs

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Regresiota tuli kun muutettiin käyttämään .values.head, palautetaan vanha systeemi takaisin ja lisätään kommentti rikastaa kaista datalla ennen kuin laittaa päälle withLaneInfo.

 DROTH-3168 fix regresion

---

project/build.scala

Korjaus aws java sdk riippuvuuksien lisäämisen aiheuttamiin deduplication virheisiin

DROTH-3167 Sbt assembly fix

---

conf/env.properties

Asetetaan lokaalissa kehityksessä awsConnectionEnabled falseksi, jotta ei turhaan tallenneta rajapintojen vastauksia s3.

Droth 3167 Add env property for local development

---

aws/cloud-formation/taskdefinition/dev-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/prod-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/qa-create-taskdefinition.yaml
conf/env.properties
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/Digiroad2Properties.scala

S3 objektin elinaika parametrisoitu ja yksiköksi vaihdettu sekunti. Default arvoksi laitettu nyt 300 sekuntia eli 5min.

DROTH-3188 Parametrize s3 object ttl and change unit to seconds

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala

Tarkistetaan apiS3ObjectTTLSeconds env muuttujan olemassa olo ennen muunnosta int muotoon, muuten käytetään default arvoa 300.

DROTH-3188 Fix transformation to int

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala

Nostettu odotus aika tuntiin, jotta voidaan varmistua, että kaikki Akka viestit on käsitelty, eikä tule dead letter. Aikaisempi 15min ei riittänyt

Increased wait time for Akka mailbox processing

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json

Nostettu dev job definitionin resursseja, koska UpdateIncompleLinkList kaatuu muistin loppumiseen n. joka toinen kerta

Increase Memory and VCPU dev job definition

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/ValidateLaneChangesAccordingToVvhChangesSpec.scala

Buildi failasi, koska oli jäänyt bugi korjatessa samuutuksen lopputuloksen validointia, ei huomioitu linkkejä joilla ei ollenkaan pääkaistoja kun validoidaan pääkaistojen määrää. Validointieräajon koodi ja yksikkötestit käyty läpi, ei löytynyt muita ongelmia.

DROTH-3170 fixed bug and unit test

---

UI/src/assetTypeConfiguration.js

Poistettu "Näytä täydentävä geometria" -valinta kaistatyökalusta.

DROTH-3219 remove complementary geometry choice from lane modelling

---

UI/src/assetTypeConfiguration.js

Poistettu näytä täydentävä geometria raksi kaistatyökalusta. Tarkistettu, et toimii devissä.

DROTH-3129 remove complementary geometry choice from lane modelling

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

- muutettu getchanged-funktiota siten, että huomioi myös useamman kaistan pätkimisen
- korjattu kaistan pätkimistä historioinnin osalta, että historioidut kaistat kohdistuvat oikeisiin uusiin kaistoihin
- monipuolistettu ja lisätty testejä muutossanomien muodostumisen osalta
- selkiytetty kaistamuutostyyppien sanallista kuvausta

DROTH-3109 Alter change messaging to acknowledge several lane splits

---

aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json

Caching päälle QA ja Prod job definitioneissa niin voidaan ajaa RefreshRoadLinkCache eräajoa. QA jobdef voi nyt päivittää kehitystilille,  mutta tuotantoa ei, pilvioperaattorin luodessa tuotanto job definition tuotantotilille tulee caching olla true

Droth 3259 enable caching job def

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RefreshRoadLinkCache.scala

Muisti loppui kesken aikaisemmassa versiossa, kun koko valtakunnan tielinkit muistissa

DROTH-3198 Out of memory fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Lisätty exit(), koska batch ei muuten osaa lopettaa itseään toisin kuin muut batchit

DROTH-3198 added exit() for refreshCache

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Korjaus bugiin, joka kaatanut UpdateIncompleteLinkList eräajoa välillä. Nyt täydentävien linkkien käsittelyyn viedään mukaan vain niihin kuuluvat muutostiedot, aikaisemmassa toteutuksessa muutosrivit käsiteltiin kahdesti, ja se tietyissä tapauksissa kaatoi batchin

DROTH-3198 Fixed bug with duplicate changes to link attributes

---

UI/src/model/selectedLaneModelling.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/LaneUtilsSpec.scala

- Tieosoitteet ryhmitellään jatkossa linkeittäin ja alku- ja loppu m-arvojen päättely tapahtuu linkin ja kaikkien sen sisällä olevien tieosoitteiden perusteella. Ts. ei enää luoda "pätkittyjä" kaistoja jos linkillä on useampi tieosoitepätkä vaan luodaan yksi kaista per linkki.
- Digitointisuuntaa vastaan olevien kaistojen alku- ja loppu m-arvojen päättelyä muutettu. Tämä korjaa ongelman, jossa useamman tieosoite pätkän sisältävän linkin kaistojen lisääminen synnytti päällekkäisiä kaistoja, joiden sijainnit olivat virheellisiä.
- Ei käytetä enää suoraan tieosoitteen mukaisia alku- ja loppu m-arvoja vaan lasketaan niitä vastaavat sijainnit linkin nykyisen pituuden perusteella.
- Korjattu säädettyjen (lyhennettyjen) päätepisteiden päättelyä. Aiemmin tieosoitteen m-arvoista vähennettiin …

DROTH-3129 Problems with adding lanes using road address

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

LaneService unit testit jäänyt laittamatta kuntoon. Lisätty SideCodesForLinkIDs niitä vaativiin kohtiin. Yksi mock oli mennyt rikki, nyt korjattu. Kaikki testit lokaalisti OK

DROTH-3104 fixed unit tests

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Lisätty funktio, joka luo kaistaa pilkottaessa mahdollisesti poistetulle pätkälle expiroidun kaistanpätkän, jotta muutos voidaan jäljittää muutosviestiä tehdessä (käytännön tasolla muutos on sama kuin tapauksessa, jossa käyttäjä ensin pilkkoisi kaistat ja poistaisi jonkin pätkän vasta tallennuksen jälkeen).

DROTH-3109 explicit expiration of deleted split lanes

---

UI/src/controller/laneModellingCollection.js
UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingForm.js
UI/src/view/linear_asset/laneModellingLayer.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Testattu devissä seuraavista näkökulmista:
1. Kaistan lisäys
2. Kaistan poisto
3. Kaistan lisäys ja pilkkominen samalla tallennuskerralla
4. Kaistan lisäys ja pilkkominen eri tallennuskerralla
5. Kaistan pilkkominen ja jonkin pätkän poisto samalla tallennuskerralla
6. Kaistan pilkkominen ja jonkin pätkän poisto eri tallennuskerralla
7. Ominaisuuksien muutos
8. Kaistan lyhennys (UI:n näkökulmasta toisen pätkän poisto)
Lisäksi testattu, että muutosten aiheuttamat muutosviestit ChangeApista ovat järkeviä (erityisesti, että pätkimistilanteessa tulee eksplisiittinen muutosviesti myös poistetulta pätkältä).

Droth 3109 lane split problems branched from master

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala

Korjattu VVH lokitus. Ei yritä parse vastausta, ellei StatusCode ole OK. Irroitettu tämä nyt omaksi tiketikseen niin voida viedä tuotantojulkaisussa.

DROTH-3279 fix VVH error logging

---

aws/cloud-formation/batchSystem/batchLambda/cicd/prod-batchLambdaPipeline.yaml

Lisätty CodeBuildin käyttämälle roolille PutObjectAcl -luvitus. Korjauksen myötä eräajo-lambdan tuotanto pipeline toimii.

DROTH-3268 PutObjectAcl permission added to codebuild role

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Lisätty filtteröinti InUse, UnderConstruction ja Planned linkin tiloille. Aikaisemmassa toteutuksessa filtteröinti tapahtui VVH vastauksen kenttien mappauksen yhteydessä. Jääyt toteuttamatta uudessa toteutuksessa.

DROTH-3313 Fixed construction type filtering in roadLinks

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala

Laitettu väliaikaisesti VVHCLient palauttamaan tyhjä Seq ChangeInfoa haettaessa. Testattu muutamasta eri paikasta, että eri assetit latautuvat samalla tavalla ennen ja jälkeen muutoksen.

DROTH-3311 disable change info fetch temporarily

---

UI/src/view/linear_asset/careClassStyle.js
UI/src/view/linear_asset/carryingCapacityStyle.js
UI/src/view/linear_asset/cyclingAndWalkingStyle.js
UI/src/view/linear_asset/laneModellingStyle.js
UI/src/view/linear_asset/parkingProhibitionStyle.js
UI/src/view/linear_asset/pavedRoadStyle.js
UI/src/view/linear_asset/piecewiseLinearAssetStyle.js
UI/src/view/linear_asset/roadDamagedByThawStyle.js
UI/src/view/linear_asset/roadWorkStyle.js
UI/src/view/linear_asset/winterSpeedLimitStyle.js
UI/src/view/point_asset/pointAssetLayerStyles.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Piirretään niille asseteille, joissa piirretään käpy-väylät, ohuempi viiva käpy-väylän kohdalle (pl. rautateiden huoltotie). Toteutustapa sama kuin tielinkin hallinnollisen luokan tyyleissä. Kaistoissa hieman poikkeava toteutus, koska muutenkin vähän poikkeavat tyylisäännöt.
Lisäksi korjattu yksi oletettu typobugi (piecewiseLinearAssetissa kysymysmerkkityyli on kahteen kertaan normityyleissä, joista toinen on readonly-tyylien joukossa, joten tämän pitäisi varmaan olla readonly).

DROTH-3197 draw narrower lines for cycling and walking

---

UI/src/model/selectedLaneModelling.js
UI/src/view/linear_asset/laneModellingForm.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Toimi ok devissä, poislukien, että muutossanomien testaus ei onnistunut devissä (lokaalisti todettu OK), koska tiketissä DROTH-3104 tehty muutos pieceWiseLanesToTwoDigitWithMassQuery-funktioon, joka on puskettu development aiheutti virheellisiä tyyppi castauksia. Tämä bugi korjataan tiketissä DROTH-3104.

Droth 3096 promote to mainlane

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala

Lisätty käsittely VKM virheille. Rivi, jolla virhe on tullut ja muunnettavat kaistat tulostuvat raporttiin lopuksi

DROTH-3104 Added handling for VKM errors

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
aws/cloud-formation/batchSystem/batchSystem.yaml

Lisätty lupa hakea S3:sta tiedostoja BatchTaskRole-roolille. Taitaa vaatia tämän, kun käytetään InstanceProfileCredentialsProvider tunnusten saamiseksi alkupäivänmäärien import-batchissa aws-ympäristössä.

DROTH-3104 Allow batch to get object from S3

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/RoadLinkClient.scala

Tehdään nyt tyhjä lista tyyliin. Sitten kun poistetaan noi muut vvhclient hommat vois uudelleen nimetä koko object.

Droth 3254 turn off change info

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Jäänyt vastaus bäkkäriltä väärään muotoon kaistattomien tielinkkien osalta. Käyty läpi kaistakoodia, ei löytynyt muuta korjattavaa liittyen tilanteisiin, joissa kaistoja ei löydy tielinkiltä. QA:lla vastaan tullut None.get virhe näyttäisi johtuneen pyöristämisvirheestä kaistan päätepisteiden koordinaateissa. (päätepisteiden desimaaleissa heittoa, vaikka todellisuudessa osoittavat samaan pisteeseen), ei saatu toistettua ongelmaa, tuntuu toimivan riittävän hyvin.

DROTH-3351 fix roadlinks without lanes api mapping

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala

Lisätty käsittely tapauksille jossa kaistajoukkoa muodostaessa ei löydetä seuraavaa pistettä. Pistettä ei löytynyt tapauksissa, jossa kaistajoukon alku- tai loppupäässä oli linkki, jonka päätepisteet olivat samat (esim. asuinalueen ympyrän muotoinen pihatie)

DROTH-3351 Handling for cases where no nextPoint found

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

Poistettu https://extranet.vayla.fi/jira/browse/DROTH-3337 tiketissä lisätty Int konversio. Vanhan lain mukainen koodi voi sisältää myös kirjaimia esim. uuden koodin merkki 'F31':n vanha koodi on '665 a'

DROTH-3307 Removed .toInt conversion

---

digiroad2-oracle/src/main/resources/clear-db.sql

Lisätään clear-db.sql takaisin temp_road_address_info droppaaminen. Buildi ei mennyt läpi kun yritti luoda testejä varten taulun vaikka se oli vielä olemassa

DROTH-3361 rollback change to clear-db.sql

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala

Kiireessä oli jäänyt unit test korjaamatta vastaamaan nykytilannetta.

DROTH-3307 Fixed unit tests

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala

Csv import korjaus. Poistettu geneerinen polkuparametri mappaus kaistojen csv importista, jotta muut tietolajit kuten suojatiet ja esterakennelmat eivät mappaudu väärin siihen.

DROTH-3385 Fix csv import

---

digiroad2-oracle/src/main/resources/db/migration/V1_10__rename_vvh_administrative_class_column.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkOverrideDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RedundantTrafficDirectionRemoval.scala

Korvattu "vvh" termillä "masterData" roadlinkOverrideDAOssa ja sitä käyttävissä funktioissa sekä tietokannan administrative_class -taulussa.

Droth 3274 remove vvh from roadlink override dao

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Käytetään kannasta haettavilla normaaleilla tielinkeillä suoraan linkSource arvona NormalLinkInterface. Ei tarvetta hakea kannasta sourceinfo arvoa.

DROTH-3403 Remove fetching of sourceinfo from table

---

UI/src/utils/text-utils.js
UI/src/view/dynamicAssetForm.js
UI/src/view/linear_asset/prohibitionFormElements.js
UI/src/view/point_asset/servicePointForm.js
UI/test/integration-tests.html
UI/tmpl/index.html

Paranneltu data-value attribuutin muodostumista UI:lla. Luotu utils metodi joka korvaa merkkijonosta merkit å -> a, ä -> a, ö -> o sekä " " -> "-". Esim "Linja- ja kuorma-autojen pysäköintialue" => "linja-ja-kuorma-autojen-pysakointialue". Muutos koskee kaikkia tietolajeja, joihin on aiemmin lisätty data-value attribuutti.

DROTH-3373 New method for resolving data-value attribute value

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MainLanePopulationProcess.scala

Levähdysalueille halutaan luoda 31-kaista vain, jos liikennevirran suunta on linkillä kumpaankin suuntaan. Muuten luodaan liikennöinti suunnan mukainen kaista. Toteutettu tämä

DROTH-3389 Special handling for RestAreas

---

UI/src/utils/backend-utils.js
UI/src/view/laneWorkList.js
UI/src/view/link_property/linkPropertyForm.js
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneWorkListService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneWorkListServiceSpec.scala

Muutoksia Sasun kommenttien perusteella edellisestä pullarista. Luotu LaneWorkListService, ja LaneWorkListServiceSpec. Käytetään Akka actor ohjaamaan linkkien property muutoksien tunnistus ja tallennus servicelle. Lisätty LinkID + Pvm. mukaan järjestäminen työlistalla UI:lla. Poistettu turha /delete api endpointista.

Droth 3097 lane work list

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Korjataan satunnaisesti epäonnistuva testi järjestämällä validit assetit alkuarvon lisäksi myös loppuarvon mukaan.

DROTH-3280 Sort valid assets by start and end measures

---

aws/cloud-formation/batchSystem/batchLambda/batchLambda.yaml

Lisätty timeout 30 sec ja policyyn createLogGroup. Poistettu "dev" policyn nimestä, kun se ainakin itseäni hämmensi.

DROTH-3437 add createLogGroup to batch-lambda policy + change timeout

---

UI/src/assetTypeConfiguration.js

Tien leveydessä ja kantavuudessa oli nimetty single- ja multiElementEvent samalla tavalla, johon ohjelma kaatui muokkauksen perumisessa. Nämä nimetty nyt eri nimillä.

DROTH-3441 fix asset split cancel bug

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/DamagedByThawFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ChangeLanesAccordingToVvhChanges.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala

Tuotu viivamaisten kohteiden korjausoperaatiot takaisin haun yhteyteen. Erotettu ne operaatiot tähän jotka oleellisia ilman geometria muutoksia. Nostettu korjauksessa assetin ja linkin pituuksien erotuksen toleranssi 2.0. Tyhjien assettien täyttäminen tielinkeille joilla ei assettia siirretty korjausoperaatioiden kanssa samaan funktioon. Käydään rekursiivisesti korjausoperaatioita läpi linkille kunnes korjattavaa ei ole.

Droth 3451 separate fix operations

---

UI/src/less/core/variables.less
UI/src/less/site/action-panel.less
UI/src/view/link_property/linkPropertyForm.js
UI/src/view/link_property/linkPropertyLayerStyles.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/navigationpanel/pointAssetBox.js
UI/src/view/navigationpanel/roadLinkBox.js
UI/src/view/point_asset/pointAssetLayerStyles.js
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Linkki, joka on väliaikaisesti poissa käytöstä piirretään haaleammalla värillä. Sivupalkkeihin liittyvissä tiedostoissa oli vielä rakenteilla ja suunnitteilla vanhat arvot, joten nämä vaihdettu samalla.

Droth 3196 draw links temporarily out of use

---

UI/src/view/navigationpanel/manoeuvreBox.js
UI/src/view/navigationpanel/speedLimitBox.js

Poistettu ylimääräisiksi DROTH-3196 jälkeen jääneet divien sulkemiset, jotka hajottivat muokkaustilaan siirtymisen nopeusrajoituksilla ja kääntymisrajoituksilla.

DROTH-3481 Remove extra closings of divs

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala

Korjattu virhe korjausoperaatioissa. Filteröidään ennen uutta fillTopology kutsua generoidut unknown assetit pois, näille ei ole tarkoituksenmukaista tehdä korjausoperaatioita vaan generoidaan uudet korjausoperaatioiden lopuksi. Yhdenmukaistettu tuntemattomien filtteröinti käyttämään <= 0, koska korjausoperaatioissa annetaan juokseva negatiivinen numero pseudoID:ksi tuntemattomille.

DROTH-3484 fix bug with unknown assets

---

UI/src/view/navigationpanel/massTransitStopBox.js

Bussipysäkkien legendissä näytetään kaikki constructiontypet paitsi käytössä. Lisäksi uusi "väliaikaisesti poissa käytöstä" label tulee nyt tuplana perinnän kautta. Ylikirjoitetaan peritty funktio tyhjällä funktiolla ongelman korjaamiseksi.

DROTH-3488 override inherited function to fix double rendering

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala

Lisätty .value.isEmpty, suodatukseen, jotta ei suodateta pois vanhoilta tielinkeiltä uusille projektoituja assetteja

DROTH-3484 Fix bug with filtering projected new assets

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/resources/db/migration/V1_18__update_traffic_sign_F53_enumerated_value.sql

Päivitetty F53 liikennemerkin nimeksi "F53 Esteetön reitti" (vanha "F53 Vammaiselle tarkoitettu reitti"). Päivitetty myös koodissa käytetty termi vastaamaan uutta nimeä.

DROTH-2830 Update F53 traffic sign enumerated value

---

UI/src/view/point_asset/trafficSignForm.js
digiroad2-oracle/src/main/resources/db/migration/V1_19__increase_maximum_number_of_additional_panels.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISTrafficSignDao.scala

Mahdollistetaan viiden lisäkilven lisääminen samalle päämerkille. Ennen sallittu ainoastaan kolme lisäkilpeä.

DROTH-2640 Allow five additional panels for traffic sign

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala

Korjattu virhe ChangeApissa. Virhe oli tullut kun TEMP tieosoitteiden käyttö poistettu. Aikaisemmin oli .getOrElse, oli vahingossa tullut .get, joka palauttaa Option. Tielinkit on tässä vaiheessa koodia jo suodatettu tieosoitteellisuuden mukaan, joten ei tarvetta option.

DROTH-3553 fix ChangeApi type cast

---

lambda/road-link-change-handler/.dockerignore
lambda/road-link-change-handler/Dockerfile
lambda/road-link-change-handler/README.md
lambda/road-link-change-handler/aws/cloudformation/ecr/dev.yaml
lambda/road-link-change-handler/aws/cloudformation/lambda-resources.yaml
lambda/road-link-change-handler/aws/dev/README.md
lambda/road-link-change-handler/aws/dev/lambda-resources.json
lambda/road-link-change-handler/aws/dev/tags.json
lambda/road-link-change-handler/package.json
lambda/road-link-change-handler/src/index.ts
lambda/road-link-change-handler/test/index_test.js
lambda/road-link-change-handler/tsconfig.json

Alustettu tielinkkien muutosten kyselijä -lambda ja sen CloudFormation templatet.
Viedään muutokset omaan development branchiin, joka tulee CI/CD putken toteuttamisen jälkeen käynnistämään lambdan dev-pipelinen.

DROTH-3497 Add cloudformation templates and initialize lambda

---

UI/src/controller/laneModellingCollection.js
UI/src/model/selectedLaneModelling.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

korjattu getMainLaneByLinkIdAndSideCode toimimaan oikein, korjattu tieosoite etäisyyksien lasku toimimaan  oikein, tuodaan tieosoitteen sideCode frontEndille, pakollinen tieto kun lasketaan etäisyyksiä katkotuille kaistoille.

DROTH-3461 fix bug with road address value calculation

---

digiroad2-oracle/src/main/resources/db/migration/V1_22__add_expired_date_constraint.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAOSpec.scala

Vaikuttaisi toimivan devillä ok.

Droth 3541 separate queries for valid and expired links

---

lambda/asset-history-processor/aws/cloudformation/cicd/cicd-stack.yaml
lambda/asset-history-processor/aws/codebuild/buildspec.yml
lambda/asset-history-processor/aws/dev/README.md
lambda/asset-history-processor/aws/dev/cicd-parameter.json
lambda/asset-history-processor/aws/qa/README.md
lambda/asset-history-processor/aws/qa/cicd-parameter.json

Poistettu ylimääräisiä ohjeita sekä parametrisoitu lambdan koodin sisältävä kansio cicd putkessa.

Droth 3528 instructions cleanup and improvements

---

digiroad2-oracle/src/main/resources/db/migration/V1_24__edit_change_table.sql

Tehty muutos-tauluun seuraavat muutokset:
- **asset_type_id** ei voi olla null
- **value_type** voi olla null. Lisätty uusi constraint: Jos value kenttään on syötetty arvo niin value_type pitää olla myös määritetty.
- muutettu **change_type** int tyyppiseksi ja lisätty sopiva constraint
- lisätty uniikki constraint kentille: **edit_date, edit_by, change_type, asset_type_id, asset_id**, jotta vältyttäisiin duplikaatti riveiltä

DROTH-3532 change_table improvements

---

digiroad2-oracle/src/main/resources/db/migration/V1_25__drop_columns_from_change_table.sql

Pudotettu muutos-taulusta kenttiä:
- **asset_geometry** pudotettu, koska geometria voidaan laskea m-arvojen ja linkin geometrian perusteella.
- **link_geometry, link_type, link_length ja link_functional_class** pudotettu, koska linkin tiedot voidaan kysellä keskilinjavarasto:road_links_versions rajapinnasta.

DROTH-3532 Drop columns from change_table

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Korjaa bugin, joka aiheutti tuntemattoman nopeusrajoituksen päälle tallentamisessa ongelman. Tuntemattomien luonnissa oli typo, jonka vuoksi tuntemattoman start- ja endMeasure oli samat. Testiin lisätty pari riviä, jotka tarvittaessa nappaa vastaavan jatkossa.
Samalla muokattu assettien adminClasseja tielinkin mukaiseksi siellä, missä sen saa helposti linkistä (tällä ei taida olla väliä, kun SpeedLimitillä ei tätä tietoa ollut, mutta muutin nyt kuitenkin).

DROTH-3513 fix bug and add admin class when applicable

---

UI/src/model/selectedLaneModelling.js

Korjattu bugi pääkaistan paikan vaihdossa poistamalla turha metodi kutsu. Metodin kutsu on tainnut jäädä aikaisemmin vahingossa mukaan, jäänyt huomaamatta kun useimmissa tapauksissa metodi ei tee mitään, mutta tiketissä kuvatussa tilanteessa sekoitti formin.

DROTH-3559 Remove redundant reorganizeLanes method call

---

UI/src/view/linear_asset/laneModellingLayer.js

Estetty kaistan katkaiseminen, jos lisäkaista muutettu pääkaistaksi samassa muokkauksessa. Backend tallennus ja historiointi sekoaa, jos koitetaan samaan aikaan muokata kaistojen kaistakoodeja ja katkoa kaistoja uusiin osiin samalla tallennuksella. Tämän korjaaminen backend puolella veisi liikaa aikaa, riittää kun estetään vain.

DROTH-3549 Prevent lane cut if additional lane is promoted to main lane

---

digiroad2-oracle/src/main/resources/db/migration/V1_28__edit_kgv_roadlink_constraints.sql

- Pudotettu pois kgv_roadlink_mtkid constraint, sillä kgv siirtymän myötä sama mtkid voi esiintyä useammalla linkillä (esim. eri linkkien versioilla)
- Muutettu kgv_roadlink_linkid constraint kgv_roadlink_linkid UNIQUE (linkid) DEFERRABLE INITIALLY DEFERRED => ALTER TABLE kgv_roadlink ADD CONSTRAINT kgv_roadlink_linkid UNIQUE (linkid), jotta uusien linkkien lisäämisessä tauluun voidaan hyödyntää ON CONFLICT:ia

DROTH-3500 Modify kgv_roadlink constraints

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala

Pysäkki form ei auennut, koska VKM vastauksessa tuli vastauksen kenttien käsittelyssä tyyppi castaus virhe. Hieman omituinen tapaus, käytettiin .asInstanceOf[Option[String]] mutta silti debuggerissa tyypiksi näkyi Some(BigInt). Ennen tätä metodia arvon tyyppiä ei ole määritelty vaan on ollut [Any]. Lähti nyt toimimaan tällä muutoksella.

DROTH-3671 Fix VKM response value type cast

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Käyttäjät halusivat myös aikaisemmat muutokset, joilla ei ollut history_event_order_number tietoa kannassa rajapinnan vastaukseen, mahdollistettu tämä, korjattu samalla bugi end_date asettamisessa päättämisen yhteydessä. Parannettu LaneChange järjestämistä.

Droth 3674 use history events with no event number

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala

Ajattelin siirtää muutoksiin liittyvät case classit clientin ulkopuolelle. Helpompi kehittää näitä käyttäviä juttuja jatkossa, kun voi importata suoraan.

DROTH-3505 move case classes outside the client

---

UI/src/assetTypeConfiguration.js
UI/src/view/point_asset/trafficSignForm.js

Korjattu bugitiketissä kuvattu pyöräily- ja jalankulku linkkien traffic sign formin default liikennemerkin toiminta formia avatessa. Ennen korjausta loi A1.1-liikennemerkin (DR-arvo 36), vaikka formilla näkyi A11-liikennemerkki (DR-arvo 85), jos merkkiä ei vaihtanut pudotusvalikosta ollenkaan.

DROTH-3681 Fix Traffic sign form pedestrian cycling link default sign

---

UI/src/assetTypeConfiguration.js

Korjattu regex. Aikaisempi regex matchasi tyhjän "" kanssa. Mahdollisti tyhjän arvon tallentamisen, jos kumitti kentän tyhjäksi. Korjattu nyt hyväksymään vain numerot, ei tyhjää.

DROTH-3686 Fix traffic sign save condition regex for number field

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Digiroad api on hakenut tielinkin kuntakoodin nopeusrajoituksen attribuuteista eri keylla kuin muissa asseteissa. Nyt kun nopeusrajoitukset haetaan samalla tavalla kuin muutkin lineaariset, kuntakoodia ei enää löydy. Vaihdettu key samaan kuin muillakin.
Kuntakäyttäjän oikeudet katsotaan kuntakoodin perusteella UI:ssa, joten tämä ainakin lokaalin testailun perusteella korjaa kuntakäyttäjien muokkausoikeusongelman.

DROTH-3691 speedlimit editing rights bug fix

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Lisätty halutut merkit käpy-väylien liikennemerkkien ryhmään. Mahdollistaa näiden liikennemerkkien lisäämisen käpyväylille nyt myös CSV-imporitssa.

DROTH-3704 Add traffic signs to walking-cycling group

---

digiroad2-oracle/src/test/resources/smallChangeSet.json

Korjataan väärä replace info, joka ilmeisesti tullut, kun pilkoin mergen replaceiksi.

DROTH-3508 correct replace info

---

lambda/road-link-change-handler/src/client/kgv-client.ts
lambda/road-link-change-handler/test/service/change-set_test.js

Lisätty linkkien pituuden pyöristäminen kolmen desimaalin tarkkuuteen. Muutos vaikuttaa niin kantaan tallennettaviin tietoihin kuin muodostettuun muutossanomaan.
Korjattu lisäksi KgvLink parametrien järjestys oikeaksi.

DROTH-3700 round link lengths to 3 decimals

---

lambda/road-link-change-handler/aws/cloudformation/lambda-resources.yaml

Lisätty s3 bucketille toiminnallisuus lähettää muutostietoja EventBridgelle, joiden perusteella voidaan ajoittaa samuutuksen aloitus oikein. Vaatii muutoksia vielä batch lambdan konfiguraatioon sekä uusi käsittely samuutuksella (toteutetaan eri PR yhteydessä).

DROTH-3743 Add event configuration to s3 bucket

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClientSpec.scala

- Muokattu muutossettien käsittely niin, että muutossetit käsitellään erikseen vanhimmasta uusimpaan, mikäli useampi muutossetti on tietolajilla käsittelemättä. Jokainen muutossetti käsitellään omassa transaktiossa
- Lisätty puuttuvat labelit AssetTypeInfoille
- Muokattu kantaan tallennettava viimeisin onnistunut samuutuspäivämäärä vastaamaan käsitellyn muutossetin kohdepäivämäärää
- Muokattu samuutuksen raportin nimi muodostumaan muutossetin kohdepäivämäärästä, jotta jos yhtenä päivänä muodostuu useampi raportti, ei uudempi ylikirjoita vanhaa.

DROTH-3752 Process road link change sets individually

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/DirectionalPointAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdateProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/DirectionalPointAssetUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdaterSpec.scala

- Muutettu bussipysäkkien ja muiden suunnallisten pistemäisten tietolajien samuutus käyttämään tielinkkien ylikirjoitettuja arvoja (hallinnollinen luokka sekä liikennevirran suunta) ja päivitetty testit
- Korjattu lähimmän korvaustiedon etsiminen lisäämällä puuttuva tarkastus
- Lisätty puuttuvat pysäkeiden samuutuksen käynnistämis konfiguraatiot

DROTH-3755 directional point asset samuutus to use overridden link direction

---

digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala

Oli jäänyt yksikkötesteihin vielä WinterSpeedLimit, vaikka se poistettiin koko tielinkin täyttävien assettien listasta. Yksikkötestit korjattu nyt.

DROTH-3566 Fix tests to use SpeedLimitAsset instead of WinterSpeedLimit

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala

Käytetään nyt kmtk_id ja ktmtk_id_loppu kenttiä VKM:n vastauksesta linkId sijaan.

DROTH-3703 Use String KMTK ID

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala

Deviä testaillessa huomattu, että VKM ei vielä tue kunnolla Kmtk_id ja kmtk_id_loppu kenttien käyttöä tässä käyttötarkoituksessa. Käytetään link_id ja link_id_loppu kenttiä string muodossa. kmtk_id ja link_id Kentät sisältävät testailun perusteella saman merkkijonomuotoisen kmtkID:n. Kmtk_id:tä käyttäessä parametrinä palautuu vain alkulinkki, ei osaa tehdä välihakua oikein.

DROTH-3703 Use string LinkID instead of KMTK ID field in VKM

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ResolveFrozenRoadLinks.scala

Päivitetään timestamp viimeisimpään viite tielinkki verkkoon.
Paremetrisoidaan jos tulee tarvetta muuttaa useammin tai eri ympäristöissä eri viite tieverkko.

 DROTH-3788 update timetamp

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluSender.scala

Kasvatetaan connection pool asetuksia. 
Toiven vaihtoehto olisi kyl tehdä niin että jokainen kutsu loisi oman client.
Oman client luonti per kutsu tietty tarkoittaa että kyselyt ei voi hyödyntään connection pool hommia tai keskitettyä cache. 
Tää voisi olla ehkä nyt tähän hätään nopein ratkaisu kun tätä rajapintaa muutenkin kutsutaan tosi paljon.

 DROTH-3562 change how viite change client is configured

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

Hyväksytään pysäkin tallennus liikennevirran suuntaa vastaan, jos pysäkki sisältää ratikan. Korjataan bugi, jossa ei-sallitun tallennusyrityksen jälkeen, lomake jää näkyviin, mutta sitä ei voi enää muokata. Nyt lomake suljetaan, jos tallennusta ei sallita.

DROTH-3745 remove traffic direction condition from trams and fix bug

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluSender.scala

Palautetaan vastauksen logitus. Useimmiten ihan tyhjä mut 400 tai 500 tilanteissa olis hyvä tietää se.
Ei nyt viiksi tälle tehdä tätä ihmeellisempää logiikkaa.
Development niin pysyy tasoissa, varsinainen testaus nextRelease

 DROTH-3557 bring back logging also response

---

UI/src/model/selectedMassTransitStop.js
UI/src/view/navigationpanel/massTransitStopBox.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
UI/src/view/point_asset/pointsCursorTool.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

- Lisätty checkBox "Salli pysäkin luonti kävelyn ja pyöräilyn väylälle (vain raitiovaunupysäkit)", jonka ollessa enabled sallitaan lisäystyökalun kursorin liikkuminen käpy-väylilllä
- lisätty uusi virhe label jos yritetään lisätä käpy-väylälle väärän tyyppistä pysäkkiä
- Lisätty tarkastus pysäkin tallennukseen(jos käpy-linkki, pysäkin tyyppi voi olla vain ratikka)
- backEnd palauttaa linkId:n pysäkille kun haetaan asset (tarvitaan UI:lla muokattavan pysäkin linkin löytämiseksi)
- Lisätty PopUp "Oletko varma, että haluat luoda pysäkin kävelyn ja pyöräilyn väylälle?" kun tallennetaan käpy-väylälle ratikkapysäkkiä

Droth 3744 enable tram stops on pedestrian links

---

UI/src/view/point_asset/massTransitStopForm.js

- Kattaa myös DROTH-3727 samoilla muutoksilla.
- Poistaa front endistä poikkeuskäsittelyn, jolla estetään vanhentuneiden/geometrialta pudonneiden ELY-pysäkkien muokkaus ja tallennus.
- Perusteluna muuttuneet käytännöt, joiden myötä kyseiset pysäkit eivät enää ole riippuvaisia Tierekisterin vastineista.

Droth 3728 expired ely admined bus stops can be redeployed with same national

---

UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

- Pitää sisällään muutokset DROTH-3725 alaisiin tiketteihin (3726, 3727, 3728)
- Maantiepysäkkeihin liitetty erityiskäsittelylogiikka poistettu

Droth 3725 ely admined bus stops retain nationalId when assessed

---

UI/src/view/point_asset/massTransitStopLayer.js
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala

- Haaran edelliset muutokset laajennettu koskemaan myös HSL:n hallinnoimia maantiepysäkkejä.

 DROTH-3728 Removed same exception logic regarding HSL stops

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminalBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ClientUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala

Paranettu performanssia käyttäen HTTP POST kun haetaan tieosoitteita.
Ei tehdä jatkuvasti pieniä kantakyselyitä.
Käsitellään terminaalit jo haetuilla bussi pysäkeillä.
Lisätty uudelleen yrittelyä siltä varalta että tulee connection reset, nyt kun käytetään connection pool.
Pilkottu koodia paljon pienempiin osiin jotta vanhaa logiikaa voisi uudelleen käyttää tehokkaasti.
DEV kanta dumpilla tehdyillä testeillä haut helsingissä saatu menemään 1 minuutissa. Ennen meni 10 minuuttia tai enemmän.

Droth 3808 improve bus stop integration api

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala

-korjattu rikkinäinen syntaksi

Droth 3802 allow tramp stops on pedestrian ways during csv import

---

UI/src/view/point_asset/massTransitStopForm.js

Merge conflictista johtunut bugi korjattu.
Poistettu vanhentunut tramStopToSave-muuttuja ja siihen sidonnainen logiikka.
Testattu lopputulosta seuraavasti:
- Luodaan ratikkapysäkki autotielle, ei pitäisi tulla käpy-varoitusta ---> OK
- Luodaan bussipysäkki autotielle, ei pitäisi tulla käpy-varoitusta ---> OK
- Luodaan ensin ratikkapysäkki käpy-väylälle, pitäisi tulla käpy-varoitus ---> OK
- Luodaan seuraavaksi ratikkapysäkki autotielle, ei pitäisi tulla käpy-varoitusta ---> OK
- Luodaan lopuksi bussipysäkki autotielle, ei pitäisi tulla käpy-varoitusta ---> OK

 DROTH-3744 Fixed error which led to all links being treated as pedestrian

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala

Korjaa ongelman, joka tulee, kun luodaan monen linkin mittaista pysäköintikieltoa digitointisuuntaa vastaan seuraavaan risteykseen asti, Lokaalisti testaillessa en havainnut muita ongelmia. Pitää ajaa devillä niin näkee, onko mahdollisesti muitakin caseja.

DROTH-3766 fix generation of zero length parking prohibitions

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala

Korjattu yksikkötesti, olin tähän aikaisemmin keväällä vaihtanut väärän arvon jostain syystä git historian mukaan, josta nyt johtui että failaili. Nyt ok

DROTH-3493 Fix laneChange unit test

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISHeightLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISTrafficSignDao.scala

Pitäisi korjata ongelma, jossa yhdistellyssä queryssa on sekä pos että lrm lyhenne lrm_positionista. lrm-lyhennettä oli vähemmän pistemäisten daoissa, joten korvasin sen pos:lla. Testit meni läpi ja UI:lla pistemäiset tuli näkyviin, joten ei ainakaan nopeasti katsottuna hajottanut mitään muuta.

DROTH-3493 fix sql querystring inconsequency

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala

Poistettu ylimääräinen enum ja muutettu tarkistustapaa.

Droth 3727 floating ely admined bus stops keep national id when reattached to geometry to development

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Vaihdettu rekursiivinen metodi siihen, että ryhmitellään muutokset id:n mukaan ja otetaan viimeisin muutos. Tulkitsin googlailun ja yksikkötestin perusteella, että muutosten ryhmän sisäinen järjetys säilyy.
Testejä jouduttu muokkaamaan, koska eri asset_id:llä olevien muutosten järjestys ei välttämättä säily.
Lisäksi vaihdoin updateMValuesChangeInfo luomaan timeStampin, koska adjustmentin timestamp assetFilleriltä tullessa on nolla. Voin vaihtaa takaisin, jos on väärin tai ei ole väliä.

Droth 3493 fix bugs

---

digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala

Lisätään testi tilanteelle, jossa kaksisuuntainen tietolaji on koko linkin pituinen mutta tielinkillä on myös yksisuuntaisia tietolajeja.

 DROTH-3818 

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/MValueCalculator.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Lisätty tielinkki muutoksen lokitus. Aikaisempien lokien perusteella tien leveys ja käpy samuutukset jää saman tielinkki muutoksen käsittelyssä jumiin, uusi lokitus auttaa selvittämään mikä muutos kyseessä.

DROTH-3493 Add logging for roadLink change

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Uusittu eräajo, joka poistaa tuntemattomat rajoitukset, jos:
* Kaksisuuntaisella linkillä on molemminpuolinen rajoitus tai molemmat toispuoliset rajoitukset.
* Tielinkillä on noepusrajoitus ja linkki on yksisuuntainen
Lisäksi päivitetään tuntemattoman rajoituksen hallinnollinen luokka ja kuntakoodi kuten vanhassa eräajossa.

Droth 3844 fix unknown speed limit

---

UI/src/utils/geometryUtils.js
UI/src/view/linear_asset/piecewiseLinearAssetStyle.js

Visualisoidaan yksisuuntaisen tien yksipuolinen asset paksulla viivalla keskellä tietä. Pitäisi loppujen lopuksi mennä melko yksinkertaisella muutoksella. Kävin tietolajit läpi, enkä löytänyt, että jollakin olisi erikoiskäsittely.

DROTH-3847 fix one way road asset visualization

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AssetsOnExpiredLinksDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala

Korjattu tyhjän geometrian käsittely (viime ajossa geom oli jäänyt tyhjäksi rikkinäisillä TR-asseteilla, jotka olivat linkin ulkopuolella)
Jätetty TR-assetit pois käsittelystä, koska näitä ei samuuteta

DROTH-3502 fix insertin empty geometry, ignore TR-assets

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LaneUpdaterSpec.scala

Lisätty LaneProperty luokkaan tarvittavat tiedot, jotta voidaan historioida ilman SELECT subqueryä. Lisätty MassQuery insertteihin timerit

Droth 3853 optimize lane saving

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/KgvMunicipalityBorderClientSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/KgvRoadLinkClientSpec.scala

Lisätty KGVClient operaatioineen kuntarajojen hakemiseen ja pisteen sijainnin paikallistamiseen.
PointAssetCsvImporter ja ServicePointCsvImporter muokattu niin, ettei palvelupisteiden tarvitse olla tielinkillä. Kuntakoodi haetaan kgv clientin avulla. Käytetty olemassaolevia rakenteita niin pitkälle kuin mahdollista.
Muokattu virheilmoitusta niin, että viranomaisdatavaatimusten aiheuttama epäonnistuminen esitetään käyttöliittymässä oranssilla ikonilla.

Droth 3822 csv import for service points

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PostGISServicePointDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/DirectionalPointAssetUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/MassTransitStopUpdaterSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdaterSpec.scala

Otettu pois geometrian uudelleenlaskenta, jos geometria ei muutu. Lisätty "IncomingAsset" objekteille mArvo, jotta mahdollinen uudelleenlaskenta on deterministinen. Muokattu testejä siten, että mahdolliset virheet tulevat esiin. Aiemmissa testeissä, jossa testattiin täysin suoran viivan geometrialla, tulos saattoi olla uudelleenlaskennankin jälkeen oikein, vaikka se ei käytännön tapauksissa ollut.

DROTH-3887 prevent point asset movement on property update

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala

- Operaattorin toiveesta yhdenmukaistettu ääkkösten käyttöä palvelupisteiden kentän nimissä.
- tarkenne tulee toimittaa merkkijonona. Mikäli yritetään toimittaa koodiarvona, import ei mene läpi ja käyttöliittymään tulee tavanmukainen virheilmoitus.

 DROTH-3822 Fixed use of nordic alphabet in column names. Using a numeric instead of string in type extensions creates an error message on UI.

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Korjattu niin että alkuperäinen design  säilyy viellä, adjustLinearAssets niin helppo vaihtaa filltopology

 DROTH-3855 fix so it use adjustLinearAssets as wrapper

---

UI/src/view/linear_asset/serviceRoadLabel.js

Jos huoltotie tarkistettu - arvoa ei ole, property.values on tyhjä lista, jolloin yritetään etsiä arvoa undefinedille. Tarkistetaan, että property.values ei ole tyhjä. Jos on, niin huoltotie tarkistettu -arvoksi asetetaan "ei tarkistettu".

DROTH-3868 fix service road undefined value bug

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdaterSpec.scala

Jokainen uusi linkki käsitellään päivityksessä vain kerran, vaikka olisikin osa useampaa eri muutossanomaa. Ominaisuudet peritään ensimmäisestä käsitellystä muutossanomasta, jossa linkki on mukana.
esim:
- Linkki a jakaantuu kahdeksi uudeksi linkiksi: x ja y
- Uusi linkki x korvaa myöhemmin linkin z
- x on jo perinyt ominaisuudet a:lta jakaantumisen yhteydessä, joten uutta perintäprosessia ei suoriteta.

DROTH-3882_unnecessary_incomplete_links_produced

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadAddressServiceSpec.scala

Jettyn määrittelemä parametriraja johtaa hakujen eväämiseen suurissa tieosoitetietokyselyissä. Pilkotaan kyselyt 1000 linkId:n batcheihin, jotta rajaa ei ylitetä.

Droth 3906 split link query when jetty limit reached

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Päällekkäisten adjustmentien ongelma taitaa ainakin osittain johtua siitä, että foldLeftin lähtökohdaksi otetaan vanha ChangeSet, joka on jo AssetFillerissä käsitelty. Tällöin vanhat arvot tulevat mukaan. Aloitetaan yhdistely tyhjällä setillä, niin ainakaan testissä ei enää tule duplikaatteja tai limittäisiä adjustmenteja.

DROTH-3855 fix overlapping adjustments

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadAddressServiceSpec.scala

Jettyn määrittelemä parametriraja johtaa hakujen eväämiseen suurissa tieosoitetietokyselyissä. Pilkotaan kyselyt 1000 linkId:n batcheihin, jotta rajaa ei ylitetä.
Samat muutokset viety jo developmentiin. Testattu toimivaksi dev-puolen Integration API Swaggerilla, seuraavilla hakuparametreilla:
- municipality: 49 
- assetType: mass_transit_stops

Droth 3906 split link query when jetty limit reached to next release

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala

Huomasin tuossa logituksia lisäillessä, että yksi tallennusoperaation empty-check testaa eri listaa, mitä tallennetaan. Tuon vuoksi voi jotain jäädä tallentamatta, jolloin asset ei ole taulussa silloin, kun propertya tallennetaan.
Voisin ajella tämän ensiksi ja lisätä logit vasta sen jälkeen, jos tarpeen.

DROTH-3855 alter illogical empty check

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISLinearAssetDao.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdaterSpec.scala

Lisätty yksi puuttuva get sekä verified_datelle timestamp-konversio. Muokattu yhtä testiä niin, että saadaan testicase myös datalle, josta löytyy verified-tiedot.

DROTH-3855 fix dao statements

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadAddressServiceSpec.scala

Pilkkominen tarpeeton lisäkuorma, poistetaan käytöstä

 DROTH-3906 Undo splitting, as original problem was not caused by Jetty limit

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdaterSpec.scala

Muutettu logiikkaa tiiviimmäksi, jotta korjattavaksi merkittyjä linkkejä ei synny seuraavissa tapauksissa:
- Linkki lisätty ennen 15.5.2022, annettu hallinnollinen luokka ja linkin tyyppi. Tieosoitetietohaun myötä tulee mukaan Add-muutossanomana. Nämä tapaukset ohitetaan mutta lokitetaan.
- Sama new link mukana kahdessa erillisessä Split-muutossanomassa. Minkään new linkin ei tule missään tapauksessa tulla käsitellyksi kuin yhden kerran, huolimatta monessako muutossanomassa se on mukana. 
Lisää testitapauksia.

 DROTH-3882 Updates for leaks that caused unnecessary incomplete links

---

digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdaterSpec.scala

Itse bugi on taidettu korjata jo aiemmin, mutta kirjoitin nyt varmuuden vuoksi testin siitä, ettei toiminnallisen luokan tai linkin tyypin tulisi siirtyä piennartielle.

DROTH-3927 test no functional class or link type is transferred to hard shoulder

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Tuotti erroria kun oli unohtunut case _ muille tapauksille, missä ei haluta tehdä mitään.

DROTH-3666 Add underscore case for all other propertynames

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala

Korjattu huomattu virhe boolean logiikassa, tielinkin tyypin muutos vaikuttaa kaistoihin vain jos pelkästään toinen uudesta ja vanhasta linkin tyypistä kuuluu twoWayLanes joukkoon

DROTH-3666 Fix boolean logic in link type change handling

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/SpeedLimitUpdaterSpec.scala

Filtteröidään käpyväylä, ajopolku ja piennar pois tuntemattomien nopeusrajoitusten generoinnista link typen perusteella. Talvitiellä ei ole link typeä, joten sitä ei voi tässä filtterissä käyttää, mutta talvitiet filtteröidään pois jo linkkejä haettaessa kaikissa samuutuksissa (piennartiellä taitaa olla sama juttu, mutta laitoin nyt filtteriin joka tapauksessa).

DROTH-3935 exclude illegal targets for unknown speed limits

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala

Poistetaan metodi, joka muuttaa nopeusrajoituksen sidecoden both directions aina, jos kyseessä on ainoa rajoitus tielinkillä. Asia tehdään myöhemmin adjustSegmentSidecodes-metodissa, jos tielinkin liikennöintisuunta on molempiin suuntiin. Sen sijaan yksisuuntaisten tielinkkien assettien kuuluu olla uuden logiikan mukaan yksisuuntaisia, joten tämä on vanhentunut.
Käytännössä tämä metodi ei taida tehdä enää mitään, koska uusi sidecodelogiikka ajetaan tämän jälkeen. Metodin poistaminen ei rikkonut testejä, enkä havainnut UI:lla mitään outoa.

DROTH-3859 remove converting only speed limit always to both directions

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Kääntymisrajoitusta lisätessä viereistä linkkiä ei löydy, jos linkin geometriassa on väärä tarkkuus. Hyväksytään 0.01 ero tarkistuksessa, jolloin kääntymisrajoituksen pystyy lisäämään virheestä huolimatta.

DROTH-3874 find adjacent road links despite precision error in geometry

---

UI/src/view/linear_asset/manoeuvreForm.js

Formista puuttuu elementin tyhjennys, jolloin edellisen assetin työlistat jäävät näkymään. Lisätty tyhjennys. Laitoin nyt varmuuden vuoksi tonne if:n alle, kun oli muillakin formeilla, vaikka en havainnut sivuvaikutuksia ennen if:iä.

Droth 3918 manoeuvre work list bug

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ValidatorDao.scala

Kattelin, et kokonaisluvun tarkkuus varmaan suodattaa suurimman osan turhista riveistä pois. Toki tuossa on pieni mahdollisuus, että assettien ja linkin pituus on just puolikkaan eri puolilla, mutta se ei taida olla kovin vaarallista.
Muutan tarkkuuden, jos on joku näkökulma, mitä en tajunnut.

DROTH-3929 round length values in validation

---

aws/buildspecs/development.yaml
aws/cloud-formation/support-repository.yml
aws/fargate/Dockerfile

Päivitetty dev-build käyttämään uutta imagea public-repositorysta ja poistettu private-repon luominen.

Droth 3941 update docker base image

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdateProcess.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/PointAssetUpdater.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/TrafficSignUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/pointasset/TrafficSignUpdaterSpec.scala

Päivitetään liikennemerkin sidecode/validitydirection nollaksi samuutuksessa, eikä muokata bearingia, jos merkki on tieverkon ulkopuolella (location_specifier = 6).

Droth 3883 location specifier in traffic sign sidecode update

---

package.json

grunt v1.5.2 ei riitä kaikkiin varoituksiin, joten v1.5.3
https://github.com/finnishtransportagency/digiroad2/security/dependabot/10
Backbone päivitetty myös versioon 1.5.0

 DROTH-3934 grunt to 1.5.3

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala

Jos ei löydy tielinkkiä, jonka suuntima on 25 asteen toleranssin sisällä tuotavan assetin suuntimasta, annetaan sijainti tarkenne 6 ja sideCode 0 ja käytetään alkuperäistä assetin suuntimaa luonnissa.. Tehty samalla valtion tie filter korjaus liittyen tikettiin DROTH-2935

Droth 3885 csv import side code 0 fix from master

---

UI/src/utils/validity-directions.js
UI/src/view/point_asset/pointAssetForm.js
UI/src/view/point_asset/trafficSignForm.js

Peruslogiikka:
Merkki tieverkon ulkopuolelle (locationSpecifier = 6) -> sidecode 0, vaihda suuntaa disabled, validi suuntima annettava manuaalisesti
Takaisin tieverkolle -> sidecode 2, vaihda suuntaa enabled, suuntima-kenttä disabled ja suuntima lasketaan uudelleen linkin perusteella (samalla tavoin kuin assettia siirrettäessä)
(Branchatty alunperin samuutus_codesta. Pitää cherry-pick, jos viedään eteenpäin.)

DROTH-3884 ui handling for traffic signs outside roads

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala

Ilman geometriaa olevaan tyhjään after-riviin tulee tällä hetkellä yksi pilkku liikaa, kun ei huomioida otsikkorivin puuttuvaa geometriasaraketta. Excel ei tästä välitä, mutta jollain muulla (esim. pandas) avaaminen ei välttämättä onnistu. Eli poistetaan ylimääräinen pilkku.

DROTH-3854 remove incorrect comma from csv report

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Tarkistetaan ennen datafixture resetiä urlin ja usernamen perusteella, että yhteys on lokaaliin kantaan. Jos ei ole, heitetään poikkeus.
Masterille viennin jälkeen cherry-pickaan commitin samuutus_codeen, kun sieltä branchataan myös.

DROTH-3902 safeguard for data fixture reset

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/postgis/PostGISDatabase.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala

Hyväksytään resetissä yhteys myös buildin unit-test kantaan, jotta build ei kaadu.

DROTH-3902 allow aws test connection to reset unit test db

---

UI/src/view/point_asset/trafficSignForm.js

Suuntiman ja vaihda suuntaa -kenttien lähtöarvojen asettaminen oikein myös tilanteessa, jossa merkki valitaan katselunäkymässä ja siirrytään katselunäkymästä muokkausnäkymään.

DROTH-3884 bearing and validity direction fields when toggling between read only and edit

---

UI/src/view/point_asset/trafficSignForm.js

Alkuperäinen muutos ei toiminut devillä, koska ei taida päästä käsiksi valittuun assettiin. Jostain syystä lokaalissa ympäristössä en huomannut tätä ongelmaa. Siirretään tapahtumakäsittelyä ja tarkennetaan sen verran, että logiikka toteutetaan vain, jos on olemassa valittu asset.

DROTH-3884 move read only toggle event

---

package.json

jQuery v3.5.0 rikkoi vanhan self-closing tag syntaksin. Liian suuri työ alkaa korjaamaan UI-muutoksen kynnyksellä.

 DROTH-3934 revert jQuery back to 3.4.1 due incompatibility issues

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ApiUtils.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/LaneApi.scala
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala

Keskitetty virheiden käsittely. Luotu erillinen metodi virheen käsittelylle, jotta avoidRestrictions pysyisi siistinä.
avoidRestrictions käyttää samaa virheen käsittely systeemiä jos oli sitten AWS yhteys päällä tai ei.
Korjattu infinity loop kun törmätään virheeseen.
Pientä virheen käsittelyn parantelua.

 DROTH-3952 change how failure is handdled, report error

---

UI/src/view/point_asset/trafficSignForm.js

Aiempi metodi hakee liikennemerkeille vain autotiet, jolloin suuntima lasketaan virheellisesti lähimmän autotien perusteella, vaikka linkki olisi kävelytiellä. Filtteröidään linkit niin, että kävelytiet tulee mukaan.

DROTH-3884 don't filter by car roads only when recalculating bearing

---

digiroad2-oracle/src/main/resources/db/migration/V1_38__alter_road_link_replacement_table.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkReplacementWorkListDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadLinkReplacementFinder.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/RoadLinkReplacementFinderSpec.scala

- Käytetään lisättyjä / poistettuja linkkejä käsittelyssä replaceInfon sijaan
- lisätty kenttiä tauluun
- Muutettu viereisten linkkien etsintä käyttämään lisätyn linkin alku- ja loppu pisteitä geometrisen painopisteen sijaan

Droth 3937 work list for missing replacements

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala

Muutettu samuutusraporttien tallennusta niin, että yli 100MB raportit tallennetaan hyödyntäen S3MultipartUploadia. 
Rinnakkainen tallennus tehdään 100MB chunkeissa asynkroonisesti. Testattu lokaalisti 1GB:n bodyilla, joiden tallennus vei alusta loppuun keskimäärin 15-20 sekunttia.
ChangeReporter tarkistaa bodyn koon ennen tallennuskutsua selvittääkseen parhaan tallennustavan.
Tallennuksen testaukseen käytetty bucket: https://s3.console.aws.amazon.com/s3/buckets/droth-3976-multipart-upload-test-bucket?region=eu-west-1&bucketType=general&tab=objects
Bucket poistetaan pull requestin mergeämisen jälkeen.

Droth 3976 traffic sign samuutus report saving failed

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/ChangeReporter.scala

Siirretty päätös multipartin käytöstä ChangeReporterilta AwsServicelle. 
AwsServiceen määritellyn CHUNK_SIZEn koko tällä hetkellä sama kuin SINGLE_UPLOAD_MAX_SIZE, mutta kokoja voidaan arvioida uudestaan mikäli käyttötapauksissa ilmenee tarvetta.

 DROTH-3976 Moved saveMultipart decision from ChangeReporter to AwsService

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

- Poistettu viallinen parallel progress lokitus
- Palautettu vanha mergerOperations, uusi toteutus aiheutti hitautta lokien perusteella

Droth 3977 optimize linear asset samuutus

---

lambda/road-link-change-handler/src/service/change-set.ts
lambda/road-link-change-handler/test/service/change-set_test.js

Replace-infojen yhdistelyssä ollut min ja max ei sopinut tilanteeseen, jossa digitointisuunta kääntyy. Korvattu head ja last -arvoilla, koska yhdistelyssä käsitellään järjestettyä listaa. Testattu ongelmia aiheuttanut case.

DROTH-3994 fix lambda to combine replace infos with digitization change

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdater.scala

Pidetään OperationSteppien assetsBefore tyhjänä, jotta muisti ei loppuisi mergeOperationSteps. Käytetään alunperin kannasta haettuja assetteja mergetyn OperationStepin assetsBefore arvon asettamiseen.
Refaktoroitu ja yksinkertaistettu Split käsittelyä

DROTH-3977 Keep assetsBefore empty, simplify split handling

---

aws/cloud-formation/cicd/dev/DEV-cicd-parameter.json
aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/cicd/qa/QA-cicd-parameter.json
aws/cloud-formation/cicd/qa/cicd-qa.yaml

Token secretsmanagerin kautta dev- ja qa-pipelineen. Muut pipelinet taitaa olla omissa brancheissaan vielä.

Droth 3563 cicd to use secrets manager

---

aws/fargate/Dockerfile

Poistetaan xz ja openssl, jotka tulee base imagen mukana. Testataan eka devillä, että ei aiheuta ongelmia.

Droth 4016 remove xz and openssl

---

UI/src/assetTypeConfiguration.js
UI/src/controller/obstaclesRoadCollection.js
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/kgv/KgvOperation.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala

Tarkoituksena sallia tasoristeysten lisääminen UI:lla ja csv:llä käpyväylille, ajopoluille, täydentävälle geometrialle ja hallinnolliselle luokalle 99. Tällä hetkellä onnistuu vähän vaihtelevasti.
Rajapinta, josta kuntien rajat haetaan, oli muuttunut.

Droth 3774 allow railway crossings to new types

---

aws/cloud-formation/batchSystem/DEVbatchJobDefinition.json
aws/cloud-formation/batchSystem/ProdBatchJobDefinition.json
aws/cloud-formation/batchSystem/QAbatchJobDefinition.json
aws/cloud-formation/taskdefinition/dev-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/prod-create-taskdefinition.yaml
aws/cloud-formation/taskdefinition/qa-create-taskdefinition.yaml
conf/env.properties

GitHub väittää, että master -> development mergessä olisi konflikteja. Tämä haara otettu developmentista, ja siihen mergetty master ilman konflikteja. Mergetään master deviin nyt tällä tavalla, kun ei suoraan anna.

Master to development merge conflict fix

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala

Muutettu muutosapin hyödyntämiä servicejä niin, että ne hakevat poistuneen assetin linkkiä kgv:n historia-taulusta mikäli linkkiä ei löydy enää Digiroadin kannasta.
Operaattorin toiveesta lisätty logiikka, jonka myötä käsittelystä jätetään pois sellaiset assetit, joille ei löydy linkkiä myöskään kgv:n taulusta. Nämä tapaukset merkitään lokiin varoituksina.
Lisäksi yhdenmukaistettu assetien ja linkkien mappausta eri getChanged overrideissä niin, että ne kaikki kutsuvat tyypilleen sopivaa mapPersistedAssetChanges-metodia.
Testattu dev-kantaa vasten.

Droth 4020 change api to handle missing history link

---

digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdaterSpec.scala

Muokattu tarpeettomien tuntemattomien rajoitusten poisto poistamaan tuntemattomat ei-autoteiltä sekä generoimaan autoteille tuntemattomat, jos tarvitaan. Vanhaa logiikkaa yksinkertaistettu. Suuntaisuustarkastelua ei enää tarvita, kun nopeusrajoitus seuraa linkin suuntaa.

DROTH-4041 update unknown speed limit batch

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Lisäkaistoja ei voinut lisätä ja kaistoja ei voinut muokata, koska tuli NotImplementedError
Lisätty DateTime deserialization. En löytänyt mitään järkevää syytä miksi on toiminut aikaisemmin, mutta yhtäkkiä mennyt rikki, mutta tämä korjaus vaikuttaisi toimivan, rikkomatta mitään.

DROTH-4040 Implement DateTime deserialization

---

UI/src/model/selectedPointAsset.js

Tallennus kaatui backendillä, kun yritettiin tallentaa 'counter' propertyä, jota ei ole olemassa kannassa.
Suodatetaan 'counter' property pois frontilla ennen tallennusta. Kyseinen property ei ole "oikea" property, joka tallentuu kantaan, vaan kyseessä on laskettu arvo, jota käytetään lähekkäisten liikennemerkkien päällekkäiseen visualisointiin.

DROTH-4043 Filter out unneeded 'counter' property before saving

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UnknownSpeedLimitUpdater.scala

Korjataan huolimattomuusvirhe eli myös noi poistuneilla linkeillä olevat mukaan if-lauseeseen.

DROTH-4041 include expired links in if-clause

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/AwsService.scala

Korjattu bugi S3 multipart upload. Body voi sisältää merkkejä, jotka ovat useamman tavun pituisia ja tästä syystä requestBody:sta voi leikkantua loppu pois.

DROTH-4049 Fix bug with multipart upload dropping ends of chunks

---

UI/src/application.js
UI/src/model/applicationModel.js
UI/src/view/zoomBox.js

Lisätty toiminnallisuus, joka estää kauas pois zoomaamisen hiiren rullalla, mikäli muokkaukset kesken. Tehty pieni muutos canZoomOut-tarkitukseen jotta se olisi funktionaalisempi, mutta muuten koetettu olla koskematta alla olevaan himmeliin.

Droth 2844 block zooming out during modifications

---

digiroad2-oracle/src/main/resources/db/migration/V1_41__delete_unnecessary_asset_types_from_samuutus.sql
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/LinearAssetUpdateProcess.scala

Poistetaan tarpeettomat typet samuutus_success-taulusta:
150 = kyseille id:lle ei löydy typea nykykoodissa eikä asset_type taulussa
250 = palvelupiste (ei samuuteta)
310-370 = tierekisterin rajoituksia
410 = eläinvaroitukset
Lisäksi poistetaan eläinvaroitukset prosessista.

Droth 3838 remove unnecessary asset types from samuutus success

---

UI/src/view/workListView.js

Korjaa tiketin ensimmäisen bulletin, jossa työlistan kohteiden poisto ei toimi.
Tiketin toinen bullet päätettiin laajentaa omaksi tiketikseen, jotta saadaan muutokset toimimaan yhteneväisesti kaikille työlistoille.

 DROTH-4045 deletable speedLimit value should not be parsed to int

---

UI/src/view/providers/layer.js

Operaattorien toiveesta toteutettu laajennus tiketille.
Kohteiden tulee olla deselektoitavissa (ei-valittavissa? valinta poistettavissa?) myös niillä tasoilla, joilla layerin muut toiminnot eivät ole käytössä.

 DROTH-2844 Removed selectionTool deactivation from layer stoppage

---

UI/src/view/providers/layer.js

Operaattorin toiveesta viimeinen laajennus (kohteen valinta poistettavissa myös kauemmas zoomatessa) kumotaan, sillä se ei liity tiketin alkuperäiseen tapaukseen ja siitä syntyi bugi muualle käyttöliittymään. Mikäli laajennus halutaan myöhemmin toteuttaa, tehdään se omalla tiketillään.

 DROTH-2844 readded deactivation during stoppage

---

aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/cicd/qa/cicd-qa.yaml

Poistettu turha luvitus geotools-repo käyttöön
Lisätty kaikki Actionit digiroad CA repoihin ja domainiin
Lisätty "sts:GetServiceBearerToken" luvitus, CodeArtifact vaatii https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_bearer.html

DROTH-4072 Fix CodeBuild role permissions

---

project/build.scala

Muutettu CODE_ARTIFACT_AUTH_TOKEN env muuttujan käsittely valinnaiseksi, niin ei tarvitse aina asettaa kun buildaa projektia

DROTH-4072 Build auth token optional

---

project/build.scala

Päivitetty 9.2.30.v20200428 koska uudempi versio ei toiminut. Tässä jäljelle jää 6 haavoittuvuutta.

 DROTH-4028 update jetty into 9.2.30.v20200428

---

project/build.scala

https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core/2.26.7 
com.google.guava haavoittuvuus säilyy. 
https://mvnrepository.com/artifact/com.google.guava/guava/15.0
Netty korjaantuu.

 DROTH-4029 update aws sdk

---

project/build.scala

digiroad-2-oracle moduuliin oli jäänyt dependencyksi vanha versio. Korjattu nyt.

DROTH-4022 fix digiroad-2-oracle module logback version

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/RoadLinkChangeClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala

Lisää null-checkejä serialisaatioon.
Digiroad2Api.scalan deserialisaatio (case _ => JNull) aheutti jotain häikkää ja kaatoi testejä. Ei ollut aikaa perehtyä siihen ja sen tarpeeseen tarkemmin, joten jätin sen pois. Tarvetta voi analysoida paremmalla ajalla.

 DROTH-4026 Added null checks for serialization

---

project/build.scala

Päivitetty commons_codec tiketin mukaisesti. Dependency-checkissä tulee medium varoitus koskien commons_net kirjastoa, mutta  commons_codec taitaa olla puhdas. Ohjelman toiminnassa en havainnut eroa.

DROTH-4033 update commons-codec

---

project/build.scala

Commons-IO kirjastopäivitys 2.6 > 2.7 tietoturvahaavoittuvuuden takia.

DROTH-4034 Commons-IO upgrade from 2.6 to 2.7

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdaterSpec.scala

Kun muutossanomassa muutos ajopolusta ajotieksi tai toisinpäin, generoidaan toiminnallinen luokka ja linkin tyyppi riippumatta siitä, onko vanhoja arvoja olemassa. Muussa tapauksessa edetään olemassa olevan käsittelyn mukaan.

Droth 4000 improve functional class and link type samuutus

---

UI/src/assetTypeConfiguration.js

Käpy ja kaistanmallinnustyökalut eivät tallenna koska assetTypeConfiguration form käyttää väärää tietotyyppiä ('required', kun pitäisi olla true)

DROTH-4101 fix cyclingAndWalking and laneModellingTool not saving

---

UI/src/enumerations.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
digiroad2-oracle/src/main/resources/db/migration/V1_42__delete_animal_warnings.sql

Poistetaan eläinvaroitukset koodista sekä migraatiolla luodut arvot kannasta uudella migraatiolla. Assettien poistoa varten tehdyt sql:t kirjattu tikettiin, joten katselmoija voisi katsoa ne samalla.

DROTH-3966 remove animal warnings

---

UI/src/application.js

UI:n integraatiotestit taisi hajota, kun experimentalAssetsConfig jäi poistojen jälkeen undefined. Muutoksen jälkeen testit meni ainakin lokaalisti läpi.

DROTH-3338 set experimental assets empty after trAssets removal

---

UI/src/controller/speedLimitsCollection.js
UI/src/utils/backend-utils.js
UI/src/view/linear_asset/speedLimitLayer.js
UI/src/view/navigationpanel/speedLimitBox.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Lisätty kokeellinen tapa hakea UI:lle tarvittavat tiedot nopeusrajoitusten piirtämistä varten. Haetaan yhdellä SQL kyselyllä tielinkit ja niillä mahdollisesti olevat nopeusrajoitus assetit kaikkine tietoineen. 
Nopeusrajoituksilla tielinkin rajoitus ei voi olla osittain tuntematon, joten lisätty yksinkertainen toteutus tyhjän linkin muuntamiseksi tuntemattomaksi assetiksi.
Lisätty SpeedLimitBox checkBox kokeellisen haun käyttämistä varten. 
Testattu lokaalisti devi kantaa vasten SSH putken lävitse, kuopiossa 200m zoomilla yli 2x nopeampi

Droth 4050 faster speed limits get

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala

Virheitä aiheuttaneet csv:t menee nyt devillä läpi (ei kaadu). Pistotarkistuksilla katsottu, että este/tasoristeys luodaan onnistuneesti, jos deviltä löytyy koordinaateille tielinkki. Kaikilla koordinaateilla ei ole devillä linkkiä.

DROTH-4083 allow csv import to state roads

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala

roadLinkService.getExistingAndExpiredRoadLinksByLinkIds(incompleteLinks.map(_.linkId).toSet, false)
palauttaa 0 linkkiä, eli yksikään samuutuksessa generoitu puutteellinen linkki ei näyttäisi olevan käytössä. Tulostellaan luotuja puuttellisia linkkejä manuaalista tarkistusta varten.

 DROTH-3956 more test logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala

Muutettu samuutuksen alussa suoritettavaa roadlink propertyjen hakua käyttämään vanhasta koodista löytynyttä massahakua erillisten kantayhteyksien sijasta, sillä ne ovat suhteessa hitain vaihe koko prosessissa. Testataan isolla hypyllä kuinka paljon nopeampi joineihin perustuva yksittäinen massahaku on. 
Mitataan propertyRowsToValueCollection suorituksen kesto. Mikäli se osoittautuu ajallisesti kalliiksi, hylätään conversio ja muutetaan koko prosessi hyödyntämään suoraan RoadLinkPropertyRows-oliota.
Pyritty vielä alkutestailussa selkeyden vuoksi olemaan muuttamatta vanhasta koodista löytynyttä fetchOverridedRoadLinkAttributes-metodin rakennetta, mutta sitä voisi kyllä vielä refaktoroida hyödyntämään RoadLinkOverrideDao:ta. Tällä hetkellä metodi (ja muutama muu vanha saman luokan metodi) …

Droth 3956 road link property updater performance improvements

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/assetUpdater/RoadLinkPropertyUpdater.scala

Perutaan muutokset joilla prosessin alun erilliset tietokantayhteydet yhdistettiin yhdeksi joineihin perustuvaksi massahauksi valmiina olevan työkalun avulla. Syynä perumiselle se, että vanhasta koodista löytynyt fetchOverridedRoadLinkAttributes suorittaa omia filtteröintejä tyhjille riveille, mikä ei ole yhteensopivaa RoadLinkPropertyUpdaterin vaatimusten kanssa.
Erilliset kantahaut riittävät toistaiseksi.

 DROTH-3956 revert changes to getRoadLinkValuesMass due to old code not reusable

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala

Poistettu `logger.info("Send feedback scheduler started.")` täyttämästä lokia. Poistettu kehityksen aikainen TestiTunniste vkm kutsuista, parannettu lokitusta

Droth 4055 to development

---

project/build.scala

Previous json4s-jackson update broke swagger. 
Fix: Update scalatra-swagger 2.6.3 -> 2.6.5

DROTH-4109 Update scalatra swagger 2.6.3 -> 2.6.5

---

UI/src/controller/speedLimitsCollection.js
UI/src/utils/backend-utils.js
UI/src/view/linear_asset/speedLimitLayer.js
UI/src/view/navigationpanel/speedLimitBox.js
digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimit.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ComplementaryLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/KgvUtil.scala

Otettu  #3240 testatut muutokset ja tehty niistä oletustyökalu nopeusrajoitusten hakuun. Vanha haku ei säily rinnakkaisena, vaan se ja valinta-optio poistetaan.

 DROTH-4114 replace old speedLimit get with new, faster one

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala

Tietyt linkkityypit tulee aina filtteröidä pois, huolimatta hallinnollisesta luokasta

 DROTH-4114 fixed a bug where link types were not filtered from non-state roads

---

lambda/road-link-change-handler/test/service/s3-service_test.js

Build oli failannut 'since' pvm. muutoksen jälkeen, korjattu yksikkö testi nyt

Fix unit tests broken after change to 'since' date logic

---

digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/VKMClient.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ClientUtils.scala

Poistettu Connection Pooling ja sen lokitus
Poistettu VKMClient companion object, luodaan joka kutsulla kertakäyttöinen client ilman connection pooling
Poistettu käyttämättömiä metodeja VKMClient

Droth 4055 replace viite with vkm

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala

- Poistettu service tason retry(). 
- Lisätty max parallel taso 10 vkm linkId muunnoksiin 
- Lisätty parallel tason lokitus

DROTH-4055 Remove nested retry. Add max parallel level. Add logging

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala

Korjattu bugi, jossa haettujen tielinkkien tila on unohtunut siirtää lopulliseen luokkaan ja käyttöön on tullut RoadLinkin default arvo "InUse". Lisätty samalla linkSource, jolle RoadLinkillä on myös default arvo.

 DROTH-4115 fixed wrong constructionType bug

---

digiroad2-api-common/src/test/scala/fi/liikennevirasto/digiroad2/user/UserConfigurationApiSpec.scala

Yksi testi failannut. Korjattu vaihtamalla kovakoodattu ely-koodi oikeaan

DROTH-4163 Change hard coded Ely code in unit test

---

UI/src/enumerations.js
UI/src/less/site/action-panel.less
UI/src/view/link_property/linkPropertyForm.js
UI/src/view/link_property/linkPropertyLayerStyles.js
UI/src/view/navigationpanel/roadLinkBox.js

Lisätty toiminnallinen luokka 9 käyttöliittymään. Backend-koodissa tämä jo olikin. Refaktoroitu functionalClass käytämään enumeration.js:ää. Tietokantamuutokset tiketissä, katselmoija voisi katsoa ne samalla.

DROTH-4149 use functional class 9 in ui

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Lisätty puuttuvat tiedot piirrettäessä generoiduille nopeusrajoituksille. Kuntakoodin puute johti siihen, etteivät tuntemattomat kuuluneet minkään kunnan käyttäjille. constructionType lisätty future proofina, sillä myös se löytyy tunnetuilta nopeusrajoituksilta.

 DROTH-4184 Added missing information to generated unknownSpeedLimits

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/manoeuvre/ManoeuvreDAO.scala

Korjaus devi testailun perusteella, filtteröidään työlistan kääntymisrajoituskohteen linkId-listasta null arvot pois. Viimeisen kääntymisrajoituselementin destLinkId on aina null.

DROTH-4167 Filter out null link ids

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala

Testauksessa huomattu, että csv-importissa tuotavien rivien hallinnolliseen luokkaan perustuvassa rajauksessa ei oteta täydentäviä linkkejä huomioon.

DROTH-3172 include complimentary links in roadtype limitation

---

digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ServicePointBusStopDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/OthBusStopLifeCycleBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminalBusStopStrategy.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala

Osoitteiden generointi ei toiminut oikein kaikissa tilanteissa joten vaihdoin käyttämään booleania csv-importin tunnistamiseksi, ettei mene liian monimutkaiseksi setPropertiesDefaultValues-funktion toteutus. Tämä vaikutti myös testeihin, jotka muokattu sisältämään uusi boolean arvo.
Lisäksi ominaisuustiedoilta pysäkin tyyppi ja tietojen ylläpitäjä, on riisuttu pakollisuus, sekä mahdollisuus asettaa CSV-importissa arvoon 99 (ei tietoa).

DROTH-4166 fix mandatory header behavior and roadname generation logic

---

UI/src/less/site/pop-up-map-plugins.less

Kääntymisrajoituksien worklist työkalun UI-koodissa oli määritelty uudelleen .ol-pop-up luokan tyyli, jota ei todellisuudessa käytetä työkalussa. Kaksoismäärittely sekoitti Tieosoiteinfo-työkalun tyylin.

DROTH-4251 remove duplicate ol-popup styling

---

digiroad2-oracle/src/main/resources/db/migration/V1_52__increase_externalId_lenght.sql

Lisätään merkijonon pituus 10000, varmasti riittää.

 DROTH-4265 increase varchart length so that velho assets can be saved

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala

Lisätty tarkennetieto mukaan ajoneuvokohtaisten rajoitusten integraatio-APIssa välitettävään dataan.

 DROTH-4218 add prohibition additionalInfo to intergrationAPI output

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ValidatorDao.scala

validointiskriptiin oli jäänyt ylimääräinen kaarisulku

DROTH-4233 remove incorrect bracket

---

digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala

Jos yksityistien tiekunnan nimessä on pilkku, split erottaa nimen osat toisistaan. Lisätty regex splittaa vain pilkuilla, jotka eivät ole lainausmerkkien sisällä.

DROTH-4213 ignore commas within quotes to fix split bug

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala

LinearAssetPartitioner partition funktiossa oli bugi, jonka takia osa nopeusrajoituksista (mahdollisesti myös muilla tietolajeilla toistuisi) ei palautunut funktiosta, eivätkä siten piirtyneet. Bugin aiheutti tapa, jolla rivillä 50 yhdistettiin oneWay ja twoWay assettien mapit ++ operaattorilla. Jos jälkimmäisessä mapissa oli sama avain kuin ensimmäisessä mapissa, niin kyseisen avaimen arvot ylikirjoitettiin jälkimmäisen mapin arvoilla.
Käsitellään nyt twoWay ja oneWay assetit erikseen kunnes lopussa yhdistetään lopulliset Seq[Seq[T]] tulokset

Droth 4342 speedlimits bug fix

---

aws/cloud-formation/cicd/dev/cicd-github.yaml
aws/cloud-formation/cicd/qa/cicd-qa.yaml
aws/cloud-formation/ecr/PROD-ECR.yaml

Päivitetty ECR LifeCyclePolicyja: Lyhennetty vanhojen imagejen säilytyksen ikkunaa. Säilytetään korkeintaan vain 3:a tägäämätöntä imagea (devillä ja qalla säilytettävä tägi siirtyy automaattisesti uusimmalle, jolloin aiemmin tägätty jää tyhjäksi).
Lisäksi poistettu turhia sääntöjä:
- devillä ei tarvetta säilyttää qa- ja prod-tägejä
- qa:lla ei tarvetta säilyttää latest-tägiä

Droth 4318 update ecr lifecycle policy

---

UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js
UI/src/view/point_asset/pointAssetLayer.js
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PedestrianCrossingCsvImporter.scala

* korjattu bussien lomake, jonka disablointi puuttui, kun rajoitettu
* estetty pistemäisten siirtäminen, kun rajoitettu
* siirretty state road filtteri eri kohtaan suojateiden csv-importissa (vanhan koodin bugi, joka kaataa koko importin, jos alunperin löytyy lähistöltä vain valtion linkki)

Droth 4336 fix bugs

---

UI/src/view/point_asset/obstacleForm.js

Lisätty puuttuva teksti obstacle formille kuvailemaan esterakennelmien tyypit

DROTH-4276 Add info text for obstacle types on obstacleForm.js

---

UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js
UI/src/enumerations.js
UI/src/model/selectedMassTransitStop.js
UI/src/view/point_asset/massTransitStopForm.js
UI/src/view/point_asset/massTransitStopLayer.js

Korjattu joukkoliikenteenpysäkkien UI:lta bugeja ja puutteita toiminnassa liittyen DROTH-3780 muutokseen, jossa kuntakäyttäjille sallittiin virtuaalipysäkkien ylläpito valtion teillä omassa kunnassaan. 
Muutettu formin toimintaa siten, että jos vain virtuaalipysäkki on sallittu tyyppi pysäkille, niin muita tyyppejä ei voi valita, vaan ne on disabloitu. Lisätessä uutta pysäkkiä kuntakäyttäjänä valtion tielle, on nyt virtuaalipysäkki valittuna jo oletuksena. Muutoksen takia virheviesti 'Käyttöoikeudet eivät riitä kohteen muokkaamiseen. Kuntaylläpitäjänä voit muokata valtion teillä vain virtuaalipysäkkejä.' jäi turhaksi ja poistettu.

Droth 3780

---

digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitioner.scala
digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetPartitionerSpec.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala

Refaktoroidaan partitioneriin tulevien assettien rikastaminen osoitetiedoilla olemassa olevalla enrichLinearAssetAttributes funktiolla, partitionerfunktiossa rikastamisen sijaan.

DROTH-4399 refactor linearAssetPartitioner

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/PostGISSpeedLimitDao.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala

Vaihdettu tielinkkien hakumetodi sellaiseen joka hakee myös ylikirjoitetut arvot. Tämä tarvitsee tehdä, jotta muokkausrajoitus katsotaan ajantasaisen hallinnollisen luokan perusteella.

DROTH-4337 use enriched links to get correct admin class

---

digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala

Poistetaan apikey koodista. IllegalArgument tulee, jos signaturen muodostamisessa ei ole ollenkaan id:tä tai cryptokeytä.

DROTH-4344 remove hard coded api key
